### ISSUE TITLE
[Bug]: Cannot create new map in »My Maps«

### ISSUE THREAD

**Issue by AlterDepp** [nextcloud/maps#1014]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

New map created in _My maps_ are not shown in _My maps_ after reload, although there is a new folder in _Maps_ directory.

### Steps to reproduce

1. Click on »+«  (Add map) on _My maps_:  a new entry _New map_ is shown below and number of maps is 2.
2. Click on »...« (Menu) in new entry and select _Rename_. Enter new name _xxx_.
3. Click on new entry _xxx_ or reload page: Entry disappears (forever) and the number of maps is 1 again, although the new folder _xxx_ is created in _Maps_ folder.

### Expected behavior

New map entry is shown and can be selected.

### Installation method

Offical Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": { 
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nano:8080",
            "moma:8080",
            "moma:8085",
            "nano.home:8080",
            "nano.home:9080",
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {   
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },  
            {   
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }   
        ],
        "loglevel": 0,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "integrity.check.disabled": false,
        "overwrite.cli.url": "REMOVED SENSITIVE VALUE",
        "overwriteprotocol": "https",
        "updatechecker": true,
        "has_internet_connection": true,
        "app_install_overwrite": [
            "timetracker",
            "whiteboard",
            "cookbook",
            "files_texteditor",
            "pdfdraw",
            "impersonate",
            "gpxedit"
        ],
        "updater.release.channel": "stable",
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.5.1
  - audioplayer: 3.3.1
  - bookmarks: 12.1.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.1
  - cospend: 1.5.8
  - dashboard: 7.5.0
  - dav: 1.24.0 
  - deck: 1.8.3 
  - drawio: 2.1.0
  - event_update_notification: 2.0.0
  - external: 5.0.2
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.16.0
  - files_external: 1.17.0
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - gpxpod: 5.0.6
  - group_everyone: 0.1.12
  - guests: 2.3.0
  - impersonate: 1.12.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.4 
  - maps: 1.0.0 
  - news: 21.1.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.7.1
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - phonetrack: 0.7.4
  - photos: 2.0.1
  - polls: 4.1.8
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.7.1
  - spreed: 15.0.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tables: 0.3.3
  - tasks: 0.14.5
  - text: 3.6.0 
  - theming: 2.0.1
  - timemanager: 0.3.6
  - timetracker: 0.0.77
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
The log is much too big, but there are no messages related to app _maps_.
```

**Comment by tacruc** [comment]
Can you create and open the map, without renaming it?

1. Click on "+"
2. Click on "new map"

Additionally could you check if there is a ".index.maps" file within the "Maps/xxx" folder? You might need to enable "show hidden files"

**Comment by AlterDepp** [comment]
I also tried without renaming, same behavior. The ".index.maps" file is created in both cases.

**Comment by tacruc** [comment]
Ok could you check whath the maps request provides:

- Therefore Open the network console (Firefox Menu -> More Tools -> Web Developer Tools) (on other browsers in a similar place)
- Then choose the network tab
- You might need to reload the page then F5
You are looking for a request ending on maps/maps 
![image](https://user-images.githubusercontent.com/402891/227015794-58c42afb-de01-46fd-b3a3-ec38de4f74ff.png)

**Comment by AlterDepp** [comment]
I am not very familiar with this, but I tried. The response is:
```
Diese Anwendung benötigt JavaScript zum ordnungsgemäßen Betrieb. Bitte [aktiviere JavaScript](https://www.enable-javascript.com/) und lade die Seite neu
```
which means
```
This application needs JavaScript to work correctly. Please activet JavaScript  and reoad the page
```
I don’t know, if this is from nextcloud or from firefox console. When I click on the provided link to enable JavaScript it says:
```
Javascript is enabled in your web browser.
```

**Comment by AlterDepp** [comment]
Ah, and on some lines the response also contains:
```
Dieser Vorgang benötigt eine Passwortbestätigung von dir
```
which means
```
This action needs a password confirmation from you
```
There is a password entry field, but I cannot past in this, and my password is really difficult to type, so I did not test, what happens if I enter it. But I can try if it helps.

**Comment by tacruc** [comment]
But the rest is loading normally? E.g. Favorites?

**Comment by AlterDepp** [comment]
> This intressting. Can you confirm that in the header tab it is a request to .../apps/maps/maps?

No, all lines with Initiator _maps-main.js_ have the header _apps/dashboard_

**Comment by tacruc** [comment]
And maybe clear the browser cache?
![image](https://user-images.githubusercontent.com/402891/227029995-0109f9c3-0010-480a-a23f-f710d2f6a803.png)

**Comment by AlterDepp** [comment]
I searched again for lines with _headers_ containing _/apps/maps/maps_. The response is always empty.

**Comment by tacruc** [comment]
This is more expected, if you switch to raw it is probably [].

So we know:
1. MyMaps folder is created and renamed
2. .index.maps file is created
3. apps/maps/maps doesn't throw an error but just return an empty list

Can you check the mimetype of the .index.maps file?
It should be 'application/x-nextcloud-maps'
If everything is working clicking on the .index.maps file in the files app should open the maps app.

**Comment by tacruc** [comment]
You can also test if loading the new map works manually. Therefore you need the ID of the maps folder.
Therefor open the folder in the files app. The URL should look like:
https://example-domain.com/apps/files/?dir=/Maps/New%20Name&fileid=21495503
The in this example would be 21495503
Now open the URL:
{SERVERNAME}/apps/maps/m/{FILEID}

**Comment by tacruc** [comment]
>  Should it be shown on the map?
Yes, but probably only on the corresponding one. Not on the default map.

**Comment by AlterDepp** [comment]
Ah yes, I found it in _My Tracks_, So for me the Issue is solved.
Thank you very much for the support.
And thank you very much for the my-maps feature.
