### ISSUE TITLE
[Bug]: Maps won't load in safari

### ISSUE THREAD

**Issue by finsyfins** [nextcloud/maps#1015]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Updating to Maps 1.0.0 caused the app to not load on osx safari 16.3.1 or safari on ios 16.3.1. Nothing shows in the content box, the background and header are normal.
It does work on chrome. 
Nextcloud is version 25.0.2.
Nothing is showing up in the log via admin interface. 

### Steps to reproduce

Update to maps 1.0.0
go to maps in safari

### Expected behavior

work the same as chrome

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "2": "***REMOVED SENSITIVE VALUE***",
            "3": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "simpleSignUpLink.shown": false,
        "default_phone_region": "AU",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "theme": "",
        "loglevel": 2,
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "enabledPreviewProviders": [
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\MPEG",
            "OC\\Preview\\WEBM",
            "OC\\Preview\\QUICKTIME",
            "OC\\Preview\\PNG",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - calendar: 4.3.1
  - camerarawpreviews: 0.8.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_linkeditor: 1.1.13
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - imageconverter: 1.3.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 1.0.0
  - metadata: 0.17.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - previewgenerator: 5.2.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.8
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.17.0
  - admin_audit
  - bruteforcesettings
  - circles: 25.0.0
  - contactsinteraction: 1.6.0
  - encryption
  - survey_client: 1.13.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

php 8.0.26

**Comment by tacruc** [comment]
Sorry have no safari to test or reproduce this.
Could you check the browser console? Is there a build of safari running on Linux?

**Comment by tacruc** [comment]
And can you check the output of the network console? Are there failing requests?

**Comment by finsyfins** [comment]
the browser is running on osx
sure. let me know how to output the network console and Ill give it a try

**Comment by tacruc** [comment]
I guess somewhere there:
https://support.apple.com/en-gb/guide/safari/sfri20948/mac

And and on Firefox and chrome one tab is volles browser console and one something with network.

**Comment by tacruc** [comment]
For the network I would look there:
https://jun711.github.io/web/how-to-inspect-network-request-and-response-headers-on-safari/

But from there you should be able to find the browser console somewhere

**Comment by finsyfins** [comment]
This is the only error I could find in the browser console
<img width="1676" alt="Screen Shot 2023-03-23 at 10 16 51 pm" src="https://user-images.githubusercontent.com/123302808/227187727-da228874-d5b0-4b83-aee0-1282ee452c93.png">

No errors showing up in network section, and the files prefixed with "maps" are loading fine

**Comment by tacruc** [comment]
Ok, I was able to reprudce it with the gnome browser. 
Can you test if #1017 works for safari?

**Comment by finsyfins** [comment]
ive patched the 5 files. cleaned browser cache and server cache using:
echo 1 > /proc/sys/vm/drop_caches
echo 2 > /proc/sys/vm/drop_caches
echo 3 > /proc/sys/vm/drop_caches
sudo redis-cli flushall async

But the file report-error-map-action.js is still loading the old version. Is there a cache I have missed? Suspect others have not updated either.

Also tried:
sudo systemctl reload apache2

Is there something I have missed to force the patches to load?

**Comment by finsyfins** [comment]
I think the issue Im having getting the patch to work is the maps-main.js is not reflecting the changes you made to the files. Is there a way I can for this to update? or do I have to remove app and install patched one to rebuild the maps-main.js?
