### ISSUE TITLE
[Bug]: Collaborative Maps does not work

### ISSUE THREAD

**Issue by gpgmailencrypt** [nextcloud/maps#1016]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 25.0.5
Maps 1.0.0

I can create a new collaborative map, but when trying to rename it the "..." menue disappears and after clicking on the name the whole map disappears. This happens with firefox and chromium. The only message in the logs is
```
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }

Object { _uid: 117, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": [], … }
​"$attrs": 
​"$children": Array []
​"$createElement": function $createElement(t, n, a, i)
​"$el": <button class="content-buttons button-v…tem action-item--single" data-v-60378d00="" data-v-b05d7434="" data-v-5b8980a1="" type="button" data-v-0c63f5ea="">
​"$listeners": 
​"$options": Object { parent: {…}, _parentVnode: {…}, _componentTag: "NcButton", … }
​"$parent": Object { _uid: 116, _isVue: true, __v_skip: true, … }
​"$refs": Object {  }
​"$root": Object { _uid: 7, _isVue: true, __v_skip: true, … }
​"$scopedSlots": Object { icon: nn(), … }
​"$slots": Object { icon: (1) […] }
​"$vnode": Object { tag: "vue-component-48-NcButton", data: {…}, children: undefined, … }
​__v_skip: true
​_c: function _c(t, n, a, i)
​_data: Object { … }
​_directInactive: false
​_events: Object { focus: (1) […], blur: (1) […], click: (1) […] }
​_hasHookEvent: false
​_inactive: null
​_isBeingDestroyed: false
​_isDestroyed: false
​_isMounted: true
​_isVue: true
​_props: Object { disabled: Getter & Setter, type: Getter & Setter, nativeType: Getter & Setter, … }
​_provided: Object {  }
​_renderProxy: Object { _uid: 117, _isVue: true, __v_skip: true, … }
​_scope: Object { detached: true, active: true, _vm: true, … }
​_self: Object { _uid: 117, _isVue: true, __v_skip: true, … }
​_staticTrees: null
​_uid: 117
​_vnode: Object { tag: "button", data: {…}, children: (1) […], … }
​_watcher: Object { deep: false, user: false, lazy: false, … }
​<get $attrs()>: function get()
​<set $attrs()>: function set(t)
​<get $listeners()>: function get()
​<set $listeners()>: function set(t)
​<prototype>: Object { constructor: o(e), disabled: Getter & Setter, type: Getter & Setter, … }
NcActions.js:2:2436
```

### Steps to reproduce

1. Click on the plus symbol (add map) => a new map appears (named "Neue Karte 2" and is greyed out)
2. Click on the "..." menu and select "rename"
3. Enter a new name ("test") and press the "->" button

4. The new map can't be used: clicking on the name deletesit, or after reloading the page the map vanishes
 
![maps](https://user-images.githubusercontent.com/13087633/227339762-90430ebd-6ec2-4a38-8e1e-36b4e97f5b37.png)

### Expected behavior

map should still exist an there should be a way to activate 

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - analytics: 4.8.0
  - announcementcenter: 6.5.1
  - approval: 1.0.12
  - audioplayer: 3.3.1
  - bookmarks: 12.1.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_automatedtagging: 1.15.2
  - files_external: 1.17.0
  - files_linkeditor: 1.1.13
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - geoblocker: 0.5.7
  - guests: 2.3.0
  - health: 1.6.1
  - integration_dropbox: 1.0.6
  - integration_github: 1.0.15
  - integration_google: 1.0.9
  - integration_onedrive: 1.1.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 1.0.0
  - metadata: 0.17.0
  - news: 21.1.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.7.2
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - phonetrack: 0.7.4
  - photos: 2.0.1
  - polls: 4.1.8
  - previewgenerator: 5.2.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quicknotes: 0.8.5
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_nextcloud_notification: 3.6.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.1.2
  - updatenotification: 1.15.0
  - user_migration: 3.0.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
no information available
```

**Comment by tacruc** [comment]
Did you have a look at #1014?

All the debug steps would be intressting here, too.

There disabling and enabling the maps app resolved the Issue.

**Comment by gpgmailencrypt** [comment]
Thanks. I did miss this bugreport. But it did help. In my case I had to reinstall the maps app and now it works fine

**Comment by AlterDepp** [comment]
After upgrade to Maps version 1.0.2 my maps disappeared again. What I did:
- disable and enable maps: didn’t help
- uninstall and install maps: didn't help
- Now my _Maps_ folder did not exist anymore. I cannot say, when it disappeared.
- Tried to create a new map: ok
- Restored Maps/xxx folder from backup
- `occ files:scan`
- Now my favorites for the map are back, but tracks still are missing, although I see them when I click on _Open folder_. I hope, they will come back soon …

**Comment by tacruc** [comment]
@AlterDepp can you check if you find something in the update log?
If the tracks are gone tryp OCC maps:scan-tracks

**Comment by AlterDepp** [comment]
Hmm, can only find an _updater.log_ from 2018, the normal log does not contain something special. Is there another log file?
