### ISSUE TITLE
Favorite gpx import ignores trk and trkpt attributes

### ISSUE THREAD

**Issue by simonspa** [nextcloud/maps#102]
First of all huge thanks to all contributors, I have been following the work on this app for a while now and decided tonight was the time to spin up a Docker image to test it - and I am very, very impressed! Many things already work very beautifully.

When importing some GPX files via the "Favorite" section I noticed that only way points (i.e. `<wpt>` tags) are imported and shown on the map, while the `<trk>` and `<trkpt>` attributes are ignored. I understand you want this feature to only focus on places (and later offer the import from Google via #66 ) - maybe you can make this more clear somehow?

Again, this is really just suggestions for polishing, I'm super happy with the current state already (and imported my 700+ contacts from my production Nextcloud just to see them on the map...)

**Comment by jancborchardt** [comment]
Hey @simonspa thanks a lot for your feedback! :) Since your suggestions are 2 distinct issues, could I ask you to open a separate issue for one of them? That helps us organize and tackle things one by one.

And thanks a lot for the praise! Contributions are also always welcome. :rocket:

**Comment by jancborchardt** [comment]
(Also, if you like the app, a nice review on the app store is much appreciated :D https://apps.nextcloud.com/apps/maps )

**Comment by simonspa** [comment]
Hej @jancborchardt I opened a ticket for renaming "my tracks". I'm not sure if I should also do that for the other part, cince I'm not so sure myself how this could be made more intuitive. I'll do when I come up with an idea.

Also, could someone of you add me to the Transifex project for Maps? I have a few suggestions to make concerning the German translation (few things are mixed up)

**Comment by jancborchardt** [comment]
@simonspa thanks! Regarding the translations, you have to apply at https://www.transifex.com/nextcloud/nextcloud/maps/ and the German translators will add you. :)

**Comment by jancborchardt** [comment]
What do you think @eneiluj @tacruc? I would guess tracks which are part of favorites should also be imported?

**Comment by simonspa** [comment]
I'm actually not so sure of that. If we look at how big commercial maps applications handle this, it's rather only used to store individual locations. Otherwise we start duplication functionality, because tracks are also read from file store...

Maybe we can keep it as it is, only import `wpt` features and show a warning if `trk`s are present but not imported?

**Comment by tacruc** [comment]
I agree with simonspa, right now favorite's is for locations, not a general favorite folder which can store tracks, devices or contacts, too.

So I think the general question is, if favorites is more like a bookmark of different things (places, tracks, contacts, devices etc.), than the current favorites would need to be renamed to places.
Or if we keep it as a favorite places (short favorites) and we show a warning or import trk points directly to tracks?

Personally I have no preference.

**Comment by jancborchardt** [comment]
Ahh ok. No, Favorites should stay as it is then, so just for places. Basically we should keep wording and the flow "compatible" with Google Maps, so to say.

Then probably there should be some sort of notice if a favorites file has Tracks, and then to separately upload them? Could also work automatically in the future.

**Comment by eneiluj** [comment]
Favorites are definitely only about places and not lines or polygons IMO.

Hmmm so we should just warn that only waypoints (`<wpt>`) will be imported when done from "favorites" context menu. We could also rename "Your favorites" to "Your favorite places". What do you think?

**Comment by tacruc** [comment]
Favorites is fine as a name, hence other applications use the same. 
@eneiluj lets only show the warning if there are any trk points etc. in the gpx. Otherwise it would just bother people.

**Comment by simonspa** [comment]
@eneiluj I agree, but I would also implement it as @tacruc suggests: import the waypoints and only warn if there were tracks or polygons which have been ignored.

Renaming to "Favorite Places" sounds like a good idea, it makes it even more clear what to expect.
