### ISSUE TITLE
[Bug]: Creation of dynamic property $lockingProvider is deprecated at apps/maps/lib/Hooks/FileHooks.php#46

### ISSUE THREAD

**Issue by rcmlz** [nextcloud/maps#1023]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using php 8.2 the nextcloud-log is flooded with

{"url":"/remote.php/dav/files/user/","message":"Creation of dynamic property OCA\\Maps\\Hooks\\FileHooks::$lockingProvider is deprecated at nextcloud/apps/maps/lib/Hooks/FileHooks.php#46","version":"26.0.0.11"}

### Steps to reproduce

1. switch to php 8.2
2. watch log while using maps app

### Expected behavior

In anticipation of future incompatibilities this depreciation warning should be addressed.

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
 - calendar: 4.3.1
 - circles: 26.0.0
 - cloud_federation_api: 1.9.0
 - comments: 1.16.0
 - contacts: 5.2.0
 - contactsinteraction: 1.7.0
 - dav: 1.25.0
 - deck: 1.9.0
 - federatedfilesharing: 1.16.0
 - files: 1.21.1
 - files_automatedtagging: 1.16.1
 - files_external: 1.18.0
 - files_pdfviewer: 2.7.0
 - files_rightclick: 1.5.0
 - files_sharing: 1.18.0
 - files_trashbin: 1.16.0
 - files_versions: 1.19.1
 - forms: 3.2.0
 - groupfolders: 14.0.0
 - lookup_server_connector: 1.14.0
 - mail: 3.0.2
 - maps: 1.0.0
 - notes: 4.7.2
 - oauth2: 1.14.0
 - password_policy: 1.16.0
 - passwords: 2023.3.21
 - photos: 2.2.0
 - previewgenerator: 5.2.1
 - privacy: 1.10.0
 - provisioning_api: 1.16.0
 - recognize: 3.7.0
 - settings: 1.8.0
 - sharebymail: 1.16.0
 - systemtags: 1.16.0
 - text: 3.7.2
 - theming: 2.1.1
 - twofactor_backupcodes: 1.15.0
 - twofactor_totp: 8.0.0-alpha.0
 - twofactor_webauthn: 1.1.2
 - updatenotification: 1.16.0
 - viewer: 1.10.0
 - workflowengine: 2.8.0
```

**Comment by tacruc** [comment]
php8.2 is not yet supported see #983

**Comment by adripo** [comment]
@tacruc this issue is still present with the latest version that supports PHP8.2
