### ISSUE TITLE
'Share this location' produces 'Geo link could not be copied to clipboard`

### ISSUE THREAD

**Issue by cnic023** [nextcloud/maps#1028]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Double-click location on the map. Menu selection 'share this location'. An error message is produced: 'Geo link could not be copied to clipboard'
This error did not occur on the latest stable version of Maps prior to v 1.0.1

### Steps to reproduce

1.Double-click location on the map.
2.Menu selection 'share this location'
3.An error message is produced: 'Geo link could not be copied to clipboard'

### Expected behavior

Expect lat and long data to be copied to the clipboard (windows 10)

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Maps 1.0.2 (all other apps up to date including Contacts
```

### Additional info

Nextcloud version 25.0.5

**Comment by tacruc** [comment]
Which browser are you using, and are you using https?

**Comment by cnic023** [comment]
Hello Arne,
I am using Firefox 102.9.0esr (64-bit)  (I tried Chrome also but with no success)
I am using https
Best wishes
Chris
