### ISSUE TITLE
[Bug]: CORS header missing

### ISSUE THREAD

**Issue by cup1dstunt** [nextcloud/maps#1048]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I open maps the map is empty. It shows pictures, but the maps itself is not drawn.

My browser shows me the following error message:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.mapbox.com/styles/v1/mapbox/streets-v8?access_token=NEXTCLOUDUSERNAME. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 401.

Cross-source (cross-origin) request blocked: The same-source rule prohibits reading the external resource on https://api.mapbox.com/styles/v1/mapbox/streets-v8?access_token=NEXTCLOUDUSERNAME. (reason: CORS header 'Access-Control-Allow-Origin' missing). status code: 401.

### Steps to reproduce

1. open maps
2. let the page load - it loads the assets (pictures and positions but doesn't load the map

### Expected behavior

Seeing a nice map in the background

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
activity: 2.18.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.3
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contactsinteraction: 1.7.0
  - cpanelmailsync: 0.1.7
  - dashboard: 7.6.0
  - dav: 1.25.0
  - external: 5.1.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_accesscontrol: 1.16.0
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.2.0
  - geoblocker: 0.5.8
  - groupfolders: 14.0.2
  - impersonate: 1.13.0
  - integration_google: 2.0.0
  - integration_gptzero: 0.1.1
  - integration_openai: 1.0.7
  - integration_openstreetmap: 1.0.5
  - integration_replicate: 1.0.6
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - maps: 1.0.2
  - memories: 5.1.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - passwords: 2023.5.30
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - richdocuments: 8.0.1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - socialsharing_email: 2.6.0
  - spreed: 16.0.3
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - unsplash: 2.2.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - analytics: 4.8.0 (installed 4.8.0)
  - encryption: 2.14.0
  - onlyoffice: 7.8.0 (installed 7.8.0)
  - recognize: 4.0.1 (installed 4.0.1)
  - twofactor_totp: 8.0.0-alpha.0
  - user_ldap: 1.16.0
```

**Comment by tacruc** [comment]
Do you use a valid access token? NEXTCLOUDUSERNAME doesn't look like a proper access token for mapbox.

**Comment by cup1dstunt** [comment]
The access token is my nextcloud username. I put the NEXTCLOUDUSERNAME in there. I can't find an option to enter API key anywhere. I installed openmap integration and put in the maptiler api key in linked accounts in nextcloud, but it does not work.

**Comment by cup1dstunt** [comment]
Found the error:  the mapbox api key has to be entered in the general settings of nextcloud.
