### ISSUE TITLE
Does not load in Safari

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/maps#106]
The app does not load in Safari, i.e. only a white screen is shown.

<img width="1437" alt="Bildschirmfoto 2019-09-01 um 12 16 09" src="https://user-images.githubusercontent.com/8535968/64074960-57c0aa00-ccb2-11e9-8591-63884bf08755.png">

Tested with Nextcloud 17.0.0 Beta 3, Safari Version 12.1.2, maps 0.1.1

App works with Chrome, Firefox.

**Comment by eneiluj** [comment]
Hey, thanks for the bug report. Could you provide the browser error log?

**Comment by eneiluj** [comment]
It has probably already been fixed with #100. I need those logs to be sure.

**Comment by ho1ger** [comment]
Sure. Is this enough? If not please tell me what you need exactly.

<img width="1452" alt="Bildschirmfoto 2019-09-01 um 12 20 27" src="https://user-images.githubusercontent.com/8535968/64075016-f1885700-ccb2-11e9-89fa-2d359207cf76.png">

**Comment by eneiluj** [comment]
Yep it's enough thanks. So yes it's the same problem #100 solves. You can try latest master branch or wait for v0.1.2 which will normally come today.
