### ISSUE TITLE
[Bug]: App is not starting (php lower 8.1 required)

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/maps#1062]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Bug]: App is not starting (php lower 8.1 required)

### Steps to reproduce

1. install php 8.1
2.try to install maps
3.

### Expected behavior

install + activation working

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
not needed for this bug
```

**Comment by mcwimh** [comment]
Same problem except with php8.2-fpm nextcloud 6.0.2 mariadb imaginary redis-server coturn notify_push, ubuntu 22.04

**Comment by adripo** [comment]
I will paste here the comment I posted in the related issue for better visibility:

> 
> From what I was able to test, if you upgrade to docker image v26 (which has PHP 8.2.7) and you already have the latest `maps` version installed (1.0.2), it will continue to work. If you, otherwise, start from a clean installation, the appstore will show the latest compatible version 0.1.10 (which I think didn't had any check on PHP version) that will not work. If you try to force the installation (which I did) by manually downloading the v1.0.2 inside the folders and enable it, you will have the following error:
> 
> ```
> ./occ app:enable maps
> App "Maps" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 8.1 is required.
> ```
> 
> Is there any real limitations in using newer php versions, or it can simply be updated here? https://github.com/nextcloud/maps/blob/master/appinfo/info.xml#L37
> 
> Thanks @skjnldsv @tacruc
