### ISSUE TITLE
[Bug]: Photos not being shown in map

### ISSUE THREAD

**Issue by adriano-pinaffo** [nextcloud/maps#1063]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Only 2 photos out of 500+ show up in the map. Clicking on My photos -> Clear Photo Cache gives me the error "Failed to clean photo cache" on the top right and the console shows a GET error response of 400 (seems to be an error given by Axios.
![image](https://github.com/nextcloud/maps/assets/28174227/19b4f037-fc35-497a-b0a8-eca943d84fcc)

When I run `php occ maps:scan-photos` on the "nextcloud-aio-nextcloud" container I get the erorr:
`Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 479232 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35`
![image](https://github.com/nextcloud/maps/assets/28174227/a38182eb-3b76-4813-a734-7791243f681f)

The first times I ran `php occ maps:scan-photos` it was scanning and saying some 20 images were added but they never showed in the map. After some 4 attempts, it started giving me the error above.

I already trying restarting the containers and even removed and restarted the mastercontainer, but nothing changed.

### Steps to reproduce

1. add photos
2. go to maps and notice they don't show up there (even after weeks)
3. try to clear the cache and see the errors

### Expected behavior

Photos expected to show up in maps

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install of the server?

Fresh Nextcloud Server install

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
bash-5.1# sudo -u www-data php occ config:list system

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 479232 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35
```

### List of activated Apps

```shell
bash-5.1# sudo -u www-data php occ app:list

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 479232 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
The correct occ command for AIO is documented here: https://github.com/nextcloud/all-in-one#how-to-run-occ-commands

**Comment by joshtrichards** [comment]
@adriano-pinaffo When you're running PHP from the CLI it looks like you're PHP `memory_size` has been reset to the default for some reason. 

As @szaimen mentioned, try running the command in the supported way:

`sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ your-command`

Though I have a suspicion maybe you override your PHP_MEMORY_LIMIT or `NEXTCLOUD_MEMORY_LIMIT and possibly typo'd it somehow? See https://github.com/nextcloud/all-in-one/tree/main#how-to-adjust-the-php-memory-limit-for-nextcloud

Most common mistake would using `MB` instead of `M` or similar for `GB` vs `G` or

**Comment by adriano-pinaffo** [comment]
@szaimen @joshtrichards
The PHP problem may be one of the problems, but in reality the main problem is that the photos are not scanning, even when occ commands run. What should I look into?
You can see below, now, I re-run the command but around 30 photos only were "added". But in the maps there are only 2 photos, and in total I have more than 500 hundreds photos that were not scanned.

![image](https://github.com/nextcloud/maps/assets/28174227/6395de17-c255-4dc5-b38f-9cac43c8400b)

**Comment by christinloehner** [comment]
@szaimen @adriano-pinaffo @joshtrichards 

I'm just coming up with exactly the same problem in Nextcloud 28 AIO. All containers are uptodate.

When issuing the command manually like this:

`docker exec -it --user www-data nextcloud-aio-nextcloud /bin/bash`
`./occ maps:scan-photos`

**it only scans the photos inside the user folders, but not all the thousands photos inside the group folders.**
