### ISSUE TITLE
[Bug]: Autoload path not allowed: /var/www/html/custom_apps/cadviewer/appinfo/application.php

### ISSUE THREAD

**Issue by chunzhenzyd** [nextcloud/maps#1090]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I wanted to enable cadviewer, but got an error:
Autoload path not allowed: /var/www/html/custom_apps/cadviewer/appinfo/application.php

### Steps to reproduce

1.enable cadviewer
2.
3.

### Expected behavior

cadviewer enabled

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install of the server?

Fresh Nextcloud Server install

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
cadviewer
```

### Nextcloud Logs

```shell
{"reqId":"KStj4MPK3MqDF1i2kvb0","level":3,"time":"2023-07-02T14:53:07+00:00","remoteAddr":"192.168.10.19","user":"root","app":"settings","method":"POST","url":"/settings/apps/enable","message":"could not enable apps","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /var/www/html/custom_apps/cadviewer/appinfo/application.php","Code":0,"Trace":[{"file":"/var/www/html/lib/autoloader.php","line":166,"function":"isValidPath","class":"OC\\Autoloader","type":"->","args":["/var/www/html/custom_apps/cadviewer/appinfo/application.php"]},{"function":"load","class":"OC\\Autoloader","type":"->","args":["OCA\\Cadviewer\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":217,"function":"class_exists","args":["OCA\\Cadviewer\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":400,"function":"isBootable","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["cadviewer"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":137,"function":"loadApp","class":"OC\\App\\AppManager","type":"->","args":["cadviewer"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":890,"function":"loadApp","class":"OC_App","type":"::","args":["cadviewer"]},{"file":"/var/www/html/lib/private/Installer.php","line":164,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["cadviewer",["OCA\\Cadviewer\\Migration\\RegisterMimeType"]]},{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->","args":["cadviewer"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["cadviewer"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Settings\\Controller\\AppSettingsController"],"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Settings\\Controller\\AppSettingsController"],"enableApps"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["settings.AppSettings.enableApps"]]},{"file":"/var/www/html/lib/base.php","line":1064,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/autoloader.php","Line":141,"message":"could not enable apps","exception":{},"CustomMessage":"could not enable apps"}}
```

**Comment by chunzhenzyd** [comment]
root@hlfd/nextcloud:/var/www/html# ls -lrt /var/www/html/custom_apps/cadviewer/appinfo/application.php
-rw-r--r-- 1 www-data www-data 3963 Jul  2 14:51 /var/www/html/custom_apps/cadviewer/appinfo/application.php

**Comment by chunzhenzyd** [comment]
oot@hlfd/nextcloud:/var/www/html# php --version
PHP 8.2.7 (cli) (built: Jun 14 2023 05:26:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

**Comment by tacruc** [comment]
Wrong repository, don't know what maps has to do with cadviewer

**Comment by chunzhenzyd** [comment]
> Wrong repository, don't know what maps has to do with cadviewer

Hi, tacruc
Which repository should I go?
I'm a new comer of nextcloud.

BR
Jack Zhang

**Comment by tacruc** [comment]
The one of the cadviewer app

**Comment by chunzhenzyd** [comment]
> 

Hi, tacruc
Would you please send me the url, I can't find it. Thanks!

BR
Jack Zhang
