### ISSUE TITLE
[Bug]: maps 1.1.0 does not work with nextcloud 27.0.0

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/maps#1097]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Erros messages when I try to activate maps at nc 27.0.0.1:

Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
Autoload path not allowed: /var/www/nextcloud/apps/maps/appinfo/application.php

[m```
aps] Fatal: OCP\AutoloadNotAllowedException: Autoload path not allowed: /var/www/nextcloud/apps/maps/appinfo/application.php at <<closure>>

 0. /var/www/nextcloud/lib/autoloader.php line 166
    OC\Autoloader->isValidPath()
 1. <<closure>>
    OC\Autoloader->load()
 2. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 129
    class_exists()
 3. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 94
    OC\AppFramework\Bootstrap\Coordinator->registerApps()
 4. /var/www/nextcloud/lib/private/Installer.php line 143
    OC\AppFramework\Bootstrap\Coordinator->runLazyRegistration()
 5. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp()
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Settings\Controller\AppSettingsController->enableApps()
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
10. /var/www/nextcloud/lib/base.php line 1064
    OC\Route\Router->match()
11. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

POST /nextcloud/index.php/settings/apps/enable

```

### Steps to reproduce

1. install maps, create favourites
2. update to nc 27.0.0
3. deactivate maps
4.activate it again
5. see the erro in the logs


### Expected behavior

it should work like charm

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not important for this issue
```

### List of activated Apps

```shell
not important for this issue
```

### Browser Console

```shell
XHRPOST
https://www.test.at/nextcloud/index.php/settings/apps/enable
[HTTP/2 500 Internal Server Error 141ms]

	
POST
	https://www.test.at/nextcloud/index.php/settings/apps/enable
Status
500
Internal Server Error
VersionHTTP/2
Transferred953 B (109 B size)
Referrer Policyno-referrer
Request PriorityHighest

	
cache-control
	no-cache, no-store, must-revalidate
content-encoding
	br
content-length
	96
content-security-policy
	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
content-type
	application/json; charset=utf-8
date
	Tue, 04 Jul 2023 09:39:11 GMT
expires
	Thu, 19 Nov 1981 08:52:00 GMT
feature-policy
	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
pragma
	no-cache
referrer-policy
	no-referrer
server
	Apache
strict-transport-security
	max-age=15552000;
vary
	Accept-Encoding
x-content-type-options
	nosniff
x-download-options
	noopen
X-Firefox-Spdy
	h2
x-frame-options
	SAMEORIGIN
x-permitted-cross-domain-policies
	none
x-request-id
	RsNbTEohXFgJ8oyXMfUO
x-robots-tag
	index, follow
x-xss-protection
	1; mode=block
	
Accept
	application/json, text/plain, */*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	en-US,en;q=0.5
Connection
	keep-alive
Content-Length
	31
Content-Type
	application/json
Cookie
	oc_sessionPassphrase=anonym; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; anonym=anonym; nc_username=anonym; nc_token=%anonym%anonym; nc_session_id=anonym
Host
	www.test.at
Origin
	https://www.test.at
requesttoken
	anonym=:anonymanonym
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-origin
TE
	trailers
User-Agent
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0
Object { apps: Getter & Setter, categories: Getter & Setter, updateCount: Getter & Setter, loading: Getter & Setter, loadingList: Getter & Setter, gettingCategoriesPromise: Getter & Setter, … }
​
__ob__: Object { shallow: false, mock: false, vmCount: 0, … }
​
apps: 
​
categories: 
​
gettingCategoriesPromise: 
​
loading: 
​
loadingList: 
​
updateCount: 
​
<get apps()>: function get()​
<set apps()>: function set(t)​
<get categories()>: function get()​
<set categories()>: function set(t)​
<get gettingCategoriesPromise()>: function get()​
<set gettingCategoriesPromise()>: function set(t)​
<get loading()>: function get()​
<set loading()>: function set(t)​
<get loadingList()>: function get()​
<set loadingList()>: function set(t)​
<get updateCount()>: function get()
​​
length: 0
​​
name: "get"
​​
prototype: Object { … }
​​
<prototype>: function ()
​
<set updateCount()>: function set(t)​
<prototype>: Object { … }
 
Object { appId: "maps", error: {…} }
apps.js:44:10
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 284 globals.js:59:15

​
```

**Comment by tacruc** [comment]
Duplicate #1069
