### ISSUE TITLE
[Bug]: Newly created "My Map" disappears when clicking on it

### ISSUE THREAD

**Issue by ratte-rizzo** [nextcloud/maps#1098]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I add a new map under "My Maps" and click on it, it disappears. However, the subfolder under "Maps" is created. 

### Steps to reproduce

1. Create a new map under "My Maps" by clicking the +
2. New map "New Map X" is created under the "default" map
3. Click on "New Map X"
4. "New Map X" disappears and the ... menue is also not avail
5. Subfolder under Maps is created

### Expected behavior

I expect "New Map X" not to disappear when clicking on it and be able to add points to this map. 

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.220",
            "nest.deutsch-u.de",
            "cloudbeere",
            "xgkvysk0cuieexfu.myfritz.net",
            "office.deutsch-u.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.3.2",
        "overwrite.cli.url": "https:\/\/nest.deutsch-u.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "social",
            "sharerenamer",
            "cookbook",
            "files_retention",
            "previewgenerator",
            "apporder",
            "occweb",
            "news",
            "phonetrack",
            "health",
            "workflow_kitinerary"
        ],
        "updater.release.channel": "stable",
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memories.exiftool": "\/var\/www\/html\/apps\/memories\/exiftool-bin\/exiftool-amd64-glibc",
        "memories.gis_type": 1,
        "memories.vod.path": "\/var\/www\/html\/apps\/memories\/exiftool-bin\/go-vod-amd64"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - calendar: 4.4.3
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - cookbook: 0.10.2
  - cospend: 1.5.10
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_automatedtagging: 1.16.1
  - files_pdfviewer: 2.7.0
  - files_retention: 1.15.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.3.1
  - health: 1.6.2
  - integration_mastodon: 2.0.2
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - maps: 1.1.0
  - memories: 5.2.1
  - music: 1.8.4
  - news: 21.2.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.8.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - occweb: 0.1.0
  - password_policy: 1.16.0
  - phonetrack: 0.7.6
  - photos: 2.2.0
  - polls: 5.1.0
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recognize: 4.2.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sharerenamer: 3.2.0
  - side_menu: 3.9.1
  - snappymail: 2.28.3
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - apporder: 0.15.0 (installed 0.15.0)
  - bruteforcesettings: 2.6.0 (installed 2.4.0)
  - encryption: 2.14.0
  - files_external: 1.18.0 (installed 1.8.0)
  - radio: 1.0.3 (installed 1.0.3)
  - recommendations: 1.5.0 (installed 0.4.0)
  - social: 0.6.1 (installed 0.6.1)
  - spreed: 16.0.4 (installed 16.0.4)
  - suspicious_login: 4.4.0
  - timetracker: 0.0.79 (installed 0.0.79)
  - twofactor_totp: 8.0.0
  - user_ldap: 1.16.0
  - workflow_kitinerary: 1.2.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by DavidMndz** [comment]
I confirm this still happens in Maps 1.1.0.

**Comment by vegardengen** [comment]
This happens also for me.

docker image nextcloud:stable-apache, Nextcloud v26.0.3, Maps 1.1.0

**Comment by vegardengen** [comment]
DIgging a bit into this.

The problem is that the call to <nextcloud>/apps/maps/maps returns no elements.

The following code, I guess, is the culprit (from MyMapsService.php, function getAllMyMaps):

```
             $MyMaps = [];
                $MyMapsNodes = $userFolder->search(new SearchQuery(
                        new SearchComparison(ISearchComparison::COMPARE_EQUAL, 'mimetype', 'application/x-nextcloud-maps'),
                        0, 0, []));
```

This came in commit cc0a8d7b3 - maybe #919 ?

**Comment by tacruc** [comment]
I know of a bug that the id of the new created map is zero after creation, but the maps folder is created. After a page reload the new map is usable.

So probably the create map function probably should return the id but doesn't do it.

**Comment by vegardengen** [comment]
I can get to the map if I know the link, which I will get to know if I open it just before it disappears from "My Maps". 
It will be there until a page reload. Maps are usable, they just don't show up in my maps, and I have no way, really, to find them.

I only guessed that it does not get the correct mime type on the folder.

- Vegard

On Tue, Jul 25, 2023 at 01:04:37AM -0700, Arne Hamann wrote:
> I know of a bug that the id of the new created map is zero after creation, but the maps folder is created. After a page reload the new map is usable.
> 
> So probably the create map function probably should return the id but doesn't do it.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nextcloud/maps/issues/1098#issuecomment-1649328553
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

-- 
- Vegard Engen, member of the first RFC1149 implementation team.

**Comment by vegardengen** [comment]
I found the reason for my issue.

For some reason, mimetypemapping.json had not been updated, so it didn't get the correct mimetype.

When updating that file manually with the entries the code specifies should be added to it, my next created map works properly, and I am able to see it under my maps.

Might get around to track why it didn't get updated, too, but this is just a hint.

**Comment by tacruc** [comment]
@vegardengen
Each map correspondence to a folder in the files app.
When you create a map can you check if the corresponding folder is created an contrains a .index.maps file?
If not could you check if placing a .index.maps file (just an empty file) into an folder make this folder listed as map?

**Comment by vegardengen** [comment]
It does not, and I saw that this file was there.


What helped for me was adding the missing entries to the mime type mappings. I have no idea why they weren't added, I can see
that there's code for adding them.

I am running in docker, btw, if that makes any difference.


On Tue, Jul 25, 2023 at 04:35:30AM -0700, Arne Hamann wrote:
> @vegardengen
> Each map correspondence to a folder in the files app.
> When you create a map can you check if the corresponding folder is created an contrains a .index.maps file?
> If not could you check if placing a .index.maps file (just an empty file) into an folder make this folder listed as map?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nextcloud/maps/issues/1098#issuecomment-1649660866
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
- Vegard Engen, member of the first RFC1149 implementation team.

**Comment by tacruc** [comment]
So adding a OCC command to recreate the mime mappings might be a work around?

**Comment by vegardengen** [comment]
Likely.


On Wed, Jul 26, 2023 at 04:44:40AM -0700, Arne Hamann wrote:
> So adding a OCC command to recreate the mime mappings might be a work around?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nextcloud/maps/issues/1098#issuecomment-1651646734
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
- Vegard Engen, member of the first RFC1149 implementation team.

**Comment by theerijn** [comment]
For who wonders what the mime mapping should be; this is what works for me:
./config/mimetypealiases.json:
`{
    "application/x-nextcloud-maps": "maps"
}
`
./config/mimetypemapping.json:
`{
    "maps": [
        "application/x-nextcloud-maps"
    ]
}
`

**Comment by tacruc** [comment]
Can anyone test  #1118?
