### ISSUE TITLE
Switch Contacts backend

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#11]
What’s there left to do to fix the Contacts display? :)

@v1r0x mentioned: »I think (or rather hope) that we only have to fix these lines:«
https://github.com/nextcloud/maps/blob/master/js/script.js#L1100
https://github.com/nextcloud/maps/blob/master/js/script.js#L1110
https://github.com/nextcloud/maps/blob/master/js/script.js#L1291
https://github.com/nextcloud/maps/blob/master/js/script.js#L1589-L1594

cc @Henni @skjnldsv @e-alfred :)

**Comment by v1r0x** [comment]
I haven't had a look at the contacts app, but @Henni should know more about it :wink:
