### ISSUE TITLE
Personlized basemap

### ISSUE THREAD

**Issue by buoncri** [nextcloud/maps#115]
It can be usefoul to have in admin config section a way to add a personlized basemap that can be served to all users. It can be a wms, wmf or wmtf resource.

**Comment by jancborchardt** [comment]
Is this related to **Add info on tile layers & fair use somewhere, allow to add own tile provider #83**, as in adding your own tile layer?

**Comment by buoncri** [comment]
Yes it partially is. Tile server is a wmtf resource.
