### ISSUE TITLE
postTouch hook seems to prevent creation of new user

### ISSUE THREAD

**Issue by alexthamm** [nextcloud/maps#116]
Hi,

I think the maps app tries to read the exif information of the Coast.jpg file when the postTouch hook is being triggered. In my setup this file is empty at that moment. This causes the copyr operation for the skeleton to abort. On first login, users are welcomed with an "Internal Server Error". After manual deletion of the user data/<user> directory the users can login.

[request_logs.log](https://github.com/nextcloud/maps/files/3568970/request_logs.log)

[system-report-2019-09-03.txt](https://github.com/nextcloud/maps/files/3569001/system-report-2019-09-03.txt)

Please let me know if you need anything else.

**Comment by tacruc** [comment]
I should be fixed with PR #91

**Comment by gpearson100** [comment]
Looks like I'm having this same issue with version 0.1.2
