### ISSUE TITLE
Adding a routing API key still displays the message "There is no routing engine set"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#117]
I added my Mapbox API key in the settings and it does show up in the routing options, but the warning message also still does:
![mapbox notice](https://user-images.githubusercontent.com/925062/64187408-dc592700-ce70-11e9-96eb-94ec4a69a4e9.png)

The note should be removed when another routing engine apart from the OSRM demo has been added.

**Comment by tacruc** [comment]
Solved with #118

**Comment by jancborchardt** [comment]
Fixed by https://github.com/nextcloud/maps/pull/118
