### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/maps#1188]
Hi,
I'm looking to contact the maintainers/devs of this project to speak about a potential collaboration. Is there a contact form? 
I can be reached at: jefiqo90.giwesa94@murena.io (temporary email address)
best regards,
Rik

**Comment by tacruc** [comment]
Hi @Rik44444 
We have a chat at:
https://cloud.nextcloud.com/index.php/call/ii2tvobc bei
