### ISSUE TITLE
With huge photo collection loading of map markers timeout

### ISSUE THREAD

**Issue by Twilek-de** [nextcloud/maps#120]
I have about 2600 photos with exif information in my database. It worked in the beginning. When I now open Maps it will show the loading ring beside Photos and after several minutes will simply stop loading with the following apache error
```
(70007)The timeout specified has expired: [client x.x.x.x:25711] AH01075: Error dispatching request to : (polling)
```

And even while it worked loading the map with a lot of photos took a LONG time (I estimate more than 2 minutes).

**Comment by tacruc** [comment]
Wired, I just loaded the map with 11k photos and the photos where loaded in a few seconds.
What kind of database are you using?

**Comment by Twilek-de** [comment]
Hosted Mysql server via TCP connection. Normally that works very fast.

**Comment by tacruc** [comment]
Are there any other errors in the log?

**Comment by Twilek-de** [comment]
Nothing in the apache log and nothing in the nextcloud log.

And... it now works. it still takes a long time (about 20-30 seconds) to load the page but now it shows 23K images on the map. Does it do some housekeeping after a rescan like generating thumbnails or so? It still shows the box that the media is not scanned for a couple of seconds, althought I did a complete scan via occ.

**Comment by Twilek-de** [comment]
And fails again... It sometimes works and other times times out. I have not yet been able to determine when what happens.

**Comment by Twilek-de** [comment]
I have raised the timeout of apache from 300 to 600 seconds. Now it always seems to load.

**Comment by jancborchardt** [comment]
So what could we improve here? If the user is an admin, show a notification about that PHP timeout and a link to the docs how to increase it?

**Comment by Twilek-de** [comment]
I actually did not raise the the PHP timeout but the timeout for page loading of apache itself (the "Timeout" parameter).

**Comment by Twilek-de** [comment]
And I had a timeout again, reloaded the map and it worked. As long as nobody else is seeing this, it is probably some quirk in my configuration as I cannot really reproduce it.

**Comment by jancborchardt** [comment]
Ok, closing hence. :) We can always reopen if it comes up again for other people.
