### ISSUE TITLE
Better documentation needed how to keep maps information current

### ISSUE THREAD

**Issue by Twilek-de** [nextcloud/maps#121]
I think you should include in your documentation when Maps gathers information. If I want to keep my Photos map data current, do I have to do a nightly cron job to rescan the photo data or does maps scan images when they are uploaded or does it scan new images via the NC cron functionality?

**Comment by tacruc** [comment]
It listen to file creation and change events. So after the initial scan now full scan is required anymore.

**Comment by jancborchardt** [comment]
Yep, as @tacruc said it Just Works™. If there’s any issues, please report them though. :)

**Comment by Twilek-de** [comment]
That´s the best way, my point is just say this somewhere in the docu so people aren´t wondering.
