### ISSUE TITLE
[Bug]: v29 compatibility

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/maps#1218]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

maps app shows a blank page when opened on v20 beta1

### Steps to reproduce

1. Update a v28 instance to v29

### Expected behavior

App is rendering

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
In theory a very long list, but due to the major release beta 1 phase expected to be an incompatibility
```

**Comment by tflidd** [comment]
I tried to use version 1.3.1 as untested app, but I get a white screen and the following details in the logs:
{"reqId":"NaRj3ZShhtOXqlNMidM8","level":3,"time":"2024-04-18T08:12:08+00:00","remoteAddr":"ip","user":"user","app":"PHP","method":"GET","url":"/apps/maps/","message":"Cannot redeclare OCA\\Maps\\Controller\\remove_utf8_bom() (previously declared in /usr/local/www/nextcloud-test/apps/maps/lib/Controller/PublicTracksController.php:53) at /usr/local/www/nextcloud-test/apps/maps/lib/Controller/TracksController.php#47","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0","version":"29.0.0.17","data":{"app":"PHP"}}

**Comment by tacruc** [comment]
I have 5 more days correct?

**Comment by tacruc** [comment]
Hi Folks,
I just tried to reproduce the Issue:
I tried v29 beta1 and git stable29 branch, with maps master and maps 1.3.1.
The maps app loaded on my dev system in all cases.

Did the Issue resolve on your systems with any patch of the server?

**Comment by AndyScherzinger** [comment]
Issue still present I think, but currently I only get an HTTP 500 on 29.0.0 RC3 but I don't have access to the logs myself.

**Comment by tacruc** [comment]
Never mind, fund the issue. 
https://github.com/nextcloud/maps/pull/1244 should be running.

**Comment by tacruc** [comment]
Ok made it to the app store: https://apps.nextcloud.com/apps/maps/releases?platform=29#29

**Comment by AndyScherzinger** [comment]
Yet not released as a stable version ;)
<img width="648" alt="2024-04-25 18_13_28-Maps - Apps - App Store - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/maps/assets/1315170/bd5dcc16-6806-4974-ad00-8a28301bdf9c">
