### ISSUE TITLE
Improvements with regard to image viewing/selection

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/maps#124]
One thing to start with: I think this could become one of the greatest add ons for nextcloud... The ability to browse geotagged information is super cool...

But one thing that bugs me a bit is that you cannot view a picture in full screen even after clicking on it. Please add this feature in future releases.  I could imagine this in a couple of different ways:

- simply open the picture full screen
- jump into the folder that contains that picture (maybe also interesting for the user that allows finding not geotagged pictures probably related to this picture)
- create some kind of virtual folder that contains the pictures shown on the current map section (this would allow the user to quickly browse the photos taken around a certain spot)

The idea with the virtualized folder could also be interesting for users to e.g. filter contacts that live in a certain area, etc...

**Comment by tacruc** [comment]
Issue #93
