### ISSUE TITLE
Ability to customize favourites' colors

### ISSUE THREAD

**Issue by thegrasshopper104** [nextcloud/maps#1245]
It'd be great if you could choose a custom color for a category of favorites, (similarly to how you can choose a color for a Deck board.)

Additionally, it might make sense to let users customize marker shapes, like what [UMap](umap.openstreetmap.fr) does.

**Comment by fabalexsie** [comment]
Seems to be related to https://github.com/nextcloud/maps/issues/164?

**Comment by thegrasshopper104** [comment]
Looks like this is a duplicate
