### ISSUE TITLE
Displaying of tracks not working (with Theming app disabled)

### ISSUE THREAD

**Issue by escoand** [nextcloud/maps#125]
Thanks for this nice app. Finally all the geo tags in my pictures have more sense than my technical interest. I'm really happy.

But I've a problem with my tracks. I can see the `/index.php/apps/maps/tracks` endpoint is delivering the data correctly but instantly throw an error:
```
TypeError: OCA.Theming is undefined[Weitere Informationen]
tracksController.js:280:13
addTrackMap   https://.../apps/maps/js/tracksController.js:280:13
getTracks/<   https://.../apps/maps/js/tracksController.js:416:17
u             https://.../core/js/dist/main.js:39:22734
fireWith      https://.../core/js/dist/main.js:39:23546
k             https://.../core/js/dist/main.js:39:70718
t/<           https://.../core/js/dist/main.js:39:74242
```

**Comment by jancborchardt** [comment]
Looking at the error message – did you disable the "Theming" app? Then cc @skjnldsv 

Otherwise cc @tacruc @eneiluj :)

**Comment by skjnldsv** [comment]
@juliushaertl is the theming expert @jancborchardt 	:)

**Comment by jancborchardt** [comment]
@skjnldsv haha, I actually wanted to cc @juliushaertl, didn’t notice I did not! Must be muscle-memory :heart:

**Comment by escoand** [comment]
@jancborchardt you're right, with theme app enabled it's working. But I don't do and don't want to use it.

**Comment by jancborchardt** [comment]
Right, thanks for checking! :) So the app should still work with Theming disabled. I assume this is cause tracks are by default colored with the theming color.

What’s the best course of action here @juliushaertl @eneiluj @tacruc? Seems just a check whether Theming exists is missing, and when there’s no theming it could use the default Nextcloud blue #0082c9 as fallback?

**Comment by juliushaertl** [comment]
```OCA.Theming ? OCA.Theming.color : '#0082c9'``` should do the trick. Note that whenever you use something in the OCA namespace make sure to check that it is actually available, since those are app related and might be disabled/not loaded by default.

**Comment by tacruc** [comment]
@escoand Do you manage to check if PR #125 solves the problem for you?

**Comment by escoand** [comment]
@tacruc fix is working for me
