### ISSUE TITLE
Optimize loading of tiles from OSM?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/maps#127]
Hello,

sometimes the map tiles are loaded really slow which results in white spots or blurred squares on the map. I don't have this problem with GpxPod/Motion/Phonetrack also build by @eneiluj on the same server. I can see several GET requests to different tile servers in the browser console and it takes a long time (more than a minute at times) to get them from the server.

Is there anything that can be done to speed up the loading time of the tiles? I don't think it is a problem with the connection speed because I tried it on an internet connection with up to a gigabit.

**Comment by jancborchardt** [comment]
Is caching possible at all @eneiluj @tacruc?

Also very related issues:
- Allow storage of maps offline #12
- Add info on tile layers & fair use somewhere, allow to add own tile provider #83

**Comment by eneiluj** [comment]
@jancborchardt The browser should cache map tiles. This is none of our business :wink:.

@e-alfred I honestly don't know what is happenning to you. Map tiles are loading at the same speed between GpxPod, PhoneTrack and Maps for me.

**Comment by szaimen** [comment]
OSM is also very slow in my installation...

**Comment by e-alfred** [comment]
@eneiluj It seems like the tile servers cancel request sometimes. Here is a screenshot on how it looks like if that happens:

![image](https://user-images.githubusercontent.com/10073629/64954504-128da200-d886-11e9-94ad-ee47f9010d61.png)

**Comment by szaimen** [comment]
Maybe that's an issue with chromium-based Browsers? 🤔
BTW: the ESRI map-data inside the maps app is loading much faster then the OSM map-data although the ESRI map-data are satellite-pictures and shouldn't be faster in loading time in my understanding.

**Comment by StyXman** [comment]
`'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` is not longer the right URL:

https://operations.osmfoundation.org/policies/tiles/

> The correct URL for the tiles is `https://tile.openstreetmap.org/{zoom}/{x}/{y}.png`. Other subdomains are not recommended as they may be slower or discontinued in the future.
