### ISSUE TITLE
When setting the language to "German (personal)" it does not use the right term

### ISSUE THREAD

**Issue by szaimen** [nextcloud/maps#131]
When setting the language to "German (personal)" it does not use the right term
Here a screenshot:
![image](https://user-images.githubusercontent.com/42591237/64355091-e27e0d80-d000-11e9-9a23-7ef420ee89be.png)
"Ihre Spuren" should correctly be called "Deine Spuren" like the others do.

**Comment by jancborchardt** [comment]
Translations are handled on Transifex and can only be fixed there. :) https://www.transifex.com/nextcloud/nextcloud/maps/
