### ISSUE TITLE
Popups are out of place on contacts with default picture

### ISSUE THREAD

**Issue by szaimen** [nextcloud/maps#132]
When hovering with the mouse over one contact with default pictures, the popup that appears is out of place.
See the screenshot:
![image](https://user-images.githubusercontent.com/42591237/64356608-6d600780-d003-11e9-9f1e-d2caa15a287d.png)
(The picture-bubble is hidden behind the popup.)
I am using a chromium based Browser on Windows if that is important.
Thank you!

**Comment by jancborchardt** [comment]
@Cancan68 this seems like a different problem. Could you open a separate issue for that? :) Thanks!

**Comment by tacruc** [comment]
![image](https://user-images.githubusercontent.com/402891/64924169-d56fd400-d7e1-11e9-87da-0d9a7db47957.png)
Is this how it is supposed to be?

**Comment by eneiluj** [comment]
Who are you asking to?

My answer is: yes :wink: The tooltip is now placed at the center of the marker.

**Comment by tacruc** [comment]
I would have assumed that the triangles should point to the same place.

**Comment by eneiluj** [comment]
Well if we do like that marker becomes invisible when tooltip is visible. I don't like that but let's talk about it.

**Comment by tacruc** [comment]
@eneiluj I see that why I ask if this placement was on purpose. 
@jancborchardt  what do you think about the placement?

**Comment by jancborchardt** [comment]
I’d agree with @tacruc, the triangles should point to the same place. Basically it should look as if the marker just "grew". Makes sense? :)

**Comment by anaqreon** [comment]
@jancborchardt I attempted to address your concern with a simple commit to pull request #154. I made some mistakes with the git branches so hopefully I didn't mess things up too badly.

**Comment by jancborchardt** [comment]
The original issue was fixed through https://github.com/nextcloud/maps/pull/154, the design followup is in https://github.com/nextcloud/maps/pull/195 :)
