### ISSUE TITLE
When I clicked on one contact and see further information, the hovering popup shouldn't get triggered.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/maps#133]
When I clicked on one contact and see further information, the hovering popup shouldn't get triggered in the background. Seems out of place here.
See the screenshot:
![image](https://user-images.githubusercontent.com/42591237/64356338-fe82ae80-d002-11e9-8f03-5a6b3c63b203.png)
I am Using a chromium-base browser on Windows if that is important.
Thank you!

**Comment by tacruc** [comment]
I think we should some how merge this two popups, 

- hover open it
- clicking makes it permanent

**Comment by jancborchardt** [comment]
This was fixed in the meantime. :)
