### ISSUE TITLE
Please make the app compatible with NC30

### ISSUE THREAD

**Issue by elpraga** [nextcloud/maps#1333]
It would be great to see it working on the newest NC version!

**Comment by Ma27** [comment]
Because I was curious, I manually changed the max-version of `info.xml` to 30 and it mostly seems to work for me.

Is there some kind of checklist or testsuite to see what's potentially breaking to fix this up? Would be open to help out here.

cc @come-nc @susnux @tacruc

**Comment by come-nc** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html is the official list for changes in 30 to take into account for applications.

**Comment by Ma27** [comment]
#1336 works for me so far. Best to review commit-by-commit.

**Comment by ant0nwax** [comment]
+1 upgrading to NC version 30 only if maps will be listed as compatible.

**Comment by Ma27** [comment]
More testers of the changes are always welcome I'd say 🤷

**Comment by gwolf** [comment]
Maximilian Bosch dijo [Fri, Oct 18, 2024 at 08:31:56AM -0700]:
> More testers of the changes are always welcome I'd say 🤷 

I completely understand that, but I'm not in a position to be a tester: I'm not
really familiar with PHP, and have currently only one working NC instance, which
is in production for my users.

**Comment by johansmitsnl** [comment]
@tacruc when can we expect a release?

**Comment by tacruc** [comment]
There is a nightly, once tested it can be released.

**Comment by tacruc** [comment]
Can be installed via OCC or Downloaded here https://github.com/nextcloud/maps/releases/download/v1.5.0-1-nightly/maps-1.5.0-1-nightly.tar.gz

**Comment by langfingaz** [comment]
> Can be installed via OCC or Downloaded here https://github.com/nextcloud/maps/releases/download/v1.5.0-1-nightly/maps-1.5.0-1-nightly.tar.gz

Many thanks! I updated to that version and it works fine on my NC instance at v30.0.2.
