### ISSUE TITLE
Photos: directories with .nomedia files are scanned

### ISSUE THREAD

**Issue by paullbn** [nextcloud/maps#143]
Hello,

Pictures located in directories containing a `.nomedia` files are scanned and displayed in Maps.

**Comment by jancborchardt** [comment]
Good point, they should be omitted, as probably all hidden folders and files.

**Comment by FelixBuehler** [comment]
Maybe even add an option to only scan specific folders. I have a lot of folders with no relevant data or photos in there but are quite big.
So a parameter like `occ maps:scan-photos userX /Photos` would be a good idea.

**Comment by jancborchardt** [comment]
@FelixBuehler we need to make sure that things we add work for regular people too. And it’s always best to do that automatically, without specific settings. :) A simpler fix could just be which folders are prioritized, e.g. well-known locations like a "Pictures" or "Photos" folder can be done first.

**Comment by FelixBuehler** [comment]
But why isn't a folder-name parameter working for all users? I mean the parameter could be optional. And if I set it, just my folder 'Photos' or 'Pics' or 'Cats' will be scanned.

**Comment by jancborchardt** [comment]
Most people do not change defaults or fiddle with settings. Hence we first have to focus on making sure it’s performant in the default case.

**Comment by cly0514** [comment]
found that external storage are also scanned, that a lot of cache picture from telegram or other application that shoot by others displayed in my nextcloud maps. excluding external storage or excluding some folders will be useful

**Comment by GAS85** [comment]
Any update here? Quite needed feature, otherwise I can see only tracks from backup of PhoneTrack App, but not actual one...

**Comment by schklom** [comment]
If anyone knows some PHP, I see where a fix can be made, but I haven't done any PHP in a long time, so I hope someone else can help :)

https://github.com/nextcloud/maps/blob/master/lib/Service/PhotofilesService.php#L320

The function is recursive and will look at the content of every folder to see if any file in the current folder is a photo.
The fix would be to skip the iteration if any file inside is `.nomedia` or `.noimage`.
A skip is already implemented below `// we don't explore external storages for which previews are disabled`.
So a similar skip can be written to skip the folder if it contains any of these 2 files.
Maybe via a for loop over the files?

Maybe this can help to list files in a folder: https://www.php.net/manual/en/function.scandir.php

**Comment by schklom** [comment]
I made a PR https://github.com/nextcloud/maps/pull/617, but didn't test it. Does anyone care to try building it to see if it works?

**Comment by Derkades** [comment]
> Note that the indentation in the PR isn't the same as the one in the file, I don't understand why.

This is because you used tabs while the rest of the code uses spaces. Your text editor likely displays tabs as 4 spaces while github uses 8.

**Comment by schklom** [comment]
> This is because you used tabs while the rest of the code uses spaces.

I didn't notice x) Thanks!
I will create a new PR and update the link in my last comment.

**Comment by b3nis** [comment]
It would be amazing to be able to choose which folders it scans. It's not usable for me now since it picks up so much stuff that I don't want.
Default could everything and then just have something under settings where I can pick which folders and re-scan.

With that this would be so freaking cool - I love the idea of the app!

**Comment by strugee** [comment]
@b3nis that sounds like a different feature request. Can you see if it's already on file and if not, open a new issue? You may want to link https://github.com/nextcloud/photos/issues/141 too since it would probably make sense for these to share the same setting.

**Comment by b3nis** [comment]
> @b3nis that sounds like a different feature request. Can you see if it's already on file and if not, open a new issue? You may want to link [nextcloud/photos#141](https://github.com/nextcloud/photos/issues/141) too since it would probably make sense for these to share the same setting.

Sorry, my bad. Please ignore my comment nextcloud/photos#141 is exactly what I was looking for, will cheer on that discussion :-)

**Comment by AykutCevik** [comment]
Any chance that this will be fixed?

**Comment by tacruc** [comment]
Maybe an approach along the same line as: https://github.com/nextcloud/photos/pull/944
is easy to implement.
