### ISSUE TITLE
For some contacts, the icon is not placed correctly in the street

### ISSUE THREAD

**Issue by Cancan68** [nextcloud/maps#147]
Hi

For some contacts, the street number does not seem to be taken into consideraiton
![image](https://user-images.githubusercontent.com/52736158/64864770-1fb55180-d638-11e9-87a5-f722d1ca4f60.png)
For others, it is jut perfect
![image](https://user-images.githubusercontent.com/52736158/64864797-29d75000-d638-11e9-8e9c-2f08c927b761.png)

Thanks to have a look into. Not big issue but would be nicer without this issue.

Laurent

**Comment by tacruc** [comment]
duplicate #136

**Comment by jancborchardt** [comment]
@tacruc if it’s a duplicate then it can be closed by the way. :)
