### ISSUE TITLE
No error message during install but: The library exif is not available

### ISSUE THREAD

**Issue by doitux** [nextcloud/maps#148]
I just installed the app from the nextcloud app store. There was no error message during the installation process. But the app doesnt appear in the main-bar of nextcloud. So i'm wondering what's the problem. When i looked into the admin area i realized the message "the library exif is not available". I think it would be better to check the dependencies before and display an error msg during installation process. 
Anyway what kind of exif library is missing? php-exif? Or any js-efix-lib? Maybe it would be possible to deploy the lib with the app?

**Comment by doitux** [comment]
During further tests i realized the msg during installation. Maybe it wasnt displayed in an older version.

**Comment by rEnr3n** [comment]
For those who don't know, you just need to enable exif on php.ini
`extension=exif`
