### ISSUE TITLE
From the logging of Nextcloud

### ISSUE THREAD

**Issue by copiis** [nextcloud/maps#149]
```
[no app in context] Error: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_maps_photos` where `file_id` = ?' with params [60950]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wolke.oc_maps_photos' doesn't exist at <<closure>>

 0. /home/users/zsemberi/www/wolke/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 184
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... t", Doctrine\DBAL\Dr ... ]})
 1. /home/users/zsemberi/www/wolke/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 158
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... t")
 2. /home/users/zsemberi/www/wolke/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 178
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "DELETE FROM `oc ... ?", {1: 60950})
 3. /home/users/zsemberi/www/wolke/lib/public/AppFramework/Db/Mapper.php line 256
    Doctrine\DBAL\Statement->execute()
 4. /home/users/zsemberi/www/wolke/apps/maps/lib/DB/GeophotoMapper.php line 54
    OCP\AppFramework\Db\Mapper->execute("DELETE FROM `*P ... ?", [60950])
 5. /home/users/zsemberi/www/wolke/apps/maps/lib/Service/PhotofilesService.php line 150
    OCA\Maps\DB\GeophotoMapper->deleteByFileId(60950)
 6. /home/users/zsemberi/www/wolke/apps/maps/lib/Hooks/FileHooks.php line 63
    OCA\Maps\Service\PhotofilesService->deleteByFile("*** sensitive parameter replaced ***")
 7. <<closure>>
    OCA\Maps\Hooks\FileHooks->OCA\Maps\Hooks\{closure}("*** sensitive parameters replaced ***")
 8. /home/users/zsemberi/www/wolke/lib/private/Hooks/EmitterTrait.php line 99
    undefinedundefinedcall_user_func_array(Closure {}, ["*** sensitive parameter replaced ***"])
 9. /home/users/zsemberi/www/wolke/lib/private/Hooks/PublicEmitter.php line 36
    OC\Hooks\BasicEmitter->emit("\\OC\\Files", "preDelete", ["*** sensitive parameter replaced ***"])
10. /home/users/zsemberi/www/wolke/lib/private/Files/Node/Root.php line 136
    OC\Hooks\PublicEmitter->emit("\\OC\\Files", "preDelete", ["*** sensitive parameter replaced ***"])
11. /home/users/zsemberi/www/wolke/lib/private/Files/Node/HookConnector.php line 102
    OC\Files\Node\Root->emit("\\OC\\Files", "preDelete", ["*** sensitive parameter replaced ***"])
12. /home/users/zsemberi/www/wolke/lib/private/legacy/hook.php line 106
    OC\Files\Node\HookConnector->delete({run: true,path: ... "})
13. /home/users/zsemberi/www/wolke/lib/private/Files/View.php line 1273
    OC_Hook::emit("OC_Filesystem", "delete", {run: true,path: ... "})
14. /home/users/zsemberi/www/wolke/lib/private/Files/View.php line 1143
    OC\Files\View->runHooks(["delete"], "/DokScan/.dtras ... o")
15. /home/users/zsemberi/www/wolke/lib/private/Files/View.php line 716
    OC\Files\View->basicOperation("unlink", "/DokScan/.dtras ... o", ["delete"])
16. /home/users/zsemberi/www/wolke/apps/dav/lib/Connector/Sabre/File.php line 422
    OC\Files\View->unlink("/DokScan/.dtras ... o")
17. /home/users/zsemberi/www/wolke/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\File->delete()
18. /home/users/zsemberi/www/wolke/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
    Sabre\DAV\Tree->delete("files/Richard/D ... o")
19. <<closure>>
    Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
20. /home/users/zsemberi/www/wolke/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
21. /home/users/zsemberi/www/wolke/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
22. /home/users/zsemberi/www/wolke/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
23. /home/users/zsemberi/www/wolke/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
24. /home/users/zsemberi/www/wolke/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
25. /home/users/zsemberi/www/wolke/remote.php line 163
    undefinedundefinedrequire_once("/home/users/zse ... p")

DELETE /remote.php/dav/files/Richard/DokScan/.dtrash/info/Scan21-81b19d20-1f8a-497a-a74a-a213922e8fb1.dtrashinfo
from 89.204.155.59 by Richard at 2019-09-14T23:43:19+00:00
```

**Comment by copiis** [comment]
![2019-09-15 12 55 55](https://user-images.githubusercontent.com/12480023/64920581-cd9c3980-d7b9-11e9-8981-76a9eb8990e1.png)
I just have one table for maps

**Comment by eneiluj** [comment]
Possible duplicate of #109.
I'm almost sure this problem has been fixed in `fix-issue109` branch (pending PR #158) . I guess you're using MySQL/MariaDB for your NC installation, right?

Could you try to install from `fix-issue109` branch? 

So here's what you may do to test:

* disable maps app in the NC app settings
* delete `/var/www/.../nextcloud/apps/maps` folder
* clone maps repo:
```
cd /var/www/.../nextcloud/apps/
git clone https://github.com/nextcloud/maps -b fix-issue109
cd maps
make
```
* then enable maps app

**Comment by copiis** [comment]
> I guess you're using MySQL/MariaDB for your NC installation, right?

yes

Database tables are stil not created, i get this after `make`

`make[1]: Verzeichnis „/home/users/zsemberi/www/wolke/apps/maps“ wird betreten
install
install: Fehlender Dateioperand
„install --help“ liefert weitere Informationen.
Makefile:89: recipe for target 'npm' failed
make[1]: *** [npm] Error 1
make[1]: Verzeichnis „/home/users/zsemberi/www/wolke/apps/maps“ wird verlassen
Makefile:64: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by eneiluj** [comment]
I don't understand german...but I can read line 64 of the Makefile :grin:. You just don't have composer installed. To be sure, let's install npm too. On Debian based system:

```
apt install composer npm
```
Then make should run fine.

Nope, I strongly advise not to perform database actions manually :wink:.

**Comment by copiis** [comment]
Okay i instales composer as root and after that i run `make` as the www-user, here is the result

```
make[1]: Verzeichnis „/home/users/zsemberi/www/wolke/apps/maps“ wird betreten
/usr/bin/npm install
npm ERR! Linux 4.15.0-62-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/users/zsemberi/.npm
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/users/zsemberi/.npm'
npm ERR!  { Error: EACCES: permission denied, mkdir '/home/users/zsemberi/.npm'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/users/zsemberi/.npm',
npm ERR!   parent: 'maps' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/zsemberi/www/wolke/apps/maps/npm-debug.log
Makefile:89: recipe for target 'npm' failed
make[1]: *** [npm] Error 243
make[1]: Verzeichnis „/home/users/zsemberi/www/wolke/apps/maps“ wird verlassen
Makefile:64: recipe for target 'build' failed
make: *** [build] Error 2

```

**Comment by eneiluj** [comment]
You can run `make` as root without many side effects except having `/root/.npm` created. Then some files in maps directory will be owned by root. Not a problem for now. Later, when you'll want to delete maps directory to install it again from appstore, you will just have to do it as root and that's it. I understand if you don't want to run make as root though.

**Comment by copiis** [comment]
Okay run `make` as root an at the end this comes
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN opening_hours@3.5.0 requires a peer of i18next-client@^1.11.1 but none was installed.
npm WARN opening_hours@3.5.0 requires a peer of moment@^2.10.6 but none was installed.
npm WARN opening_hours@3.5.0 requires a peer of country-language@^0.1.7 but none was installed.
npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none was installed.
sed -i 's/L\.Browser\.touch/L.Browser.mobile/g' node_modules/leaflet.elevation/dist/Leaflet.Elevation-0.0.2.min.js

DB tables are not been created
`

**Comment by eneiluj** [comment]
I don't exactly know how migration system works, which steps it marked as done...

You may check migration status with something like:

```
cd /var/www/.../nextcloud
sudo -u www-user php ./occ migrations:status maps
``` 
You can manually execute migration steps starting from the first one that failed:
```
sudo -u www-data php ./occ migrations:execute maps 000008Date20190428142257
sudo -u www-data php ./occ migrations:execute maps 000009Date20190625000800
sudo -u www-data php ./occ migrations:execute maps 000012Date20190703155323
sudo -u www-data php ./occ migrations:execute maps 000012Date20190722184716
sudo -u www-data php ./occ migrations:execute maps 000013Date20190723185417
sudo -u www-data php ./occ migrations:execute maps 000014Date20190817184844
sudo -u www-data php ./occ migrations:execute maps 000102Date20190901152326
```
Thanks for your determination! We're gonna make it!

**Comment by copiis** [comment]
> sudo -u www-user php ./occ migrations:status maps
` >> App:                                                maps
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\Maps\Migration
    >> Migrations Directory:                               /home/users/zsemberi/www/wolke/apps/maps/lib/Migration
    >> Previous Version:                                   000014Date20190817184844
    >> Current Version:                                    000102Date20190901152326
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     000102Date20190901152326
    >> Executed Migrations:                                7
    >> Executed Unavailable Migrations:                    7
    >> Available Migrations:                               7
    >> New Migrations:                                     7
    >> Pending Migrations:                                 None
`
After the first migration thin i get `Can not go back to previous migration without debug enabled`
I set debug level 0 in the config.php bit nothing changed

**Comment by eneiluj** [comment]
It's a boolean: `'debug' => true,`

**Comment by copiis** [comment]
Yessssss, DB tables are created, somthing else to do?

**Comment by eneiluj** [comment]
Yay :tada:. Hmmm maybe the install scan jobs were not scheduled. You could run `occ maps:scan-photos` and `occ maps:scan-tracks` and you're good to go.

**Comment by eneiluj** [comment]
Oh I forgot to thank you for confirming `fix-issue109` works. Good to know for #158.

**Comment by copiis** [comment]
I have to thank you for this wonderful software.

Photo Scan is running, 70 GB will definitely last?

**Comment by eneiluj** [comment]
Hehe you might face RAM limit problem due to PEL (Php exif parsing library) memory leaks... Let's see :grin:. We're working on it in #126.

**Comment by copiis** [comment]
Is this a problem that there are still question marks in the tables of the database?

**Comment by eneiluj** [comment]
I don't know in which interface you see that. What is it supposed to mean?

Do you see any entry in `maps_photos` during the scan?

**Comment by copiis** [comment]
> I don't know in which interface you see that. What is it supposed to mean?

Trough Adminer in the msql database
![2019-09-16 00 00 23](https://user-images.githubusercontent.com/12480023/64928192-06b5c780-d815-11e9-869f-1187541f4017.png)


> Do you see any entry in `maps_photos` during the scan?

Yessssss!
![2019-09-15 23 58 54](https://user-images.githubusercontent.com/12480023/64928200-146b4d00-d815-11e9-9d83-614d368078c6.png)
