### ISSUE TITLE
Automated image/ track scan of user home directory not working as expected

### ISSUE THREAD

**Issue by marcuseric** [nextcloud/maps#159]
Hi there!

When I installed maps I got the same message as above stating that the media scan wasn't done yet. When refreshing the site again, this message doesn't popup again. I've got round about 35GB of photos stored in my folders. Every now and then some (approx. 5-20 pictures) get added to the map, but there is no significant progress. So far I got about 150 pictures of about 10k+. I tried `./occ maps:scan-photos` as mentioned above, but the prompt responds this:

> `occ $ maps:scan-photos`
> `Encryption is enabled. Aborted.`

My files are encrypted, yes. How can it be that some files could have been scanned, but most of them haven't? Encryption is enabled for the whole account/ instance. Isn't it possible that the files are scanned anyway if the scan is triggered by the corresponding user?

Thanks in advance for your help - any explanation is very appreciated :-)

**update 1 - 15.09.2019**: apparently those images that are being added to maps are the ones that are the latest ones synced from the NC iOS app. So _already existing images_ on the filesystem are not scanned. Can this be triggered tough the encryption is enabled?

**update 2 - 15.09.2019**: see also #128 - as that issue has been closed without a response to my comment I guess this problem is not related.

**Comment by tacruc** [comment]
> Hi there!
> 
> When I installed maps I got the same message as above stating that the media scan wasn't done yet. When refreshing the site again, this message doesn't popup again. I've got round about 35GB of photos stored in my folders. Every now and then some (approx. 5-20 pictures) get added to the map, but there is no significant progress. So far I got about 150 pictures of about 10k+. I tried `./occ maps:scan-photos` as mentioned above, but the prompt responds this:
> 
> > `occ $ maps:scan-photos`
> > `Encryption is enabled. Aborted.`
> 
> My files are encrypted, yes. How can it be that some files could have been scanned, but most of them haven't? Encryption is enabled for the whole account/ instance. Isn't it possible that the files are scanned anyway if the scan is triggered by the corresponding user?
> 
> Thanks in advance for your help - any explanation is very appreciated :-)
> 
> **update 1 - 15.09.2019**: apparently those images that are being added to maps are the ones that are the latest ones synced from the NC iOS app. So _already existing images_ on the filesystem are not scanned. Can this be triggered tough the encryption is enabled?

I think this update explains what is happening. The stored files are encrypted, such that they can not be scanned. But it looks like, that new created pictures are scanned by the file hook before they are encrypted, such that new pictures are shown on the map. So I guess that we can close this issue as the behaivior here is as expected, or?

> 
> **update 2 - 15.09.2019**: see also #128 - as that issue has been closed without a response to my comment I guess this problem is not related.

:+1:

**Comment by Zocker1999NET** [comment]
is there no way to let this app work while having the files encrypted?

If not, this should be explained in the Readme / description of the plugin to avoid users complaining about the app not working as expected.
