### ISSUE TITLE
[Feature Request] - Add support for Geo Information in contacts

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/maps#16]
There are contacts I wish to use with a Map view. It could be a good Idea to add a Geo Field to contacts and allow then to get the location by address and/or moving the geo-needle and insert the coordinate to contacts

You may need to work together with https://github.com/nextcloud/contacts

http://geouri.org/2010/06/10/geo-and-vcards/
(old wrong placed Request -> https://github.com/nextcloud/server/issues/3083 )

**Comment by tacruc** [comment]
The maps part of it is working in master.

**Comment by eneiluj** [comment]
Yep, contacts with GEO information are displayed on the map. Contacts without GEO information but with an address (ADR) are displayed (using nominatim to find coordinates from the address). Other contacts can be placed by user actions on the map. There is still one small missing part: resetting the GEO information of a contact. It's almost done, feature is available in the UI but I just didn't find a way to delete a tag in a vcard. Related code is at the end of `lib/Controller/ContactsController.php`.

**Comment by Mannshoch** [comment]
May OffTopic, but If I use Nominatim to get Addresses into Geo Information. Do all Address-book data get sent to nominatim or is this a local program?

**Comment by eneiluj** [comment]
There's a request to nominatim for all user's contacts with an address defined.

Are you concerned about privacy? I don't think there's a big privacy problem here. I mean, requests are made by NC server for all users.

**Comment by Mannshoch** [comment]
In my opinian there is a need that Nextcloud ask for sharing this data with an external server.

**Comment by eneiluj** [comment]
Well, when using NC Maps, user's browser is making requests to external services anyway to get map tiles (osm, esri etc...) and potentially with external routing engines.

Do you mean that each type of request to external services should be accepted by the user?

Or maybe you mean contact addresses are very private. Well when such a request is made, nominatim does not know if it's a contact address or if it's just a search query, it does not even know which user is associated with the request, it just sees an address and returns related information.

**Comment by Mannshoch** [comment]
Thats a good Question, the whole Privacy thing is not that Easy.

For a private project I downloaded all needed map Tiles from OSM and the leaflet scripts and stored them on server. I have a little bash script which download the actual leaflet and OSM tiles which I use, from time to time. 

I created an Issue in https://github.com/nextcloud/server/issues/16046

**Comment by eneiluj** [comment]
At some point, we will add support for custom tile servers (like in GpxPod and PhoneTrack) in Maps. That's a step further for privacy.

If you host your own routing engine, you'll be able to use it in Maps. This is coming very soon (#60).

We could think about a way to let users use a self hosted nominatim for geocoding requests. I just checked and nominatim can be self-hosted!

What else can we think of?

**Comment by Mannshoch** [comment]
At moment I have no further Idea. Thanks.
