### ISSUE TITLE
Photo Scan stops after 10.508 Photos

### ISSUE THREAD

**Issue by copiis** [nextcloud/maps#161]
`An unhandled exception has been thrown:
Error: Call to a member function getValue() on null in  /apps/maps/lib/Service/PhotofilesService.php:486
Stack trace:
#0  /apps/maps/lib/Service/PhotofilesService.php(391): OCA\Maps\Service\PhotofilesService->getExifPelBackup(Object(OC\Files\Node\File))
#1  /apps/maps/lib/Service/PhotofilesService.php(270): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))
#2  /apps/maps/lib/Service/PhotofilesService.php(65): OCA\Maps\Service\PhotofilesService->addPhoto(Object(OC\Files\Node\File), 'Richard')
#3  /apps/maps/lib/Command/RescanPhotos.php(80): OCA\Maps\Service\PhotofilesService->rescan('Richard')
#4  /apps/maps/lib/Command/RescanPhotos.php(66): OCA\Maps\Command\RescanPhotos->rescanUserPhotos('Richard')
#5  /lib/private/User/Manager.php(538): OCA\Maps\Command\RescanPhotos->OCA\Maps\Command\{closure}(Object(OC\User\User))
#6  /apps/maps/lib/Command/RescanPhotos.php(67): OC\User\Manager->callForSeenUsers(Object(Closure))
#7  /3rdparty/symfony/console/Command/Command.php(255): OCA\Maps\Command\RescanPhotos->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8  /3rdparty/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9  /3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Maps\Command\RescanPhotos), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10  /3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11  /lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12  /console.php(97): OC\Console\Application->run()
#13  /occ(11): require_once('/home/users/zse...')
`

**Comment by nobody1407** [comment]
@copiis I had the same issue after 18050 pictures. In my case it was always the same file. The only difference to the picture before and after was the text in "image description" (Exif-Tag). Maybe this information will help you.

**Comment by jancborchardt** [comment]
Could you test if this is fixed for you with the latest release 0.1.4? Thanks! :)

cc @nextcloud/maps

**Comment by gucu** [comment]
I have just tried to update the app and I am getting an error on the update. It says:
An error occured during the request. Unable to proceed.
Couldn't update app.
In the logs it says: 

Error | core | Exception: Could not extract app maps

Thanks
Rich

**Comment by gucu** [comment]
Has anybody else had problems installing? I would love to get it loaded so I can see if it is working. Thanks

**Comment by tacruc** [comment]
> Has anybody else had problems installing? I would love to get it loaded so I can see if it is working. Thanks

Everybody has, just take a look at the issue tracker (#240). I do not know a single instance where it worked. 
There exists a workaround:
There is a workarround https://github.com/nextcloud/maps/issues/240#issuecomment-576113700
We're working on a fix. Not shure how long it will take.

**Comment by gucu** [comment]
Thanks - I'll wait for the fix as I am on a hosted server.

**Comment by gucu** [comment]
App still has some issues. With the new version it started scanning and added 1 contact so it displays 13 (I have a lot more), with photos however it seem to be scanning fine but stopped scanning and took all photos that had been scanned and now shows none. It shows gps routes fine.
Error log says this:
[PHP] Error: Undefined property: OCA\Maps\BackgroundJob\UpdatePhotoByFileJob::$root at /home/gqatawtz/public_html/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php#43

GET /cron.php
from 92.13.173.86 at 2020-02-01T07:42:54+00:00

Thanks

**Comment by tacruc** [comment]
There are some improvments in Metadata extraction in v0.2.0
Could you check if v0.2.0-1-nightly solves the Issue.
It can be installed by
occ app:install maps --allow-unstable
or updated
occ app:update maps --allow-unstable
