### ISSUE TITLE
Integration with Open Place Reviews for reviews

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#163]
Just read about https://openplacereviews.org which is co-founded by people from OsmAnd and Maps.me

It still seems pretty early and unreleased. But having reviews for places just like Google Maps etc is a pretty strong factor for people using a map service. :)

**Comment by EloiR** [comment]
This project was discontinued unfortunately https://github.com/osmandapp/OsmAnd/issues/17451
