### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/maps#165]
No translation for route type selection in Transifex:

![obraz](https://user-images.githubusercontent.com/47037905/65144241-303e4100-da17-11e9-9e7e-d464487d70d6.png)

App:
Nextcloud 17.0.0 RC 1
Maps 0.1.2

**Comment by Valdnet** [comment]
@jancborchardt  No translation:
![obraz](https://user-images.githubusercontent.com/47037905/65224561-b0ba7b80-dac3-11e9-887e-a9cb7ef901d8.png)

**Comment by jancborchardt** [comment]
@tacruc @eneiluj are these wrapped to be translatable?

Because if they are @Valdnet it might just be that the translations for e.g. Polish are missing from the translations. You can help complete them at https://www.transifex.com/nextcloud/nextcloud/maps/

**Comment by Valdnet** [comment]
@jancborchardt I am a reviewer in Transifex 😉. There is simply no descriptions to translate.

**Comment by gary-kim** [comment]
Addressed in #191
