### ISSUE TITLE
OSRM demonstration server

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/maps#166]
- When setting the server address "OSRM server URL (foot profile)", the OSRM demonstration server is automatically displayed in the route calculation window.

![obraz](https://user-images.githubusercontent.com/47037905/65146599-8497ef80-da1c-11e9-97b6-d23de52451f0.png)

![obraz](https://user-images.githubusercontent.com/47037905/65146664-a2fdeb00-da1c-11e9-8998-418854c92db0.png)

- When all OSRM server addresses are set, the OSRM demo server setting does not affect the display of the OSRM demo server in the route calculation window. **It is always displayed**.

![obraz](https://user-images.githubusercontent.com/47037905/65146820-0556eb80-da1d-11e9-9383-e00e5b008485.png)

![obraz](https://user-images.githubusercontent.com/47037905/65146863-1ef83300-da1d-11e9-9427-c93ac8f9dfd4.png)

App:
Nextcloud 17.0.0 RC 1
Maps 0.1.2

**Comment by jancborchardt** [comment]
I’d say the OSRM demo server should only be possible to enable when you have no other routing engines set. As soon as anything else is set, we don’t need to strain their demo infrastructure anymore.

At the very least, not sort it first in the list. :)

**Comment by Valdnet** [comment]
@jancborchardt Therefore, in my opinion, this does not work properly :wink:.

**Comment by gary-kim** [comment]
Addressed in #190
