### ISSUE TITLE
OCC maps:scan-photos [OCP\Files\StorageInvalidException]

### ISSUE THREAD

**Issue by nicogodet** [nextcloud/maps#171]
Hi everyone,

I recently installed maps and I would like to have all my previous photos displayed on maps.
New photos added after maps was installed are displayed but older ones are not displayed.

When i open maps, i have this popup :  "Media scan was not done yet. Wait a few minutes/hours and reload this page to see your photos/tracks." 
Maps is installed for a month now....

If i manually try to scan photos with OCC, it raise an error :
\# su - www-data -s /bin/bash -c "php /var/www/nextcloud/occ maps:scan-photos seed"
======== User seed ========

In Storage.php line 220:

  [OCP\Files\StorageInvalidException]

maps:scan-photos [<user_id>]

**Comment by tacruc** [comment]
What Kind of storage are you useing?

**Comment by nicogodet** [comment]
Well, it seems that federated shares cause the issue.

I deleted them from oc_strorages and now maps:scan-photos works

**Comment by jancborchardt** [comment]
Right, then let’s close this, we can always open a new issue if the problem arises again, in which case we need more info like system and logs. :)
