### ISSUE TITLE
[Enhancement] ability to add our own "folders" or "sub-folders"

### ISSUE THREAD

**Issue by doc75** [nextcloud/maps#176]
It would be very nice for each user to be able to add his/her own "folder" on top of the existing ones (wIth folders and sub-folders).
Indeed, currently with a big number of favorites the list could be quite long and some organization might be nice. 
Another solution would be to integrate maps in the search functionality (perhaps more difficult).

Thanks for this great app.

**Comment by tacruc** [comment]
I don't get it? 
Cloud you provide a mookup?

**Comment by doc75** [comment]
Here is the current interface (with only 3 favorites): ![image](https://user-images.githubusercontent.com/926263/66077673-b94d9000-e560-11e9-8652-89182039d0c5.png)

Here is what I was trying to describe (badly ;-) ) with ability to group favorite with folder:
![image](https://user-images.githubusercontent.com/926263/66078203-db93dd80-e561-11e9-8699-9ceb1eb8b8eb.png)

Adding ability to add custom icons to favorite would also be great ;-)

**Comment by jancborchardt** [comment]
Just for reference @nextcloud/maps I will look into this, also because we need to keep this reasonably simple, and fitting the standard.

A related issue is that currently there’s no way to see your favorites in list view, which people expect.

**Comment by jancborchardt** [comment]
Thinking about this further and looking at other solutions (e.g. Google Maps, Maps.me) it would be unnecessarily complicated to have a subfolder structure.

The Favorites lists themselves are "folders" for the favorites already. For example you would use the default "Personal" favorites group for "Home" and "Parent’s home" etc.

Yes we should have a way of displaying the favorites inside of a group, but this is not something for a sub-sub-folder structure. :)

**Comment by doc75** [comment]
@jancborchardt fair enough. After some time of usage, it is not as cumbersome as I thought initially.
Thanks for the time taken to answer my request.
