### ISSUE TITLE
Missing Addresses

### ISSUE THREAD

**Issue by car-gli** [nextcloud/maps#185]
Hi, I setup Maps some days ago, and first I find it a good work actually, but I have one problem with my addresses. Not all addresses show up. I looked on he database at table oc_maps_address_geo and found that at the missing addresses no latitide and longitude field is filled. See axample:
` select * from oc_maps_address_geo where adr like '%Fersch%';
+----+------------------------------------------+------------------------------------------------------------------+----------------------------------------------------------------+------------+----------+-----------+
| id | object_uri                               | adr                                                              | adr_norm                                                       | lat        | lng      | looked_up |
+----+------------------------------------------+------------------------------------------------------------------+----------------------------------------------------------------+------------+----------+-----------+
| 35 | 27a04f2a-30d0-4510-894d-0deca09e73a5.vcf | ;;zum Hierbesch 8;Ferschweiler;Rheinland-Pfalz;55668;Deutschland | ;;zumhierbesch8;ferschweiler;rheinland-pfalz;55668;deutschland |       NULL |     NULL |         1 |
| 44 | 99f811e3-e420-42d1-9fce-dd2654d2c27e.vcf | ;;Hochstraße 40;Ferschweiler;Rheinland-Pfalz;55668;Deutschland   | ;;hochstraße40;ferschweiler;rheinland-pfalz;55668;deutschland  | 49.8627959 | 6.403477 |         1 |
| 87 | c4d868ce-0f47-43d7-bcac-3006b29a1697.vcf | ;;Hochstrasse 40;Ferschweiler;Rheinalnd-Pfalz;55668;Deutschland  | ;;hochstrasse40;ferschweiler;rheinalnd-pfalz;55668;deutschland |       NULL |     NULL |         1 |
+----+------------------------------------------+------------------------------------------------------------------+----------------------------------------------------------------+------------+----------+-----------+
`
As you can see, even for the same address are empty fields for one, I suppose there is a process who does this lookup, can I force this lookup again?
My version of nextcloud is 17.0.0 maps is 0.1.2 and the instance is running pn ubutntu 18.04 with apache 2.4.29 php 7.2 and mariadb 10.3.11

**Comment by tacruc** [comment]
It is not the same address once it ist Hochstrasse and once it is Hochstraße.
We use https://nominatim.openstreetmap.org/ as resolution of the addresse. one address is known the other is not.

**Comment by car-gli** [comment]
Ok, thanks, so that means if an address don't show up, there is something wrong in the matching, which I also found for the first record in the example, in my addressbook the name is "hierbesch" and at OSM it is "hierbersch". I don't know which one is correct, but now I know at least where to search for  ;)

**Comment by tacruc** [comment]
Yes
