### ISSUE TITLE
Add database support for those officially supported by Nextcloud

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/maps#19]
Hello,

it would be good to have database support for at least Postgresql as this is another option for use with Nextcloud.

**Comment by v1r0x** [comment]
Have you tried to install it in a nextcloud using postgresql? Are there any errors?
The support notice in the readme is not from me and I currently do not have a postgresql instance to test it. Would be nice if you could post your results.

**Comment by e-alfred** [comment]
Well, this was asked by @eneiluj in another issue. I didn't try it out yet as it is non-working anyway but would be glad to test it if it will be working again one day.

**Comment by jancborchardt** [comment]
@eneiluj @tacruc is Postgresql supported now? If not, what’s missing to make it happen and is any help needed? :)

**Comment by eneiluj** [comment]
It is supported. I recently wrote some tests and made them run with Gitlab CI (as I'm kind of stuck with Travis). Tests are running fin with SQLite, MySQL/MariaDB and PostreSQL.

**Comment by jancborchardt** [comment]
Awesome! :rocket:
