### ISSUE TITLE
occ maps:scan-photos scans all the photos every time

### ISSUE THREAD

**Issue by antonkarliner** [nextcloud/maps#198]
After uploading a big number of mobile photos to my Nextcloud instance, I've decided to run occ maps:scan-photos command because I wanted to see the pictures on my Map ASAP. All worked well, no problems, pictures appeared on the map.

After that I've uploaded another batch and run the occ maps:scan-photos again. Then I noticed something strange: instead of scanning newly added images only, it scanned all the photos on the instance again. To be sure, I've tried to replicate the behavior – and yes, it did it again.

First of all, that means that the process will be longer every time when new photos are added and the command is run, as it will scan all the pictures again and again. I thought about adding this command to cron, but I think it may potentially cause some problems, for example: in case of having **a lot** of pictures on the instance, it can take great amounts of time to finish. Also, it will take resources from the system. And last, but not least, I suppose, it can eventually lead to scan crashes as described in multiple issues here.

I think, the program must look for the new files and then scan the GPS data of the new files only, like the occ preview:pre-generate command in [Preview Generator App](https://apps.nextcloud.com/apps/previewgenerator) does.

Thanks for the great app! Hope the scan process will be updated soon.

**Comment by tacruc** [comment]
There is a incremental file scan which is triggerered on a file upload change etc...
So the maps scan command is just needed for the initial scan or if the library is fucked up for some reason to manually trigger a full scan.

**Comment by dassio** [comment]
i think this better added to the README ,for someone with an external storage, it cost me an fortune with the traffic charge.

>Media scans are performed with the regular system background job.

we can change this one to: Media scans are performed automatically with file uploaded
