### ISSUE TITLE
NC17: Geolocation doesn't work anymore due to Feature Policy

### ISSUE THREAD

**Issue by AlfredSK** [nextcloud/maps#204]
After upgrading to NC17 the geolocation feature doesn't work anymore. If I go to the Maps app I get a browser warning about the issue (geolocation is allowed for my NC URL in my browser settings). When I try to jump to my current location by clicking on the little icon in the down-right area of Maps the same warning appears...

`Geolocation error: Geolocation has been disabled in this document by Feature Policy..`

I checked the Feature Policy via Mozilla's Observatory service and I found that NC17 has set the geolocation feature to 'none'.

`Feature-Policy: autoplay 'self';camera 'self';fullscreen 'self';geolocation 'none';microphone 'self';payment 'none'`

That issue didn't exist with NC16. So, I guess it probably is a NC core issue. But I'm not sure.

**Comment by AlfredSK** [comment]
Changing the lines...

https://github.com/nextcloud/server/blob/773ce9e58f2f49fa07652070f87dbe90a7d4ae76/lib/public/AppFramework/Http/EmptyFeaturePolicy.php#L49-L50

to...

```
/** @var string[] of allowed domains that can use the geolocation of the device */
        protected $geolocationDomains = [
                '\'self\'',
        ];
```

...enables the geolocation feature. But this change will trigger a warning in the admin panel because of a non-matching file hash (altered file).

**Comment by jancborchardt** [comment]
@rullzer what do we do here – should @AlfredSK submit the patch as a pull request to server, or should the Maps app specifically ask for permission?

**Comment by rullzer** [comment]
Needs a fix in the maps app to enable this when the page is loaded. I can submit a PR.

**Comment by rullzer** [comment]
I'll do that this evening/tomorrow (if not then ping me again ;) ).
It will be a bit hacky as otherwise 16 support gets dropped.

**Comment by jancborchardt** [comment]
@rullzer ah cool, thanks a lot! cc @eneiluj @tacruc for info. :)

**Comment by tacruc** [comment]
> I'll do that this evening/tomorrow (if not then ping me again ;) ).
It will be a bit hacky as otherwise 16 support gets dropped.

@rullzer  ping

**Comment by rullzer** [comment]
See https://github.com/nextcloud/maps/pull/209
