### ISSUE TITLE
Testing locally

### ISSUE THREAD

**Issue by paulschwoerer** [nextcloud/maps#220]
Hey guys,
can someone point into the right direction for testing the maps app with phpunit locally (preferably through docker)? I cannot find extensive documentation on this and am a bit lost. My main question would be: 
Do I need a database running locally and how would I go about configuring a remote (or docker based) database?

Thanks in advance!

**Comment by jancborchardt** [comment]
Hi @paulschwoerer, so how I use it locally is simply with Apache running locally (on Ubuntu for example, or macOS): https://docs.nextcloud.com/server/17/developer_manual/general/devenv.html

I think @skjnldsv has some Docker setup instructions for local dev environments?

Or are you asking about something else?

**Comment by jancborchardt** [comment]
(Also cc @eneiluj @tacruc @aszlig @gary-kim as they might have pointers)

**Comment by paulschwoerer** [comment]
@jancborchardt Thanks for the hints, I'll reopen if there are other questions.
