### ISSUE TITLE
Error with PhoneTrack

### ISSUE THREAD

**Issue by shgysk8zer0** [nextcloud/maps#221]
Using "Nextcloud Maps log job" in [PhoneTrack 0.0.13](https://f-droid.org/en/packages/net.eneiluj.nextcloud.phonetrack/), I'm getting the following error:

```
An exception occurred while executing 'INSERT INTO `oc_maps_device_points` (`device_id`, `lat`, `lng`, `timestamp`, `altitude`, `battery`, `accuracy`) VALUES(?, ?, ?, ?, ?, ?, ?)' with params [3, ":lat", ":lng", "1575046826", "", "69.0", "20.0"]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect double value: '' for column `nextcloud`.`oc_maps_device_points`.`altitude` at row 1
```

Seems like there are two errors going on here:
- Floats with ".0" decimals for at least altitude?
- Inserting datetime via Unix timestamp as string?

Interestingly, this sometimes does work for a few `INSERT`s. Stops after maybe 5 of them and then errors forever until deleted and new job created.

**Comment by feilen** [comment]
Experiencing the same issue with PhoneTrack v0.0.16, Maps v0.1.2, Nextcloud v17.0.2.

**Comment by jaykijay** [comment]
I get some similar error on importing:

> 
>   An exception occurred while executing 'INSERT INTO `oc_maps_photos`(`file_id`,`lat`,`lng`,`user_id`,`date_taken`) VALUES  
>   (?,?,?,?,?)' with params [457321, 41.09998651, -115.09897624999999, "xxx", 1532537817]:                                   
>                                                                                                                             
>   SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date_taken' in 'field list'

**Comment by shgysk8zer0** [comment]
I'm no longer experiencing this issue after some updates. There has been no mention of anything relating to the issue in any changelog or release notes though.
