### ISSUE TITLE
RAW/ARW files are not indexed

### ISSUE THREAD

**Issue by pannal** [nextcloud/maps#224]
Most of the photos I have are in ARW/RAW format. I've got the https://apps.nextcloud.com/apps/camerarawpreviews extension installed.

It would be nice to have indexing metadata of ARW/RAW inside this app as well.

**Comment by tacruc** [comment]
I at the moment we use the phpexif library and libpel as backup to read exif data. As soon as those libraries support your special Raw format (I doubt that it will happen soon) will support this Raw format. 
But even using those libraries we get a bunch of errors on jpg an well defined board spreed standard image formats. If there is a nice library which solves our problems on jpg's and works for RAW I'm happy to change, but I think starting to develop this our self is out of scope.
