### ISSUE TITLE
Cannot enable app in Nextcloud 12

### ISSUE THREAD

**Issue by mschoenebeck** [nextcloud/maps#23]
This might be a noob question and probably is easy to solve but since I don't find any more information in the README nor on Google I post here:

I cloned the repo to nextcloud/apps and then tried to enable it in Nextcloud but the "enable" button is inactive. What is the matter here?

Nextcloud Version is 12
PHP Version is 7.0.24
Ubuntu Version is 14.04 (running on Odroid - ARM)
MySQL Version is 14.14

Help appreciated.

**Comment by tacruc** [comment]
Did you cloned the master branches? It's the default one if you don't
specify a different. This is an old broken version. You have to pull the
rework... branch. I don't know the exact name, but this branch is under
development and not stable.

mschoenebeck <notifications@github.com> schrieb am Mo., 16. Okt. 2017,
23:58:

**Comment by mschoenebeck** [comment]
Ahh... ok. Thank you. I cloned the rework branch and everything seems to be OK now. I've got another error when building the app now but I will open another thread for this. Thanks again.
