### ISSUE TITLE
[rework branch] No gulpfile found

### ISSUE THREAD

**Issue by mschoenebeck** [nextcloud/maps#24]
I built the app like described in the README file but I run into the following error. It says there is no gulpfile.

```
$ make
make npm
make[1]: Entering directory `/var/www/nextcloud/apps/maps'
npm run build

> maps@0.0.7 prebuild /var/www/nextcloud/apps/maps
> npm install && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update


> maps@0.0.7 build /var/www/nextcloud/apps/maps
> node node_modules/gulp-cli/bin/gulp.js

[18:59:46] No gulpfile found
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
make[1]: *** [npm] Error 1
make[1]: Leaving directory `/var/www/nextcloud/apps/maps'
make: *** [build] Error 2
```

**Comment by v1r0x** [comment]
I admit that it's confusing right now, since there is a Makefile, but the README says `npm install`. Maybe we should remove the Makefile and simply use npm.
cc @jancborchardt

**Comment by mschoenebeck** [comment]
Ahhh.. ok. Yes, I read the correct README file but was unsure about `make` because it said something about updating dependencies. So I thought it would be necessary to execute, too.
Anyways `npm install` works perfectly and after that I was able to enable maps app in Nextcloud.

Thanks for your fast help and for developing!
