### ISSUE TITLE
0.1.4: A non-numeric value encountered at /var/www/nextcloud/apps/maps/vendor/lsolesen/pel/src/PelIfd.php#447

### ISSUE THREAD

**Issue by myxor** [nextcloud/maps#245]
The following errors occurred while updating the app to 0.1.4:

> A non-numeric value encountered at /var/www/nextcloud/apps/maps/vendor/lsolesen/pel/src/PelIfd.php#447

Update fails with this error.

**Comment by myxor** [comment]
Seems to be solved for me.

**Comment by ajira86** [comment]
Even if I have no issue with the app, my logger is full of this error now

**Comment by ggeorgg** [comment]
Me to. I just added a lot of images to my nextcloud. Now me log is spammed with this message.

**Comment by ggeorgg** [comment]
Should we reopen this issue or create a new one?

**Comment by mayonezo** [comment]
My log is also spammed with this message. Please reopen!

**Comment by tacruc** [comment]
I will need the sample pictures, which create this error.

**Comment by ggeorgg** [comment]
I tried to find the pictures that are responsible for this error but for me it is harder than I though...
I uploaded some GB of images and simultaneously monitored the nextcloud log with "tail -f nexcloud.log". Even after the upload had finished, the nextcloud.log continued to log new lines of this error. I thought it happes directly when uploading, but apparently I was wrong. 
1. Can you tell me, when exactly this function is triggered? 
I found it in the file PelIfd.php in line 343 and in line 368. 
2. But when is this load(PelDataWindow $d, $offset) function used? 
3. Is it maybe a problem with the $tag variable?
4. Could we insert a "catch all error" block after line 447 and then log the image filename or the file id to nginx error log or nextcloud log? If yes, could you guide me do it?

Thanks!

**Comment by tacruc** [comment]
> I tried to find the pictures that are responsible for this error but for me it is harder than I though...
> I uploaded some GB of images and simultaneously monitored the nextcloud log with "tail -f nexcloud.log". Even after the upload had finished, the nextcloud.log continued to log new lines of this error. I thought it happes directly when uploading, but apparently I was wrong.

On uploading only a Background job is trigger. 
> 
>     1. Can you tell me, when exactly this function is triggered?
>        I found it in the file PelIfd.php in line 343 and in line 368.
Frist the problem is the the pellfd.php is not from us, but from the external libary PEL. 
So the relavent function we can adopt is https://github.com/nextcloud/maps/blob/abefbc34b84709e056763fe6c9b49ecdc17dfb4e/lib/Service/PhotofilesService.php#L433
Which is called in
https://github.com/nextcloud/maps/blob/abefbc34b84709e056763fe6c9b49ecdc17dfb4e/lib/Service/PhotofilesService.php#L378

> 
>     2. But when is this load(PelDataWindow $d, $offset) function used?
> 
>     3. Is it maybe a problem with the $tag variable?
> 
>     4. Could we insert a "catch all error" block after line 447 and then log the image filename or the file id to nginx error log or nextcloud log? If yes, could you guide me do it?
We allready have a catch all Pel Errors in 
https://github.com/nextcloud/maps/blob/abefbc34b84709e056763fe6c9b49ecdc17dfb4e/lib/Service/PhotofilesService.php#L379
Maybe we can expand to a more general class, but I would like to stay spezific and not to catch all. 
> 
> 
> Thanks!

Still I'm shure that it is caused by some kind of broken image, as PEL is only used, if the read_exif function from php is not working. So there are two independind exif libs which can not handle this kind of exif data.

**Comment by ggeorgg** [comment]
Would it be possible to get the file name or at least the file id of the image which is causing this error to be logged in the nextcloud log? It's hard for me to find the "broken" images in my image database of around 320GB.

**Comment by tacruc** [comment]
You might be able to add
` $this->logger->debug('PEL reading: ' . $path )`
Before line 433.
Therefore you will see all images which where opened by PEL in the log.

**Comment by tacruc** [comment]
You might need to addopt the logging level in your config php or call loger->error to increase the level of the message.

**Comment by ggeorgg** [comment]
Sorry again. If I add the logger line before 433 I am out of scope of the function. If I add it after it the app won't be loaded at all from the autoloader. Are you sure you meant line 433?

**Comment by tacruc** [comment]
Sorry
Before
https://github.com/nextcloud/maps/blob/abefbc34b84709e056763fe6c9b49ecdc17dfb4e/lib/Service/PhotofilesService.php#L378
or after
https://github.com/nextcloud/maps/blob/abefbc34b84709e056763fe6c9b49ecdc17dfb4e/lib/Service/PhotofilesService.php#L433

**Comment by tacruc** [comment]
Did it work?

**Comment by ggeorgg** [comment]
I made a stupid mistake by forgetting the semicolon after the logger line... I am currently trying again to get the "broken" images...
I have inserted the logger line now and the app is loaded. Can I now just use "sudo -u php /srv/www/nextcloud/occ maps:scan-photos myuser" to get the path of the images that use the other library logged in nextcloud log? 
Ok. Guess I can. I just got the error again in my nextcloud log. I will get back to you here when I found the correct image.

**Comment by ggeorgg** [comment]
Seems I can't trigger the error using "maps:scan-photos myuser"... 
Looks like it just was the nextcloud cron job executed every 5 minutes. I stopped the nextcloud cron timer now, killed the nextcloud cron php process and started it again manually. 
Now I get the errors again and I also have the path to the files logged. I expected to see the two lines (path to file, error message) alternating but I have many consecutive error lines. Maybe this comes from the fact, that they have the same timestamp, but I don't really know. 
Nevertheless, I think I found some files without exif tags. I sent you a mail to kontakt+github@arne.email. Hope this is correct?

**Comment by tacruc** [comment]
Thanks alot for those sample pictures. It seams that there is no geo information in them. Therefore I think we can just mute the warning.
Still the underlining problem should be fixed, would you mind to open an Issue at https://github.com/pel/pel/issues?q=is%3Aissue+is%3Aopen+non-numeric and provide them the sample pictures, too?

**Comment by ggeorgg** [comment]
Do you mean this commit? https://github.com/pel/pel/pull/154
