### ISSUE TITLE
Howto import GPX in rework Branch

### ISSUE THREAD

**Issue by jaykijay** [nextcloud/maps#25]
Hi,
I'm missing some Documentation :(
Is it possible to import a .gpx File when using the rework Branch, and if yes, how to do this?
Thanks for work, this App is really nice! :)

**Comment by jancborchardt** [comment]
@eneiluj @anaqreon is this superseded by https://github.com/nextcloud/maps/issues/73 ? :)

**Comment by eneiluj** [comment]
Yes. The question is about an out of date branch.
