### ISSUE TITLE
Nothing Shows Up On Map

### ISSUE THREAD

**Issue by djohannes** [nextcloud/maps#250]
Hey,

I scanned my photos with occ maps:scan-photos and I even placed photos manually on the map, but the map just keeps being empty. 
Also placed contacts don't show up, it's just an empty map. And after "occ maps:scan-photos" it's always adding the same pictures again.

In my logs I have a few errors after I use occ maps:scan-photos:

>Error: Call to a member function getUserFolder() on null/var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({ fileId: 27 ... "})/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 48:OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})/var/www/nextcloud/cron.php - line 125:OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

> Undefined property: OCA\Maps\BackgroundJob\UpdatePhotoByFileJob::$root at /var/www/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php#43

> Undefined property: OC\Files\Node\File::$getSize at /var/www/nextcloud/apps/maps/lib/Service/GeophotoService.php#98

**Comment by tacruc** [comment]
fixed in #241
