### ISSUE TITLE
Use a bundler

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/maps#252]
Currently the release tarball is exceptionally big because you're shipping `node_modules`. With the help of a bundler, third party scripts and other resources can be combined into a few files. Then the app tarball should shrink significantly again.

I would suggest looking into Webpack, as we have some experience with it in other apps and the Nextcloud server.

**Comment by gary-kim** [comment]
Added to my todo list. 

BTW, @ChristophWurst , you got me started with Webpack/Vue and now I use it in a lot of my websites/extensions. Thank you!
