### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/maps#257]
This word does not appear in the translation into Transifex:

- Nextcloud additional settings

https://github.com/nextcloud/maps/blob/10aa2edd4882f27dfcbeb7a4d3d387a725a766e0/js/script.js#L986

![obraz](https://user-images.githubusercontent.com/47037905/72812357-a40c8680-3c61-11ea-866b-7d41f0c78dbe.png)

App:
Maps 0.1.4

**Comment by jancborchardt** [comment]
Since the link has text already, it should not have a title. :) It can simply be removed.

Setting as a good first issue since it simply has to be removed from the part in `maps/js/script.js` as posted above.

**Comment by tacruc** [comment]
We have a reimplemented the entire front-end in v0.2.0.
If the Issue still exits in the new implementation, feel free to reopen this this.
