### ISSUE TITLE
GPX Tracks are not shown on Map

### ISSUE THREAD

**Issue by nemihome** [nextcloud/maps#259]
**Description**
There is no GPX track shown on Map but there are a lot of tracks in the Folders. All photos are shown on the map but no tracks.

I also tried to manually upload the gpx files which are in the cloud but nothing happens if I try to do that.

I'm using another port for nextcloud which is not stantard. Maybe this is the problem because the port is not shown in the logs?

**Expected Behavior:**
Selected or all gpx tracks should be shown on map but there is not one track shown.

**Environment**
Nextcloud 18
Maps 0.1.4
PHP 7.4.1

**Warnings:**
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
globals.js:66 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
3005globals.js:66 The escapeHTML library is deprecated! It will be removed in nextcloud 19.

**Errors in browser console:**
ne @ globals.js:66
r @ globals.js:82
preparePhotoMarkers @ photosController.js?v=20598fa2-0:229
addPhotosToMap @ photosController.js?v=20598fa2-0:200
(anonymous) @ photosController.js?v=20598fa2-0:357
c @ jquery.js:3099
fireWith @ jquery.js:3211
k @ jquery.js:8264
(anonymous) @ jquery.js:8605
nouislider.js?v=20598fa2-0:315 Uncaught Error: noUiSlider (14.1.1): 'range' value isn't numeric.
    at handleEntryPoint (nouislider.js?v=20598fa2-0:315)
    at new Spectrum (nouislider.js?v=20598fa2-0:396)
    at Object.testRange [as t] (nouislider.js?v=20598fa2-0:537)
    at nouislider.js?v=20598fa2-0:939
    at Array.forEach (<anonymous>)
    at testOptions (nouislider.js?v=20598fa2-0:929)
    at Object.updateOptions (nouislider.js?v=20598fa2-0:2400)
    at Object.updateSliderRange (script.js?v=20598fa2-0:1316)
    at Object.updateSliderRangeFromController (script.js?v=20598fa2-0:1381)
    at PhotosController.updateTimeFilterRange (photosController.js?v=20598fa2-0:291)

Logs (I have hundrets of this errors in the log):
Error	PHP	Undefined property: OC\Files\Node\File::$getSize at /var/www/html/<myserver>/nextcloud/apps/maps/lib/Service/GeophotoService.php#98

**Comment by nemihome** [comment]
Basically I realized that I can not add tracks via the option in favorites. In my case there is only one track shown in the my tracks area, although I have hundrets of it in the folders. The one which is in the section is not displayed.

**Comment by uwe-pt** [comment]
Same here. php 7.3, nc 17.0.3, maps 0.1.4.

**Comment by mills1975** [comment]
Hello,
Since I've updated to 0.1.5, my gpx-files won't show up on the map, altough the files are shown up
in the bar. But they're never finishing to load... the circle symbol is constantly spinning.

The following error is shown, when i click on the file to toggle visibility of the track:
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: 
Zeile Nr. 1, Spalte 199: 2
ReferenceError: assignment to undeclared variable cmttracksController.js:552:39
    processGpx tracksController.js:552
    jQuery 2
    processGpx tracksController.js:550
    loadTrack tracksController.js:493
    jQuery 4

The files are all ok, because they all we're shown on the map, before I did the update to 0.1.5

**Comment by saschamander** [comment]
+1
Same error for me.

**Comment by wronny** [comment]
found same issue here in NC18.0.1 after upgrade to maps 0.1.5 no GPX tracks shown on Map with following js error:
`tracksController.js:552 Uncaught ReferenceError: cmt is not defined
    at Element.<anonymous> (tracksController.js:552)
    at Function.each (jquery.js:374)
    at e.fn.init.each (jquery.js:139)
    at S.processGpx (tracksController.js:550)
    at Object.<anonymous> (tracksController.js:493)
    at c (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at k (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)`

**Comment by nqdrizzt** [comment]
I have the same issue: no gps track is showned in the maps plugin store in Maps folder as gpx file

nextcloud: 18.0.5
maps plugin:  0.1.6

**Comment by saschamander** [comment]
For me it was fixed after this update (0.1.6). Maybe your browser has some stuff cached. Can you try Ctrl+F5 or cleaning your browser cache.

If that doesn't work maybe try updating your Nextcloud. I think to 18.0.6 was released recently OR directly to 19.0.0

**Comment by nqdrizzt** [comment]
afaik nextcloud v18.0.5 is the latest and v19 is still in RC.

however, cleanig the cache or even trying a different browser in incognito mode still dos not show any tracks on in the maps plugin. 
I put the gpx in the 'Maps' folder, is this the correct location ?

**Comment by saschamander** [comment]
You should be able to put it in any folder on your Nextcloud. I even have them in different folders. 

Do they show up at the side menu, maybe they are hidden. To show them, simply click on them.
If they dont show up you can try to put them under the top folder and see if they show up at the side menu.

Do you use CRON as background task? Maybe your Nextcloud didnt discover them yet.

**Comment by nqdrizzt** [comment]
no, there shows up bo track at the side menu of the maps plugin. I also checked that nothing is hidden there. 
how is the cron job called responisble for that? Yes i configured to use the CRON service
