### ISSUE TITLE
Update to 0.1.4 kills sharing in Nextcloud

### ISSUE THREAD

**Issue by jacotec** [nextcloud/maps#260]
After updating Maps to 0.1.4 I realized that the folder sharing to another user did not work in Nextcloud. Error message:

> Invalid query, please check the Syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.

The logs pointed to Maps ("Call to undefined method OCA\\Maps\\Service\\PhotofilesService::safeAddByFolderIdUserId()"), and after deactivating Maps the sharing worked perfectly again.

`
{"reqId":"xUzK2foyC3KAGRpTEQjL","level":3,"time":"2020-01-21T22:38:02+01:00","remoteAddr":"10.0.0.1","user":"admin","app":"no app in context","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":{"Exception":"Exception","Message":"Call to undefined method OCA\\Maps\\Service\\PhotofilesService::safeAddByFolderIdUserId()","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","createShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"file":"\/var\/www\/nextcloud\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares"]},{"file":"\/var\/www\/nextcloud\/ocs\/v2.php","line":24,"args":["\/var\/www\/nextcloud\/ocs\/v1.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined method OCA\\Maps\\Service\\PhotofilesService::safeAddByFolderIdUserId()","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/hook.php","line":106,"function":"postShare","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":[{"itemType":"folder","itemSource":188040,"shareType":0,"uidOwner":"admin","permissions":31,"fileSource":188040,"expiration":null,"token":null,"id":"15","shareWith":"marco","itemTarget":"\/Test","fileTarget":"\/Test"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Share20\/LegacyHooks.php","line":174,"function":"emit","class":"OC_Hook","type":"::","args":["OCP\\Share","post_shared",{"itemType":"folder","itemSource":188040,"shareType":0,"uidOwner":"admin","permissions":31,"fileSource":188040,"expiration":null,"token":null,"id":"15","shareWith":"marco","itemTarget":"\/Test","fileTarget":"\/Test"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php","line":212,"function":"postShare","class":"OC\\Share20\\LegacyHooks","type":"->","args":[{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"},"OCP\\Share::postShare",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php","line":44,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[[{"__class__":"OC\\Share20\\LegacyHooks"},"postShare"],["OCA\\Files\\Collaboration\\Resources\\Listener","shareModification"]],"OCP\\Share::postShare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/EventDispatcher\/SymfonyAdapter.php","line":59,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Share::postShare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Share20\/Manager.php","line":700,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["OCP\\Share::postShare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Controller\/ShareAPIController.php","line":567,"function":"createShare","class":"OC\\Share20\\Manager","type":"->","args":[{"__class__":"OC\\Share20\\Share"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"createShare","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->","args":[{"__class__":"OC\\Files\\Node\\Folder"},31,0,"marco","false","",null,"",""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","createShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"file":"\/var\/www\/nextcloud\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares"]},{"file":"\/var\/www\/nextcloud\/ocs\/v2.php","line":24,"args":["\/var\/www\/nextcloud\/ocs\/v1.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/maps\/lib\/Hooks\/FileHooks.php","Line":130},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
`

**Comment by jacotec** [comment]
@tacruc Why was this closed mentioning #240 ? For me these are different issues and I already worked around #240 by manually extracting as mentioned in that thread.

I don't see the relation to my issue ...

**Comment by tacruc** [comment]
No it is closed because #262

**Comment by jacotec** [comment]
@tacruc Thank you, Arne!
Is it worth to wait for a fix release in short term, or do you recommend going back to 0.1.2?

**Comment by tacruc** [comment]
@jacotec #254 has a list of PR's where I'm waiting on reviews. No clue how long it will take.
