### ISSUE TITLE
Undefined index: previews at PhotofilesService.php

### ISSUE THREAD

**Issue by Skip75** [nextcloud/maps#261]
Hello

I'm getting repeatedly below error in logs :

```
{
  "reqId": "6OTDL8u44DLKRN0NWhxc",
  "level": 3,
  "time": "2020-01-22T00:12:15+01:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "Undefined index: previews at /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php#320",
  "userAgent": "--",
  "version": "18.0.0.10",
  "id": "5e278b687733f"
}
```

With NC18, latest version of Maps and Below PHP version :
```
PHP 7.4.1 (cli) (built: Dec 17 2019 16:35:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies
```

Any idea of the impact it's having ?

**Comment by koarlmichael** [comment]
I think sharing files to users is not working if the maps app is activated.

**Comment by tacruc** [comment]
Can you check if #261 solves the issue.

**Comment by koarlmichael** [comment]
> @koarlmichael Can you check if #261 solves the issue.

No, don't fix it
Logfile:
Exception: Call to undefined method OCA\Maps\Service\PhotofilesService::safeAddByFileIdUserId()

**Comment by tacruc** [comment]
Sorry I meant # #262.

**Comment by koarlmichael** [comment]
> Sorry I meant # #262.

I works :)

But logfile:

Trying to access array offset on value of type int at /var/www/nextcloud/lib/private/AppFramework/OCS/BaseResponse.php#129

Undefined offset: 0 at /var/www/nextcloud/apps/maps/lib/Service/TracksService.php#82

Undefined offset: 0 at /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php#98
