### ISSUE TITLE
0.1.4 Trying to install: "App with id maps has invalid signature"

### ISSUE THREAD

**Issue by Sponkdamonk** [nextcloud/maps#264]
Any idea what could be going wrong?

Had 0.1.2 installed which worked. Trying to upgrade yielded a generic error message. I then disabled and removed the app and upon trying to reinstall, i get the above error message.

**Comment by tacruc** [comment]
related #240 and #237, I'm currently updating the tarbal. The Archive on github is allready replaced, but the signiture on the appstore is not yet updated.

**Comment by Sponkdamonk** [comment]
thanks for the update and sorry for raising a known issue...
