### ISSUE TITLE
Exception: App with id maps has invalid signature

### ISSUE THREAD

**Issue by eweinhold** [nextcloud/maps#268]
Running Nextcloud Fresh installed 17.0.2
can and could install other Apps like contacts, calender, noted, deck …

The only useful error i get is:
"Exception: App with id maps has invalid signature"

**Comment by Zocker1999NET** [comment]
I experience this problem on my production system. What did you, @eweinhold, to solve this problem?

**Comment by eweinhold** [comment]
i downloaded the relase manual and placed the "maps" folder in the apps folder on my server.
after that you can aktivate the app in the settings.

https://github.com/nextcloud/maps/releases

the auto-installer doesn´t work currently
