### ISSUE TITLE
Idea: Apply `node-prune` before creating releases

### ISSUE THREAD

**Issue by mattsches** [nextcloud/maps#273]
I've been looking into reducing the size of the release files (because of https://github.com/nextcloud/maps/issues/226#issuecomment-577619882) and found that the original size of the `node_modules` directory can be reduced from ~129 MB to about ~87 MB by employing [node-prune](https://github.com/tj/node-prune).

However, I haven't run any tests after applying node-prune, but I still wanted to leave this here as an idea. Feel free to close this issue if this is not applicable for any reasons.

**Comment by tacruc** [comment]
I thin #252 should be the first step. Can we merge the disscussion there?
