### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Byter3** [nextcloud/maps#284]
Hi I try to install the app, but after a little whle I get this error:

"An error occured during the request. Unable to proceed.
cURL error 28: Operation timed out after 30000 milliseconds with 11053643 out of 24306414 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))"

up to date univention(4.4-3) instance and up to date Nextcloud(17.0.2).

**Comment by tacruc** [comment]
Can you increase your PHP execution time. It is just the download which times out.

**Comment by Byter3** [comment]
PHP
Version: 7.2.24
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 2 MB

I'm not really sure where are the correct settings, because, eventho upload max size reads here 2 megs I can upload much bigger files.
Do you happened to know where I can change these settings in an univention appliance?

**Comment by tacruc** [comment]
PHP.ini 
You should check how long the 25mb download takes.
