### ISSUE TITLE
PHP "UpdatePhotoByFileJob.php" and cron "Call to a member function getUserFolder() on null" errors

### ISSUE THREAD

**Issue by kiv57** [nextcloud/maps#287]
Hello,

Since my NC upgrade from 17.0.2 to 17.0.3, the 2 following errors appear repeatedly in log at the same time : 

```[PHP] Error: Undefined property: OCA\Maps\BackgroundJob\UpdatePhotoByFileJob::$root at /NC_path/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php#43```

at the same time :

```[cron] Error: Error: Call to a member function getUserFolder() on null at <<closure>>

0. /NC_path/lib/public/BackgroundJob/Job.php line 77
   OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({fileId: 671437,userId: "user"})
1. /NC_path/lib/public/BackgroundJob/QueuedJob.php line 46
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
2. /NC_path/cron.php line 124
   OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-02-03T16:35:06+00:00```

Config :
Debian 10.2
PHP 7.3.14
MariaDB 10.4.11 (if I remember well!)

Feel free to ask for more info!

Kevin

**Comment by Taomyn** [comment]
Should have searched, it's been reported and a fix is in test: https://github.com/nextcloud/maps/issues/282

**Comment by kiv57** [comment]
Thanks for your answer.
I'm very sorry for the duplicate, I opened the issue in a hurry and didn't take the proper time to search, as I do usually!
So if I understand, we just have to wait for the next update.

**Comment by Taomyn** [comment]
Yes, we have to wait I'm afraid. Hopefully it won't be long.
