### ISSUE TITLE
re-enable contextmenu "place photo folder" that was removed in the past

### ISSUE THREAD

**Issue by wronny** [nextcloud/maps#290]
Hello, 
I'm like to use maps to add pictures. Unfortunately contextmenu "place photo" only allow to add single photo or several using ctrl+mouseclick. However this is not very comfortable to select many photos. While investigating on adding photos by folder I stumbled over "place photo folder" in script.js. Unfortunately this has been removed / commented in the past:

![grafik](https://user-images.githubusercontent.com/3709024/74073263-014a5b00-4a0a-11ea-981f-a5fcc340a0a3.png)

I tested using my nc18 maps to re-add this contextmenu item and surprisingly "place photo folder" was working without any further modification. 
Is there any reason that I might have missed that "place photo folder" should be kept disabled? Maybe it is just still disabled just because it has been forgotten to re-enable it again?
Maybe someone else likes to verify my observation?
Many thanks
Wronny

**Comment by wronny** [comment]
addendum: If I use "place photo folder" re-enabled in js/script.js it takes about a minute until new added photos are shown on map. Not sure why this is different to (single) "place photo" that does show the added photo immediately.

**Comment by jancborchardt** [comment]
@wronny would you like to open a pull request to add this back? And maybe you can look into the issue of the delay until photos are shown on the map? :)

**Comment by wronny** [comment]
fixed by https://github.com/nextcloud/maps/pull/316
Many thanks to @eneiluj
