### ISSUE TITLE
No Photos Showing

### ISSUE THREAD

**Issue by gucu** [nextcloud/maps#301]
Still not getting any photos showing. I run an OCC command and it said it had scanned 450+ photos but when I looked there were no photos showing. I get this error message:

[PHP] Error: Cannot modify header information - headers already sent by (output started at /home/gqatawtz/public_html/apps/maps/lib/Command/RescanPhotos.php:78) at /home/gqatawtz/public_html/lib/private/AppFramework/Http/Output.php#69

POST /index.php/apps/occweb/cmd
from 92.13.173.86 by rich at 2020-02-17T17:08:45+00:00

Thanks

Rich

**Comment by yaokai007** [comment]
No photos shown on map. I used the manually scan command, no help. Checking the mysql db found there is only a few(less then 10) rows in table "oc_maps_photos" while the total picture quantity is more than 10000.
Use the right click then 'place a picture' is able to put picture on map. However the placed location is not align with the exist GPS infor in picture's exif. And the placed picture will erased by the scan command.

**Comment by tacruc** [comment]
The photos scan command is just for the initial scan ther is no need to repeat is. The table is updated by a cron job. Is your cronjob executed in a regular basis.

**Comment by yaokai007** [comment]
Thanks for reply. Yes, i use the manual command for initial scan.
Previously i use default AJAX as backend job. After i change to cron, the photo is now able to show on map. Thanks for your advise.

**Comment by republicus** [comment]
This needs to be added to the documentation. Nowhere does this this App state or suggest changing the Background jobs setting to Cron. _It is a requirement_ to get photos on the map.

I had the same problems and did what the documentation says is required, as you did, by completing a manual scan. It took reading issues, creating an issue, and reading responses to issues before switching Background jobs from AJAX to Cron.

**Comment by tacruc** [comment]
It is mentioned in the documentation of nextcloud that Ajax Cron is not suggested for productive use.

**Comment by tacruc** [comment]
And in theory it works, you just have to reload the page often enough.
