### ISSUE TITLE
Missing changelog entries

### ISSUE THREAD

**Issue by eibex** [nextcloud/maps#304]
I have been trying to figure out what has been fixed since the previous version.

I'm currently running 0.1.2 and never updated as I read that 0.1.4 was breaking sharing. I cannot find a changelog for versions newer than 0.1.2 on the NC app store nor on GitHub and cannot decide if it is "safe" to update to 0.1.5.

I have been trying to make one myself but there have been almost 300 commits since 0.1.2.

**Comment by tacruc** [comment]
0.1.5 was supposed to be a bug fixing release, as it  turns out #280 was not fixed.
