### ISSUE TITLE
v0.1.5 does not show favorites anymore

### ISSUE THREAD

**Issue by doc75** [nextcloud/maps#305]
Environment: docker official image (fpm-alpine)
Nextcloud version: 16.0.7 & 16.0.8

I was on maps v0.1.2 and tried to upgrade to maps v0.1.5.
After doing so I cannot see anymore my favorites.

To try to figure out which version is breaking things, I did the following:
1. deactivate maps from Nextcloud UI
2. suppress maps from Nextcloud UI
3. go in custom_apps directory
4. download version 0.1.2
5. extract version
6. change ownership: `chown -R www-data:www-data maps`
-> Favorites can be seen as before.

I did the same 6 steps for version 0.1.3
-> Favorites can be seen as before.

I did the same 6 steps for version 0.1.4
-> Favorites can be seen as before.

I did the same 6 steps for version 0.1.5
-> Favorites **cannot** be seen as before.

Contacts in all version can still be seen.

I cannot find anything in the log that seems related to this issue.

Any idea on what I can do to try to get more information ?

**Comment by eneiluj** [comment]
Thanks for the bug report. I think it's a side effect of merging frontend code with webpack. It's fine now with #306. If you feel like trying, it's available in master branch now.

**Comment by doc75** [comment]
I Here is what I tried, but still having the same issue:
```sh
apk add nodejs npm make
wget https://github.com/nextcloud/maps/archive/master.zip
unzip  master.zip
mv maps-master/ maps
cd maps/
make
cd ..
chown -R www-data:www-data maps/
```
Then I activate the maps application in Nextcloud.
I still have the same issue.

I can see the modification you made through #306, but in the Web console of firefox I can see the same error: `ReferenceError: assignment to undeclared variable cat`

Did I miss something to test your modification properly ? Sorry but it is the first time I am testing a master version of a Nextcloud app.

**Comment by doc75** [comment]
@eneiluj could we reopen it while fix is not validated ?

**Comment by eneiluj** [comment]
Yes we can.

Are you sure it's the same error. I mean is it still on the same line of same file?

**Comment by eneiluj** [comment]
Let's close this issue if we find out it's exactly the same as #307. Not sure yet.

**Comment by doc75** [comment]
@eneiluj, thanks for the advice, I cleared the cache (Ctrl+F5 does not seem to do anything on firefox), then it leads to another error.

As it is mentionned in script.js which is having very big line, the debug is not easy (sorry for the silly question, but is there a way to work on the `src` version to debug easily ?).

#308 has been pushed to fix the remaining issue.

**Comment by doc75** [comment]
@eneiluj let me know if I can help in checking this. I would just need some advice on how to debug with detailed JS files instead of script.js (which is pretty hard as it is one liner almost).

**Comment by eneiluj** [comment]
I was away from Map development for a long time and I don't know much about webpack but as far as I understand, you can edit files in `src` and then run `make` to produce the big unified JS source file `script.js`. Thanks to the `.map` file (most likely), the browser is able to know where the errors come from and points to the lines in the files we really edit before compiling them with webpack.

It seems you got that too, considering your PR :smile:.

I'll make a first round of tests, then make a PR, then it would be awesome if you could try to stimulate the UI to see where variable declarations are still missing. Hopefully there won't be anymore left :grin:.

**Comment by doc75** [comment]
@eneiluj, thanks for the information.

Mention me in the PR and I'll test it on my side.

**Comment by Bergum** [comment]
> I Here is what I tried, but still having the same issue:
> 
> ```shell
> apk add nodejs npm make
> wget https://github.com/nextcloud/maps/archive/master.zip
> unzip  master.zip
> mv maps-master/ maps
> cd maps/
> make
> cd ..
> chown -R www-data:www-data maps/
> ```
> 

Is this how I download the latest beta and install it?
@doc75 @eneiluj

**Comment by doc75** [comment]
> Is this how I download the latest beta and install it?

@Bergum, yes, but before you need to suppress the map application from the GUI, and just before:
```bash
apk add nodejs npm make
```
just do:
```bash
cd custom_apps/
```
to be in the correct directory.

Do not forget to clean your browser cache before the test to be sure to download the latest version just compiled.
