### ISSUE TITLE
Time Range Filter in the lower part of the Map

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#31]
cloud we use something like:
https://codepen.io/caseymhunt/pen/kertA

To filter all elements shown on the map (Tracks, Photos) to a specific time range?

What do you think?

**Comment by eneiluj** [comment]
Yep, seems good to me. It would allow to filter all kind of elements (favorites, photos, tracks, device positions...) with one simple mouse action. There are several leaflet plugins flawlessly providing such slider (https://leafletjs.com/plugins.html#time--elevation).

I'll probably work on that after getting a functional favorite management. Unless you want to do it :smile:.

**Comment by eneiluj** [comment]
After a quick look to listed "slider" plugins, the only one able to set a time interval is http://dwilhelm89.github.io/LeafletSlider/ . Too bad it uses JQueryUi.

**Comment by tacruc** [comment]
Is there a problem with JQueryUi?

**Comment by eneiluj** [comment]
Not really. It's a bit heavy and outdated.

**Comment by tacruc** [comment]
So should we use that, or look for something else?

**Comment by tacruc** [comment]
@eneiluj  There is a WIP for a time filter https://github.com/tacruc/maps/tree/dateTaken

**Comment by eneiluj** [comment]
Good to know. I'll try that soon. I'll also try not to touch to photos-related code while you're on it.

**Comment by tacruc** [comment]
Basic stuff is working now for Photos. I needed to use tow sliders at the moment, one selecting the start and one for the end

**Comment by tacruc** [comment]
Todo:

- Photos:
- [ ] Make it look nicer
- [ ] Extend api to only load photos in a spezific range or the last x
- [ ] On page load, load the last 50 pictures and load more if the time range changes.
- Favorits
- [ ] Add date created
- [ ] Add filter

**Comment by tacruc** [comment]
@eneiluj  cloud you check if you like the way I have implemented the time filter, and if it is suitable for the favorites?

**Comment by eneiluj** [comment]
Creation date has been added yesterday to my branch.

Nicely done! I like it, slider event catched in main script then telling controllers to filter. Sounds good to me.

I'll implement a filter method in favoriteController soon.

A few suggestions that are probably close to what you want to do:

* sliders step could be one day (60*60*24)
* sliders could appear on map's bottom left corner
* date could be displayed next to sliders
* dateTaken could be displayed in photo tooltips

You could merge (or pull --rebase) my changes in your branch while you're advancing. It would reduce the chances to get conflicts. Or I could merge your changes more often :smile:. Which one do you prefer?

**Comment by tacruc** [comment]
To the sliders:
I don't like the fact that there are two sliders right now, but I needed a simple solution I got working in short time. I think they should be integrated on one time axes and the selected area should be colored or something.

>     * sliders step could be one day (`60*60*24`)

For now I would just leave it continues. But I though to make the default Range one month and either add a small plus and a minus left and right to extend the range. Or extend the range dynamically, if the slider is pulled to the end.

>  * sliders could appear on map's bottom left corner

I thought about placing them in the bottom center, and just make them long. 25% left 50% slicer and 25% right.

> * date could be displayed next to sliders
> * dateTaken could be displayed in photo tooltips

That would be amazing.

> You could merge (or pull --rebase) my changes in your branch while you're advancing. It would reduce the chances to get conflicts. Or I could merge your changes more often smile. Which one do you prefer?

I don't care, which one would you prefer?  There is a third option you cloud give me write access than I cloud just push on our branch.

**Comment by eneiluj** [comment]
Yep bottom center sounds good.

I don't know about the variable slider range. It needs to stay stupid simple for the user. We could think about that later.

As we communicate and will take care of not making (too many) conflicts, I could merge your branch once a day (or two).

Hmmm I don't like the third option because it forces us to pull before pushing.

**Comment by eneiluj** [comment]
Or I could merge each time you tell me it's working to avoid having a broken state in my branch.

May i merge now? :wink:

**Comment by tacruc** [comment]
Now would be good, I think.

**Comment by tacruc** [comment]
What do you think of https://refreshless.com/nouislider/ as a slider?

**Comment by eneiluj** [comment]
Ok merged. You can pull from my branch if you want.

This slider seems nice and simple.

**Comment by eneiluj** [comment]
Just so you know: I've added photo name in tooltips.

**Comment by tacruc** [comment]
I noticed now there is 
`The escapeHTML library is deprecated! It will be removed in nextcloud 19.`

**Comment by eneiluj** [comment]
Ok, until then I have time to find an alternative to `escapeHTML` :wink:. Thanks

I've made a few changes in what you wrote:

* `updateSliderRange()` now takes both controllers in consideration, the largest range possible is set
* filter values are stored in filterController and then accessed by favoriteController (didn't change photoController's behaviour)
* a few code harmonization (simple quotes, if/else style...) and typos

When filtering favorites, I don't take into consideration if they are visible or not to keep it simple.

Maybe we should talk about how to manage filters before pushing it forward as it will affect all further development. I think it would be simpler to store filter values in filterController. I did it and adapted favoriteController but didn't change photosController, waiting for your opinion. This way all "data" controllers would just store their own min and max date and just tell the filterController to update when needed. When a slider moves, there could be just a call to a single method implemented in every "data" controller (like `updateFilterDisplay` in favoriteController). Hope it's clear. What do you think?

> On page load, load the last 50 pictures and load more if the time range changes

I don't know if it's necessary as it's not heavy at all to load all pictures thanks to marker cluster. Thumbnails are only loaded when a marker becomes visible or when showing a tooltip.

**Comment by eneiluj** [comment]
BTW, filters are now also working for favorites. Pushed to rework-eneiluj.

**Comment by tacruc** [comment]
I changed something too. We should check soon how to continue.

the new NoUiSlider is nice

**Comment by eneiluj** [comment]
:smile: I told it too late, you had probably started to make your changes without having pulled my branch. Too bad, we have merge problems.

I'll solve the merge issue and then apply my changes again. Your version acts like if there was just photos to filter.

**Comment by eneiluj** [comment]
Ok done, you should pull my branch before going on. I've changed timeFilterController to make it able to work with multiple controllers.

I've also simplified the way it was done. Callbacks are now simple lambdas. It took me a lot of effort to make those changes :smile: but it was worth it: The slider is really awesome! The dynamic range is perfect! Even if the initial range is very big, it's possible to target a very precise small range. Super nice.

From now on we should really try to discuss how we make things in order to limit the integration work. It would be great if you could make more comments to your code for me to understand it faster :wink:. It would also be great to have a chat before changing `script.js` to avoid working in parallel on this one.

What's next? I feel like Contacts are not that obvious to integrate. There are tough questions like when do we get coordinates from addresses...

Tracks could be quite simple to implement if we just make it possible to explore the storage to select a gpx file to display. This would create an entry in the sidebar for each loaded file.

I didn't think about Devices for the moment. To be continued.

**Comment by tacruc** [comment]
Thanks for merging and sorry i didn't see your changes.. I updated a small thing to make it visibile if the range is updated. Just tell me what you think.
