### ISSUE TITLE
ReferenceError: assignment to undeclared variable cat

### ISSUE THREAD

**Issue by cweiske** [nextcloud/maps#315]
With Maps version 0.1.5, Firefox 72.0.2 shows the following error in the console when opening the maps app in Nextcloud 16.0.4:

> ReferenceError: assignment to undeclared variable cat (favoritesController.js:730:8)

The menu item "Your Favorites" on the left keeps a loading icon forever.

**Comment by Bergum** [comment]
https://github.com/nextcloud/maps/pull/308
