### ISSUE TITLE
Discussion about favorites and photos

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/maps#32]
Hey @jancborchardt, @tacruc, @Sumaid,

I forked the `rework` branch and worked (in `rework-again` branch) on favorite API and UI. I also made a few modifications to photo management that was already quite ready. I feel favorite and photo management are functional and can be tested. I'm interested in your opinions.

This is also a memo :grin:.

### About the map itself:
* bottom right corner: tile layers management. 2 buttons for main providers and a classic Leaflet selector for extra providers.
* top right corner: locate control switch
* top left corner: search (untouched), scale control, zoom control
* map "state" is saved and restored (selected tile layer, locate control state, photos/favorites/categories layers state).

### About both photos and favorites
* favorites and photos markers are displayed with MarkerCluster
* click on a cluster: spiderfy instead of default action (zooming)
* photos, favorites and favorite categories layers can be toggled with the eye icon in the sidebar
* Leaflet.FeatureGroup.SubGroup is used for category layers to be able to easily add/remove them to the markerCluster layer.

### About photos : 
* mouseover on a photo: display a tooltip with a large preview
* click on a photo: open the Gallery app in a new tab

### About favorites:
* sidebar category list is updated dynamically when favorites are added/edited
* automatic category color depending on its name
* click on category name: zoom to layer bounds
* click on favorite marker: show popup in which you can edit/delete/move the favorite
* rename category: edit all markers of the category
* foldable category list (independent from layers toggling)

TODO:
* [x] import/export favorites from/in a gpx file (OsmAnd-like?)
* [x] see photos shared with me (scan is ok but photos are not added to DB when a file is shared)

The app can be installed in NC 15 or 16:

```
git clone https://github.com/nextcloud/maps -b rework-again /PATH/TO/NEXTCLOUD/apps/maps
cd /PATH/TO/NEXTCLOUD/apps/maps
make
```

It probably required to execute `occ maps:scan-photos` command after installing the app to make it include existing photos.

Feel free to include anyone in the discussion.

**Comment by tacruc** [comment]
Just played around with it and it worked nicely for me. Thinking about installing it on my private production server.

**Comment by e-alfred** [comment]
A route planning option would be great to have in this app. I already asked @eneiluj in the Phonetrack app bug tracker, but this app is much more appropriate for this purpose.

**Comment by eneiluj** [comment]
That's definitely going to appear in Maps :smile:.

**Comment by tacruc** [comment]
@eneiluj can we close this?

**Comment by jancborchardt** [comment]
I’d say let’s close it as basically all of it is implemented. :) Overview issues are only useful in the beginning – now at this stage we should open separate issues for problems we encounter.

**Comment by eneiluj** [comment]
All good :smile:.
