### ISSUE TITLE
Cannot load GPX tracks

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/maps#321]
I thought the maps app would be able to show GPX tracks on the map.

The tracks are recognized by the maps app, but when clicking on a track, I'll get errors in the developer console in the browser, that the XML is not well formed.
![grafik](https://user-images.githubusercontent.com/9428899/75607642-8bfa1380-5af9-11ea-8cf1-0834c406c637.png)

To be sure that this is not a problem on the client side (i.e. the device providing the GPX track), I also took a sample GPX from Wikipedia: https://en.wikipedia.org/wiki/GPS_Exchange_Format
Same result.

There are no entries regarding this problem in the Nextcloud log..

Nextcloud 18.0.1
Maps App 0.1.5

Am I doing something wrong, or is the maps app not supposed to show GPX tracks?

**Comment by tacruc** [comment]
Duplicate #306 ?

**Comment by DecaTec** [comment]
I don't think so, because #306 affects `favoritesController.js`, this problem here seems to be in `tracksController.js`.

**Comment by DecaTec** [comment]
I've tested cloning and building this app (just from master branch). Here it works, so the issue should have been fixed somewhere else.
Looking forward for v0.1.6...

**Comment by eneiluj** [comment]
@DecaTec Yep it has been fixed in #309.

A few PR to merge and v0.1.6 will most likely be there soon.
