### ISSUE TITLE
Geophotoservice Line:55 Element can be false.

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#35]
### Technical details
```

    Remote Address: ::1
    Request ID: HBdb0c8Y6SDOEIXVCcD7
    Type: Error
    Code: 0
    Message: Call to a member function getPath() on bool
    File: /srv/www/htdocs/server/apps/maps/lib/Service/GeophotoService.php
    Line: 55
```

```
Trace

#0 /srv/www/htdocs/server/apps/maps/lib/Controller/PhotosController.php(40): OCA\Maps\Service\GeophotoService->getAllFromDB('admin')
#1 /srv/www/htdocs/server/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\Maps\Controller\PhotosController->getPhotosFromDb()
#2 /srv/www/htdocs/server/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Maps\Controller\PhotosController), 'getPhotosFromDb')
#3 /srv/www/htdocs/server/lib/private/AppFramework/App.php(126): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Maps\Controller\PhotosController), 'getPhotosFromDb')
#4 /srv/www/htdocs/server/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Maps\\Contro...', 'getPhotosFromDb', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#5 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#6 /srv/www/htdocs/server/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#7 /srv/www/htdocs/server/lib/base.php(975): OC\Route\Router->match('/apps/maps/phot...')
#8 /srv/www/htdocs/server/index.php(42): OC::handleRequest()
#9 {main}
```

**Comment by eneiluj** [comment]
Do you know why that happens?

Does it mean the caching system did not have time to generate the cache entry? Or does it mean the cached entry (or something in the filesystem) was deleted?

Did you notice something you did that led to the problem?

I don't know much about NC caching system...

**Comment by tacruc** [comment]
It happens on my testing system after running the Unittest with ./autotest.sh. All files got deleted, too. But now the photopart is not working at all.

**Comment by eneiluj** [comment]
What is ./autotest.sh? Are you talking about the script that tests NC server? What does it do exactly?

Which files are deleted?

Is it really potentially happening in the everyday life of a Nextcloud server?

What do you mean it's not working? In general or after the execution of the autotest script?

**Comment by tacruc** [comment]
> What is ./autotest.sh? Are you talking about the script that tests NC server? What does it do exactly?

Yes, and i don't know

> Which files are deleted?

my files app was empty after that

> Is it really potentially happening in the everyday life of a Nextcloud server?

No I guess not

> What do you mean it's not working? In general or after the execution of the autotest script?

after execution of the autotest script, no image is shown on the map, even new uploaded pictures.
I don't think that it will be likley to happen in every day use. 
But in the definition it states that https://docs.nextcloud.com/server/15/developer_manual/api/OCP/Files/Cache/ICache.html#OCP\Files\Cache\ICache::get returns what we want, or a bool. And if it is returning a bool, the service crashes.

**Comment by eneiluj** [comment]
Ok then.
