### ISSUE TITLE
Question/bug (?): No name when not using Openstreetmap layer

### ISSUE THREAD

**Issue by derritter88** [nextcloud/maps#357]
Hello,

I have installed the Maps addon recently which is really an enrichment for Nextcloud!
Unfortunately I am unable to see any names (cities, towns, roads,...) when I am not using the Openstreetmap or Opentopo layer.

Is this an expected behaviour or is there anything to setup which I forgot?

**Comment by tacruc** [comment]
Well the dark layer should have labels, too. 
The Watercolor and Satellite not.

**Comment by derritter88** [comment]
Okay, can confirm that dark layer also have labels.

Are there any plans to have labels on Satellite as well?

**Comment by tacruc** [comment]
You can get a https://www.mapbox.com/ api key, than the satelite layer has labels.

**Comment by derritter88** [comment]
Great, thanks for the info!
