### ISSUE TITLE
Different Idea for update slider range

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#37]
@eneiluj : this is how I takled the same problem

     updateSliderRangeFromController: function() {
            // favorites
            var mins = [
                favoritesController.firstDate || Date.now()/1000,
                photosController.photoMarkersOldest || Date.now()/1000,
                contactsController.contactMarkersOldest || Date.now()/1000
            ];
            var maxs = [
                favoritesController.lastDate || 0,
                photosController.photoMarkersNewest || 0,
                contactsController.contactMarkersNewest || 0
            ];
            
            this.min = Math.min(...mins)
            this.max = Math.max(...mins)

            if (this.min === this.max {
                this.min = this.min - 10;
                this.max = this.max + 10;
            }
            this.updateSliderRange(this.min, this.max);
            
        },`

**Comment by eneiluj** [comment]
What problem?

I don't know about making the default min higher than the max. I wish it could stay clear.

I admit my version is a bit too verbose though...

There's still a problem when updating photo filter. After the page loads, when moving down the right slider, it does not hide the last picture. I'll fix that.

**Comment by eneiluj** [comment]
I fixed the edge problem with photos/contacts filters that was affecting filter update and reset.

As the slider range is initially 0=>now, i don"t think it's necessary to update the slider range with default values when there is not any controller value set.

It's solved to me, feel free to reopen if you want.
