### ISSUE TITLE
Favorite sharing: Zoom to bounds of favorites instead of showing whole world map

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#389]
It would look much better if the map would zoom to the bounds of the favorites layer. How is that possible? I found the `this.map.fitBounds(catLayer.getBounds(), {padding: [30, 30]});` function but don’t know how to get the layer, and neither how to get the map.

@paulschwoerer replied in https://github.com/nextcloud/maps/pull/382#issuecomment-630431091
> This doesn't seem as trivial as I first thought, as the markers are residing on different layers, based on their category. I guess it would mean to get all layer bounds and add them up somehow

I asked:
> Hmm, but if I share one set of favorites, doesn’t that mean they are the same category and thus the same layer?

---------------

See the issue here when you open a shared link:
![Maps favorites zoom to bounds](https://user-images.githubusercontent.com/925062/82676964-879c4d00-9c47-11ea-8656-c74c15933205.png)

**Comment by paulschwoerer** [comment]
> Hmm, but if I share one set of favorites, doesn’t that mean they are the same category and thus the same layer?

While that's technically true, I implemented the map container keeping in mid that there might be multiple categories in the future. But I've got an idea how to work around that. I'll see what I can come up with

**Comment by wronny** [comment]
maybe you can use #391 as a starting point or temp workaround
