### ISSUE TITLE
Photos on the map

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#4]
Using EXIF geolocation data, we could have pictures show up on the map when they have a location set. That could simply be sourced from the Files app (doesn’t really have much to do with the Gallery app).

cc @v1r0x @brantje for Maps and cc @oparoz @icewind1991 for photos and metadata.

**Comment by v1r0x** [comment]
I added exif extraction in one of the other branches (don't remember which one exacty).
So the code already exists, but should maybe moved to a separate PR. What do you think @jancborchardt ?

**Comment by jancborchardt** [comment]
@v1r0x sounds great! Maybe just find which was the branch and open a work-in-progress pull request so other people can check it out and maybe contribute. :)

**Comment by davidpeach** [comment]
I'd love to have a go at this issue. I'm looking to contribute and this looks like a good challenge. To start with.

**Comment by oparoz** [comment]
We're starting to have an EXIF issue.
Some parameters are fetched in the server, not sure if it's at upload time. I don't think it's documented yet and there is no API to retrieve the info.
There is also the mediametadata app which will eventually be finished and usable.
So we have 2 sources already and if each app starts parsing for EXIF data, then it's a hug waste of resources.

1st step  would be to identify what is going on in the server side and whether this should be extended or dropped.

**Comment by jancborchardt** [comment]
@v1r0x @nextcloud/maps could you help @davidpeach to get started here? :)

**Comment by v1r0x** [comment]
The exif stuff has already been [merged](https://github.com/nextcloud/maps/blob/master/js/script.js#L293). This is very basic and only extracts the gps position. But I'm with @oparoz . Not sure if it is good to do an own exif extraction if this is already worked on.

**Comment by e-alfred** [comment]
There is another app for Nextcloud that does exaclty this:

https://github.com/BatPio/PhotoMap

Maybe a cooperation would be useful?

**Comment by jancborchardt** [comment]
Yup, I recently saw this too. :)

@BatPio @v1r0x let's work on having this functionality directly in the rework of the Maps app! :)

**Comment by v1r0x** [comment]
Will have a look at it after the other 0.1 stuff. We should compare this one with the implementation of the old app regarding performance etc :)

**Comment by BatPio** [comment]
Duplicating functionalities is not good, but my app is almost ready and could be useful for users before this functionality will be implemented in nextcloud/map.

@jancborchardt @v1r0x I see that You started refactoring nextcloud/map. How long can it take? If it's matter of  months, then I will release my app in market.

I can help You with this feature when refactoring will be finished :)

**Comment by jancborchardt** [comment]
@BatPio I’d really prefer if we can work together here. :) Otherwise we have 5 different Maps-related apps. Let’s join forces and build one really good Maps app together. @v1r0x @eneiluj

**Comment by v1r0x** [comment]
@BatPio the basic functionality (leaflet) is already there. I'm on vacation the next days, so you could have a look at the current code base and maybe add your code as PR without me modifying the code in the meantime ;)

**Comment by jancborchardt** [comment]
@BatPio I reopened the EXIF issue in core :)

Nevertheless it seems best if first we do a working version directly inside the Maps app, cause right now we have it separate across core, Maps, and your specific app. :)

**Comment by BatPio** [comment]
@jancborchardt Ok, I have already written lat/long extraction command and files hooks for my app. I can reuse it in nextcloud/maps. I'll try to implement showing photos on map for nextcloud/maps :)

**Comment by jancborchardt** [comment]
@BatPio awesome stuff! :)

**Comment by BatPio** [comment]
@jancborchardt, @v1r0x I've finished moving code from my app. I also made some improvements. Do you want to review the changes before I make PR? https://github.com/BatPio/maps/tree/rework

**Comment by v1r0x** [comment]
I'd prefer a PR and discuss and review it then. Thanks for all the work :)

**Comment by v1r0x** [comment]
fixed in #21
