### ISSUE TITLE
OCA.Viewer in standalone mode - Images not loading

### ISSUE THREAD

**Issue by dekrabor** [nextcloud/maps#426]
Hi folks,

when I am opening the maps extension no images from the user account are loaded. This has happened for all users since I set up my Nextcloud installation.

I checked the development console and found an issue that  might cause the problem.
"No OCA.Files app found, viewer is now in standalone mode"
![bild](https://user-images.githubusercontent.com/48912666/88555623-5154c280-d028-11ea-8a87-400d8b340e95.png)
OCA.Files is available in the normal File view, so I assume this error prevents the map from showing files.

Is this an actual bug or might it be a configuration error from my side? I could not find any open issues on this topic.

Greetings
Dekrabor

**Comment by tacruc** [comment]
Have you added photos recently, or where the photos on nextcloud before the maps app was enabled?
Can you try adding new photos, with geo tags and see, if they are shown? 
Or if there are any errors in the nextcloud log, not the browser console?

The error you are mentioning is not an error just an information. The CSP error below, might be more curtial, but I'm not shure if it is.

**Comment by dekrabor** [comment]
Thanks for the quick reply tacruc.

> Have you added photos recently, or where the photos on nextcloud before the maps app was enabled? 
> Can you try adding new photos, with geo tags and see, if they are shown?
I have both cases, none of the photos are showing. But most where added after maps was enabled. I have added multiple photos with geotags, non are showing

> Or if there are any errors in the nextcloud log, not the browser console?
I checked the logs and there are no errors or any other logs generated when the map is loaded

> The error you are mentioning is not an error just an information. The CSP error below, might be more curtial, but I'm not shure if it is.
Here is a full screenshots of the errors. However I just noticed that the error does not display in Chrome, yet still there are also no images loaded on the map (and OCA.Files not available)
![image](https://user-images.githubusercontent.com/48912666/88632612-1ef0a700-d0b4-11ea-8d13-c8c24a7ffc80.png)

I ran both commands indexing commands (./occ maps:scan-photos ./occ maps:scan-tracks) again to make sure and they showed no errors and added 16.000 files.

**Comment by tacruc** [comment]
Which Kind of cron job are you using?

**Comment by dekrabor** [comment]
I triggered the indexing commands directly without a cron job at the moment. 
But the Nextcloud installation is running on a Synology Diskstation

**Comment by dekrabor** [comment]
Note, to the last question, I'm using Webcron

**Comment by tacruc** [comment]
> I triggered the indexing commands directly without a cron job at the moment.
> But the Nextcloud installation is running on a Synology Diskstation

This is correct. But the trigger will only schedule the scanning. The actuall scan of the picture will be done by a background job during the cron job. Therefore it is important that the background jobs are running.

**Comment by dekrabor** [comment]
> This is correct. But the trigger will only schedule the scanning. The actuall scan of the picture will be done by a background job during the cron job. Therefore it is important that the background jobs are running.
I double checked and the CRON jobs are running every 15 minutes. I triggered the scanning again and restarted the webserver. However there was no change :/

**Comment by tacruc** [comment]
Are there any log entries in your nextcloud log? 
I assume that there are not pictures on the map because the frontend does not recieve any pictures from the server. You could also check the reply to the request where the pictures are loaded. In the dev tools there is a network tool, where you can see all request. You should be one request called "photos" or "your.cloud/apps/maps/photos".
The response array would be interessting.

**Comment by dekrabor** [comment]
Hi tacruc,
I have just restarted the whole system and now got an error message then opening the maps area the first time. Error log is attached.
Yet after refreshing the map is loading and showing 17 photo. All those are returned as JSON in the "photos" request. However it should return a few thousand images. 

Before you noted the CRON jobs I had it in AJAX settings, yesterday switched to Webcron. Maybe it started actually adding the pictures since then? Is there a way to run the process of adding the pictures so they are returned in the photos request manually?

`[index] Error: OCP\Files\NotPermittedException: Could not create folder at <<closure>>

 0. /volume1/web/nextcloud/lib/private/Files/AppData/AppData.php line 158
    OC\Files\Node\Folder->newFolder("maps")
 1. /volume1/web/nextcloud/lib/private/Template/SCSSCacher.php line 158
    OC\Files\AppData\AppData->newFolder("maps")
 2. /volume1/web/nextcloud/lib/private/Template/CSSResourceLocator.php line 110
    OC\Template\SCSSCacher->process("/volume1/web/nextcloud/apps/maps", "css/style.scss", "maps")
 3. /volume1/web/nextcloud/lib/private/Template/CSSResourceLocator.php line 85
    OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist("/volume1/web/nextcloud/apps/maps", "css/style.scss", "maps")
 4. /volume1/web/nextcloud/lib/private/Template/ResourceLocator.php line 78
    OC\Template\CSSResourceLocator->doFind("css/style")
 5. /volume1/web/nextcloud/lib/private/TemplateLayout.php line 310
    OC\Template\ResourceLocator->find(["css/server","c ... "])
 6. /volume1/web/nextcloud/lib/private/TemplateLayout.php line 215
    OC\TemplateLayout::findStylesheetFiles(["css/server","c ... "])
 7. /volume1/web/nextcloud/lib/private/legacy/template.php line 184
    OC\TemplateLayout->__construct("user", "maps")
 8. /volume1/web/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php line 167
    OC_Template->fetchPage({user: "Sven"})
 9. /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 123
    OCP\AppFramework\Http\TemplateResponse->render()
10. /volume1/web/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Maps\Control ... }}, "index")
11. /volume1/web/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Maps\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "maps.page.index"})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "maps.page.index"})
13. /volume1/web/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "maps.page.index"})
14. /volume1/web/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/maps/")
15. /volume1/web/nextcloud/index.php line 38
    OC::handleRequest()

GET /index.php/apps/maps/
from 45.8.153.110 by Sven at 2020-07-29T14:15:00+00:00`

**Comment by tacruc** [comment]
> Before you noted the CRON jobs I had it in AJAX settings, yesterday switched to Webcron. Maybe it started actually adding the pictures since then? Is there a way to run the process of adding the pictures so they are returned in the photos request manually?

Yeah it is only working in theory with AJAX cron in practice you will need a way to many page loads to before pictures are added, as on every request only a single backgroundjob is run. And no, there is no way to do the actuall work manually. It used to be like that, but made to many problems. Just exectue the cron php on a regular basis and all pictures which are detected should show up.

I think the error is due to some permisson problems on your machine, or @eneiluj do you have an idea where the error is from?

**Comment by dekrabor** [comment]
Hi @tacruc ,
sorry that I never came back on this topic. I have found the source of this problem and fixed it since :) 
It was the CRON jobs. After switching to system CRON the pictures started showing up.

However I wanted to leave a big thanks for your great and fast support!
