### ISSUE TITLE
get and display device positions

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/maps#43]
How should we do that?

### Store

 In the DB, there could be a `devices` and a `points` table.

### Send

There could be multiple ways to send points to Maps:

* passive: when map location control is enabled, positions could be sent periodically with user agent as device ID
* active: there could be an API for clients to actively send their position to Maps

### Display

A foldable `devices` side menu entry with a sub entry for each device. It would be possible to show/hide each device display. Filtering would have an effect on which points are displayed.

Should points be displayed as a line or as markers? Line is problematic because it links positions that can be very far away from each other. Markers are problematic because it's uggly and heavy to render when there are too many.

### Extra

It would be nice to be able to share device positions with a Nextcloud user or with a public link (like files). There would be a list of shares. From the receiver point of view, it would show points starting from the moment device owner started to share. It would be possible to set an expiration date.

* sharing
* geofences (alerts/notifications when a device enters/leaves a defined area)
* export device position history (all/visible) to gpx

to be continued

**Comment by tacruc** [comment]
I would like a possibility to rename the device imported devices are just called deviceX

**Comment by eneiluj** [comment]
This happens because files coming from timeline don't provide names or my parsing does not get it correctly. I would need an example file to adjust import. Could you provide that?

Anyway I'll add device renaming soon.

**Comment by tacruc** [comment]
There is no usable name in the google export.

**Comment by eneiluj** [comment]
Device renaming is available in `rework-eneiluj` branch. As there is no "name" DB field, renaming actually changes the user agent. This is probably not definitive.

**Comment by jancborchardt** [comment]
Similar to the Contacts issue, I would add this to the 0.1 milestone and close it. We can track specific problems in separate issues rather than an overview. Makes sense?

**Comment by eneiluj** [comment]
Yep, phase 2 engaged :grin:
