### ISSUE TITLE
Shared Photos do not get scanned

### ISSUE THREAD

**Issue by mayermart** [nextcloud/maps#447]
In [Issue 123](https://github.com/nextcloud/maps/issues/123#issuecomment-531565076) i can read:

> Photos in folders "explicitly" shared with you should be scanned [...]. If that does not work, there is a bug.

So it seems like Photos get scanned with maps:scan-photos on initial scan. (At least i have Photos previously shared placed on my map) but Photos in newly shared Folders (not Groupfolders) seem not to be scanned.

=> My woman shared a Folder containing 12 Photos with me. On her map the Photos get placed. On my map the Photos do not get placed.

Can someone confirm this? As i have X*1.000 Photos on my instance i do not want to issue maps:scan-photos with no need.

NC 19.0.2
Maps 0.1.6

**Comment by lochbika** [comment]
I can confirm this behavior

**Comment by JohnEskimSmith** [comment]
I can confirm this behavior

**Comment by cryptoscuttlebutt** [comment]
It's not creating entries in the oc_jobs table when uploading files to a shared folder.

**Comment by cryptoscuttlebutt** [comment]
I've created a fast hack for testing:

lib/Hooks/FileHooks.php
Change line 51 from
if ($this->isUserNode($node) && $node->getSize() > 0) {

to
if ($node->getSize() > 0) {

It spawns some errors in log. -> Exception: Call to a member function getOwner() on null
But its working in my setup.

**Comment by voronond** [comment]
Are there any updates regarding this issue? I have the same problem.

**Comment by wiktorsikora** [comment]
Any progress on this?
