### ISSUE TITLE
Failed to Install NextCloud 20 using Postgres

### ISSUE THREAD

**Issue by kaleb** [nextcloud/maps#463]
Received the following error when attempting to enable:

> Column name "oc_maps_address_geo"."object_uri" is NotNull, but has empty string or null as default.

**Comment by tacruc** [comment]
Are you trying to install maps on nextcloud 20 or are you installing Nextcloud 20?
The release of maps for NC20 will be published soon, this error should than be fixed.

**Comment by beccon4** [comment]
certainly just a workaround - but you could login as postgres - and then connect to the database

`\c nextcloud (or how you called your database)`

and then set the column to nullable

`ALTER TABLE oc_maps_address_geo ALTER COLUMN object_uri DROP NULL`

[Postgres Doku](https://www.postgresql.org/docs/12/sql-altertable.html)

With that you simply drop the NOT NULL constraint from the column. I have no idea if this causes trouble later on - but it seems to be worth trying

**Comment by tacruc** [comment]
Thx, it is already fixed by https://github.com/nextcloud/maps/pull/453
