### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/maps#466]
Hi, 
a question and a feature request at the same time: 
1. is someone working on an Android application that works specifically well with Nextcloud maps? 
2. Or is the aim that it stays web-based and is loaded in mobile's web browsers, like a PWA?
3. Or can existing map applications like Osmand be expected to make use of the full functionality of Nextcloud maps? 

If "no" to 1, feature request hereby!

**Comment by tacruc** [comment]
There is phonetrack, and an open discussion in the OSMand issue tracker for synchronization. 
I don't have the time to develop an android app, but feel free to give it a try.
