### ISSUE TITLE
exif_read_data is making problems

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#47]
On most of my jpegs php read exif is throwing errors. This is giving me a hard time to get 1000 picture in my test installation to do some performance testing. 

`exif_read_data(P1050526.JPG): Process tag(x013B=Artist ): Illegal components(0) at /srv/www/htdocs/server/lib/private/legacy/image.php#418`

I didn't manage to make it more stable, but the metadata app is reading them correctly. 
Some sample picture:
![P1010498](https://user-images.githubusercontent.com/402891/56680505-aab4a000-66c7-11e9-902d-49806347ca1b.JPG)

**Comment by v1r0x** [comment]
pel (lib to read exif data) is already included as composer dep and doesn't rely on anything. You should be able to get exif data from pel without using `exif_read_data`. But I agree that there should be some kind of error handling (regardless which method is used).
