### ISSUE TITLE
Photos Overlay Shows Nothing

### ISSUE THREAD

**Issue by Condoulo** [nextcloud/maps#483]
Nextcloud: 20
Maps: 0.1.8

Despite the Maps application seeing 6,175 photos with Geotagged data the photos overlay does not appear to be functional. 
![image](https://user-images.githubusercontent.com/46665887/96132686-4b9ca980-0ec0-11eb-8f33-23135300ea83.png)

I am getting the following errors from the Console: 
![image](https://user-images.githubusercontent.com/46665887/96132057-8b16c600-0ebf-11eb-99ef-bc241d18520c.png)

Looking at the warnings from the Console I see one warning per detected photo regarding OC.Util.formatDate, unsure if that is related: 
![image](https://user-images.githubusercontent.com/46665887/96132509-1abc7480-0ec0-11eb-8e9a-36444531a0e4.png)

**Comment by Condoulo** [comment]
Disregard anything above, it appears that photos on the maps won't get repeated which is what caused my confusion. 

Should this be a separate issue, if at all? I'll let you guys decide, but my immediate concerns have been alleviated. 

![image](https://user-images.githubusercontent.com/46665887/96137613-7687fd00-0ec2-11eb-939a-dfc43e8bfbb9.png)

**Comment by tacruc** [comment]
Duplicate #427
