### ISSUE TITLE
Share Placed Photo on Map

### ISSUE THREAD

**Issue by Fynenix** [nextcloud/maps#487]
Is there a way to share the Photo with the Location on the Map with other users on nextcloud?

When I Place a photo on the map i want that the other users see the picture on their own map.
Or is there a way to share the whole map?

**Comment by tacruc** [comment]
Not yet. If you share the picture the others should See it in there map. 
The in the mymaps Branch we're working on custom and sharable maps, feel free to test it.

**Comment by Fynenix** [comment]
Okay thanks.

When i placed a photo on my map, i share it with the user like this.
![image](https://user-images.githubusercontent.com/67441473/97077494-7e435200-15e4-11eb-8aa3-83b7ca6a5333.png)

But the other user doesn't see the shared picture on their map.
Im I doing something wrong?

**Comment by mayermart** [comment]
Shared Photos do not show up on others maps. They don't get scanned. See https://github.com/nextcloud/maps/issues/447

**Comment by Fynenix** [comment]
> Shared Photos do not show up on others maps. They don't get scanned. See #447
Okay, is there a fix or workaround for that?

**Comment by tacruc** [comment]
This issue should be fixed in the v0.2.5 nightly builds.
