### ISSUE TITLE
cannot display gpx file with multiple tracks

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/maps#489]
in the attached archive you can find two files
- test20.gpx contains 20 tracks and works
- test30.gpx contains 30 tracks and cannot be displayed

NC: v20.0.1

[test-gpx.tar.gz](https://github.com/nextcloud/maps/files/5434866/test-gpx.tar.gz)

**Comment by tacruc** [comment]
@schaarsc sorry for the late response. I Just tested on v0.2.5-x-nightly and it seeams to work
![image](https://user-images.githubusercontent.com/402891/224313484-c498cf72-7e5d-464e-8f64-7a39da47e637.png)
