### ISSUE TITLE
Import location history from Google

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#49]
I imported my google location history, as track, but this is not practicle. Reading the file like this at once tool 2.6 GB of ram in my case and showing everything on the map is no fun.

So probably it should be imported as device, or?

Any other ideas, to that topic? 
@eneiluj  you did something similar in phonetracks or?

**Comment by eneiluj** [comment]
Could you be more precise on what this file contains? A bunch of waypoints, one segment, multiple segments?

Which format is it? Kml? How did you convert it to gpx?

What's the size of your file?

I remember doing something to let users import such files in PhoneTrack. I'll check that soon.

**Comment by eneiluj** [comment]
Answers to the previous questions still interest me :wink:.

I ported what had been done in PhoneTrack to import kml files coming from google timeline. It's memroy and time efficient. It was successfully tested in PhoneTrack with 200MB files.
It's now also possible to export all devices to gpx and to import such files.

It's all in `rework-eneiluj` branch if you want to give it a try.

I'll make it possible to export a single device soon.

**Comment by tacruc** [comment]
Your new PR solves this.
