### ISSUE TITLE
Cannot find devices on map

### ISSUE THREAD

**Issue by cvinhaes** [nextcloud/maps#491]
I have two iPhones running the latest nextcloud app (as of Oct'20) and the latest maps app installed with nc 20. I cannot find any of the devices on the map using the accounts devices are logged or the admin user. Do I need to install or configure anything else to be able to view the devices on the map?

**Comment by fazlerabbi37** [comment]
I think this same issue is being discussed here on #113. If that's the case please close this issue and continue discussion there. Thank you!

**Comment by cvinhaes** [comment]
Guess so, thanks for pointing it out.

**Comment by cvinhaes** [comment]
Guess so, thanks for pointing it out.
