### ISSUE TITLE
Add ability to create maps

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/maps#492]
It would be nice to be able to create different maps with different favorites / want to go places / tracks in it. 
In the navigation we could then have all the maps like:

- Main;
- 2020 Christmas vacation (Shared with Alice, Bob and other 2);
- Places to rent (Shared with Jane);
- Hikes that I enjoyed;

...and so forth

The good thing about this is that it would allow granular sharing of different favorites/tracks and would also de-clutter the main map from things that one might not need there all the time.

We could also have a navigation entry that merges all maps into one, much like the "All inboxes" in mail.

cc @nextcloud/designers

**Comment by tacruc** [comment]
Can you checkout the my maps Branch if it goes in the direction your thinking oft?

**Comment by lizeidsness** [comment]
I like this idea - is it something getting brought into the main app?

**Comment by tacruc** [comment]
That The idea, but don't ask for any schedule. There is a new branch something like enh-vue-rewrite-my-maps. Feel free to test it, but it is work in progress.

**Comment by lizeidsness** [comment]
Happy to look into this, but I am new to dev side of things with nextcloud - might take me a bit to get oriented...

**Comment by ma12-co** [comment]
@lizeidsness thanks for that! You can ask for help in [our maps public channel](https://cloud.nextcloud.com/call/ii2tvobc) 
or in[ our community chat](https://cloud.nextcloud.com/call/xs25tz5y). 
If you quickly want to spin up a dev environment I suggest you use this: https://github.com/juliushaertl/nextcloud-docker-dev!

**Comment by lizeidsness** [comment]
Oh that's helpful thanks! I spent a night looking into it and couldn't get it working.  I used the main docker not dev and had to add stuff to it.   I've got errors still.  I'll try new docker and try again.

**Comment by bes1002t** [comment]
I'm looking forward to this. It will be very helpful for touristic activitiy for instance.

**Comment by tacruc** [comment]
Since some time there are nightly builds.
They can be installed via
`occ update maps --allow-unstable`

Testing and feedback is appreciated
