### ISSUE TITLE
occ error - activation failed

### ISSUE THREAD

**Issue by vantino** [nextcloud/maps#503]
I am running NC 19.0.4 on a raspi 4. Once I want to activate the map, I get the following msg.

Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
Column name "oc_maps_address_geo"."object_uri" is NotNull, but has empty string or null as default.

Thats a pitty, I really want to use this app.

Ideas/Assistance .. ?

Thanks

**Comment by vantino** [comment]
Toll, super .. und wo finde ich nun die Lösung dazu ?

Von: Arne Hamann <notifications@github.com>
Gesendet: Dienstag, 24. November 2020 13:51
An: nextcloud/maps <maps@noreply.github.com>
Cc: Marc Vantino <vantino@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/maps] occ error - activation failed (#503)


Closed #503<https://github.com/nextcloud/maps/issues/503>.

**Comment by eneiluj** [comment]
It's been fixed in #453. It's included in latest release...which is only compatible with NC >= 20.

**Comment by vantino** [comment]
https://www.elliottwave.com/free-events/freepass-asia/reports

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

**Comment by vantino** [comment]
https://tradersacademy.online/trading-courses/python-tws-apir

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>
