### ISSUE TITLE
Bower notes it is deprecated

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#52]
During `make` one of the errors is:
```
npm WARN deprecated bower@1.8.8:
We don't recommend using Bower for new projects.
Please consider Yarn and Webpack or Parcel.
You can read how to migrate legacy project here:
https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

So we should probably migrate? :)

**Comment by eneiluj** [comment]
There is no dependency in `bower.json` so we could simply get rid of bower unless you know there is going to be, for sure, a dependency that is impossible to find in NPM.

I just removed it from `package.json` in `rework-eneiluj`.
`.bowerrc` and `bower.json` were also deleted.

All good?
