### ISSUE TITLE
Maps icon missing

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/maps#533]
![2021-01-31 10_37_33-New Issue · nextcloud_maps](https://user-images.githubusercontent.com/51749973/106380104-5ff1ad00-63b0-11eb-98ff-6f7b8233d51d.jpg)

Unlike the majority of the other apps, there isn’t an icon for the Maps app in the tab (tested on Firefox and Brave). I don’t know if it’s easy to set it up ? Thanks.

And thank you for this amazing app which is soooo great.

**Comment by tacruc** [comment]
Working in v1.0.0-x-nightly
![image](https://user-images.githubusercontent.com/402891/226143993-14705f03-8e7d-406d-b236-8b06d434785c.png)
