### ISSUE TITLE
images not opening in NC21

### ISSUE THREAD

**Issue by beardhatcode** [nextcloud/maps#543]
I just updated to NC21, but now I can no longer view images from maps, instead I see a spinner (the same files do view from Files and in the Photos app)

When looking at the console, I see that the preview is successfully fetched, but it is not shown. 

![screenshot_2021-02-26-091745](https://user-images.githubusercontent.com/662538/109274690-16ac4600-7814-11eb-8852-c9ef2ddc4bb6.png)
[console-export-2021-2-26_9-15-49.txt](https://github.com/nextcloud/maps/files/6048350/console-export-2021-2-26_9-15-49.txt)

NC21.0.0, Maps 0.1.8

**Comment by neuherzk** [comment]
HI,
I have exactly the same issue, did you find a solution?

**Comment by tacruc** [comment]
@eneiluj @skjnldsv @juliushaertl  
is this an error of the viewer or do we provide the wrong file object?

```JavaScript
canDelete() {
	return this.currentFile?.permissions?.includes('D')
},
```
For some reason permissions is an integer valued 27 in my case.
The currentFile Object exampe:

```JSON
basename: "2629971823265445308_account_id=3.jpg"
dateTaken: ***8887735
etag: "***60521b5f8899967cefbf380a809de"
failed: false
fileId: ***4023
fileid: ***4023
filename: ***
hasPreview: true
lastmod: ***41743**
lat: 48.***
lng: 7.***
loaded: false
mime: "image/jpeg"
modal: {…}
path: ***
permissions: 27
size: ***547
type: "file"

```

**Comment by juliushaertl** [comment]
Seems like an issue with a manually provided file info here. For the files app permissions are handed over from the webdav response in a string based represenation.

@skjnldsv I guess it would make sense to not only check for the dav permission flags but also try to check against the bitwise permissions when a numeric value is provided.

**Comment by RobinFrcd** [comment]
Same issue here, I also get a `permissions: 27`. When I check in DB (`oc_filecache`) the permissions field is also 27.
So the conversion from `27` to `RGDNVW` is omitted somewhere.

**Comment by Olliek95** [comment]
Same here. Any update on this issue? Is there anything we can do to help diagnose this problem?

**Comment by skjnldsv** [comment]
> @skjnldsv I guess it would make sense to not only check for the dav permission flags but also try to check against the bitwise permissions when a numeric value is provided.

Yeah, I'm fine with that, but this is frustrating to have to manage both cases :thinking: 
Can dav return the bitwise?

**Comment by juliushaertl** [comment]
> Can dav return the bitwise? 

I'm not sure about that, while the permissions dav property is in the http://owncloud.org/ns namespace so nothing that seems to be inside of the webdav standard itself, it would be a breaking change for clients all over the place. 

As a workaround the maps app could of course just map those permissions from the bit flags to the dav format based on how the backend does it in https://github.com/nextcloud/server/blob/19a3ac67a719e3e71fabdffe8921dbbd9ffc22fc/apps/dav/lib/Connector/Sabre/Node.php#L300-L327

**Comment by tacruc** [comment]
Whats inconvenient is that \OCP\Files\Node implemented by OC\Files\Node
 https://github.com/nextcloud/server/blob/19a3ac67a719e3e71fabdffe8921dbbd9ffc22fc/lib/private/Files/Node/Node.php#L215 does not provide getDavPermissions. 
So I will solve the problem, by not providing permissions in https://github.com/nextcloud/maps/blob/fbf257d31b0b7c4753ef3b5e2b30dab4dd2f5689/lib/Service/GeophotoService.php#L97

Anyhow I think the root issue should be fixed in server or viewer.

**Comment by tacruc** [comment]
Anybody out there willing to test #559?

**Comment by neuherzk** [comment]
Hello,

many thankks @tacruc I can confim its working again.
Just "git pull" and jippi working :)
![image](https://user-images.githubusercontent.com/52923848/110896170-55a1c780-82fb-11eb-89ae-4db5d981084e.png)

**Comment by RobinFrcd** [comment]
Thank you very much for this fix!

Any chance to have a release with it soon ? Thanks!

**Comment by beardhatcode** [comment]
Works for me. Thank you @tacruc.

**Comment by kedare** [comment]
Up, any idea of when this will be released ?
Thanks
