### ISSUE TITLE
Exclude photos from certain folders from being shown on the map 

### ISSUE THREAD

**Issue by ichwillkeinenaccount** [nextcloud/maps#555]
It would be nice if the user could exclude certain folders from being scanned for the maps app. Maybe with something like the a .nomedia/.noimage or .nomaps file inside these folders. (https://github.com/nextcloud/photos/issues/234)

**Comment by Stifler6996** [comment]
This!

I have a personal share on a NAS. Its got tons of stuff in it. One folder is my Samsung Backup folder for my devices.
For each device, and for each backup, it stores certain stuff "as-is" and guess what. the DCIM folder is one of them.

So 3 devices, 5 historical backups each, there are (in some cases) 15 copies of a photo in 15 different folders. Not to mention the photos have been moved to my normal "Photos" location as well!

Please, let us select which folders are included or excluded, somehow.

Personally, I have never enjoyed the .nomedia/.nomedia option, it is counter productive. The "correct" method IMO, is to select which folders are scanned in the first place.

**Comment by tacruc** [comment]
Duplicate #143

**Comment by tomsik-radek** [comment]
> Duplicate #143

I'm sorry but I don't believe scattering .nomedia into every folder is a proper solution

**Comment by HammyHavoc** [comment]
> > Duplicate #143
> 
> I'm sorry but I don't believe scattering .nomedia into every folder is a proper solution

You're right, this isn't a proper solution. Perhaps what might make sense is some kind of option available in the 'Sharing' panel for a folder, where users choose to scan a particular folder, and its children.
