### ISSUE TITLE
Photos don't show full screen on Nextcloud 21

### ISSUE THREAD

**Issue by miklasiu** [nextcloud/maps#593]
I tried the app on Nextcloud 21. I use it basically to only show photos. So they do show, miniatures look ok, but when you click on a photo they overlay shows but the image is not being loaded. You can close the overlay normally. It works ok from files. When photo is displayed from files on the top there is a file name shown and after a moment the image is loaded. Here - from maps - neither the filename on top nor the image itself is displayed. The page title does change to image file name though. I can open sidebar and the miniature is shown on top of it.
Not sure it may be related but I host it on a very slow CPU (E350) so it just may be a timeout or something like it.

**Comment by amo13** [comment]
I can confirm this is happening on my nextcloud instance too. Noticed it a while back. Might have been the same on NC 20 already. Loading is ok from the Files app, but does not load at all from the Maps app.
