### ISSUE TITLE
Finish maki icons (add more POIs/icons and throttle api calls)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#6]
(reopening original issue by you @v1r0x ;)

Currently we fire too much calls to the overpass api (see https://github.com/owncloud/maps/pull/112#issuecomment-179490200).
Also there are only 'must have' POIs. We should add some more, see https://github.com/owncloud/maps/blob/master/js/script.js#L1340-L1342 for the missing POIs

refs #13 and #46 as well

**Comment by tacruc** [comment]
@jancborchardt  can we close it?

**Comment by jancborchardt** [comment]
Yep, thanks for checking through! :)
