### ISSUE TITLE
.nomedia ignored

### ISSUE THREAD

**Issue by schklom** [nextcloud/maps#607]
Hello,

My folders and files are:
```
-- Backup/
    -- .nomedia
    -- Photos/
        -- image1.jpg
        -- image2.jpg
```

Both jpg images were scanned and added after running `php occ maps:scan-photos -v`.

I don't want my Backup folder to be scanned, that's why I included a `.nomedia` file.
Is this a bug, or did I mess something up?

Many thanks :)

**Comment by StarSmasher44** [comment]
Since no one seems to be assisting you, could you perhals try a .noimage file instead, and see if that may help? I've seen some apps/websites use one or the other, perhaps this is the same.

**Comment by schklom** [comment]
Hey, thanks for the idea!

Unfortunately, even with `.noimage` the pictures are still added.
```
[1144] Photo "/schklom/files/Backup/phone/Storage/Media/Images/IMG-01.jpg" added
```
despite `/schklom/files/Backup/` containing `.noimage` or `.nomedia` or both.

**Comment by jZ7He56RkPTYABUjfww4** [comment]
I've looked through the issues and it seems like this is a problem that is still being worked on. There's discussion about excluding folders with photos and gpx files from being scanned/added to the map, but I don't think there's been any progress made towards a solution.

In addition, there doesn't seem to be any mention in the repository about `.noimage` or `.nomedia`.

I'm in the same position. I have my gpx files I've recorded myself, then I have very large archives of gpx files I use on my GPS devices. I don't want to include the large archives and I need a way to exclude them from the map, or even from being scanned.

**Comment by schklom** [comment]
Similar to #143

**Comment by schklom** [comment]
I made a PR https://github.com/nextcloud/maps/pull/617, would you mind testing it to see if `.noimage` and `.nomedia` are taken into account? :)

Go ahead and read the update before building it, it is really straightforward.

**Comment by tacruc** [comment]
#143
