### ISSUE TITLE
Maps 0.1.9 on Nextcloud 21.0.2 Images not loading spinning wheel

### ISSUE THREAD

**Issue by apg1980** [nextcloud/maps#609]
Hello,
no image are loadet on the map after clicking.
I get a spinning wheel, the sidebar is showing the image.
![grafik](https://user-images.githubusercontent.com/9514965/119772863-1decf980-bec0-11eb-8dea-57b27b55d469.png)

**Comment by tacruc** [comment]
duplicate: #543
