### ISSUE TITLE
Exclude/ignore folder (with gpx etc files)

### ISSUE THREAD

**Issue by Bergum** [nextcloud/maps#612]
Is there a way to ignore some folders? 
I have a lot of gpx files, and the spinny thing where the map list was, is just spinning.
It got slower and slower as i added files, and now I can't use it on a computer on cellular.

Can we get a .notrack or something to exclude the search?

**Comment by schklom** [comment]
I have almost the same problem in #607 with backups being scanned for no reason.

`.nomedia` and `.noimage` aren't taken into account

**Comment by tacruc** [comment]
Lets bundle this in #143. As I think it is related.

**Comment by torygg** [comment]
Hello,
this is not related to 'Photos' = .nomedia
Tracks are still not ignored... I currently have a folder with 3000+ gpx-Track-Files which are not possible to 'navigate' through within the Maps-Apps.
So please establish something like a .notracks option to exclude the main tracks folder, and only 'use' a separate folder for all 'active' tracks...
