### ISSUE TITLE
No photo in image viewer

### ISSUE THREAD

**Issue by millenseer** [nextcloud/maps#625]
Nextcloud Version 21.0.2
Version Maps 0.1.8

My photos are displayed on the map. When hoovering above a single photo, the photo is displayed in a small popup.
When I click the photo, the image slider does not show any photo, just the rotating icon is displayed forever.

Using browser debugger, I can see the XHR-Request to the photo:
https://XXX/remote.php/dav/files/YYY/Photo-2015-05-04-06-16-23_2453.JPG

The response code is 200. Using the above URL,  I can download the photo.

The console shows:
Viewer.vue 
Opening viewer for file  /YYY/Photo-2015-05-04-06-16-23_2453.JPG

vue.runtime.esm,js:1888
`TypeError: e.includes is not a function
    at a.canDelete (Viewer.vue:239)
    at pn.get (vue.runtime.esm.js:4479)
    at pn.evaluate (vue.runtime.esm.js:4584)
    at a.canDelete (vue.runtime.esm.js:4836)
    at fn (Viewer.vue?d560:1)
    at r (vue.runtime.esm.js:2590)
    at a.ve [as _t] (vue.runtime.esm.js:2686)
    at a.<anonymous> (Modal.js:151)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)`

Re-installing the module did not help.

Any idea?

Apropos. I have no idea how to use the phone tracking feature (iOS)? No documentation found.

**Comment by rndmh3ro** [comment]
Upgrading the maps app to 0.1.9 fixed this for me.

**Comment by tacruc** [comment]
We have a reimplemented the entire front-end in v0.2.0.
If the Issue still exits in the new implementation, feel free to reopen this this.
