### ISSUE TITLE
no photos on maps 

### ISSUE THREAD

**Issue by dem-ars** [nextcloud/maps#626]
photos does not display on my nextcloud server  in maps 
server details: 
CentOS 8
NC  21.0.2
database Postgres
webserver Nginx
Maps app v0.1.9-8-nightly, manual installation with recocemdations from https://github.com/nextcloud/maps/issues/566

_[root@arshome_server1 html]# sudo -u nginx php occ maps:scan-photos
[160] Photo "/demars/files/Publuc share/IMG_20210515_120003.jpg" added
[161] Photo "/demars/files/Publuc share/IMG_20210515_120027.jpg" added
[162] Photo "/demars/files/Publuc share/IMG_20210621_205533.jpg" added
[163] Photo "/demars/files/Publuc share/IMG_20210621_205536.jpg" added
[164] Photo "/demars/files/Publuc share/IMG_20210621_205541.jpg" added_

EXIF metadata in files presented

_Date created: | 2021-05-15 12:00:05
Dimensions: | 4656 x 2620
Camera used: | Xiaomi MI 9
Exposure: | 1/608 sec. f/2.2 ISO-100 +0 EV
Exposure program: | Normal program
Focal length: | 2.25 mm (35 mm equivalent: 15 mm)
Max aperture: | f/2.2
Metering mode: | Center Weighted Average
Flash mode: | No flash, compulsory
GPS coordinates: | N 43° 26' 54.99" E 39° 56' 32.49"
GPS altitude: | 62.1 m
Location: | Molokova Street, Sochi, Russia_

**Comment by MelBourbon** [comment]
In my case only one picture is shown. Not the rest.

**Comment by dem-ars** [comment]
Problem had solved
it was problem with Cron https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron

sudo crontab -u nginx -e
add:
*/5  *  *  *  * php -f /usr/share/nginx/html/cron.php
