### ISSUE TITLE
Device icon and description

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/maps#647]
Steps:

1. Add a device.
2. Select "Devices" from the menu.

Description of the device name in the "Devices" menu overlaps with its icon. There is no padding between the icon and the device name description.

![obraz](https://user-images.githubusercontent.com/47037905/131130326-616a933c-77f0-42df-a204-7eee3c9cbcb4.png)

Apps:
Nextcloud 22.1.1
Maps 0.1.9
Firefox 91.0.2

**Comment by Valdnet** [comment]
The same for "Your photos":

![obraz](https://user-images.githubusercontent.com/47037905/131229598-94016436-642c-410d-b031-7dba772421be.png)

**Comment by sean13013** [comment]
Same here, additionally the nested items under "Your favorites":

![nextcloud-favorites-icon-overlap](https://user-images.githubusercontent.com/43933879/133862396-9b0f5851-e3a7-4b55-89ab-d4d4d412bc41.png)

 and "Your tracks":
![nextcloud-tracks-icon-overlap](https://user-images.githubusercontent.com/43933879/133862400-9e479a28-0141-4f4b-b9a0-24aa8c9cf810.png)

Tested in firefox 91 and chromium 93

**Comment by shirou93** [comment]
Photos:
![image](https://user-images.githubusercontent.com/59237288/134641317-6d00901b-912d-4490-8ab6-bff7b06a4351.png)

**Comment by BWibo** [comment]
I can confirm #654 fixes this for the *Photos* icon. However, the problem persists for the icons of contact groups.
![grafik](https://user-images.githubusercontent.com/7643434/146783883-2a7eb46e-559e-4451-9720-1b6d60642187.png)

Probably, the fix provided in #654 just needs to be applies at another place too.

Tested with this: https://github.com/BWibo/nextcloud-compose/tree/caddy
Nextcloud 23-fpm, Maps v.0.1.10

**Comment by szaimen** [comment]
cc @RobinFrcd

**Comment by RobinFrcd** [comment]
@szaimen Indeed, I don't have any address in my contacts, so I missed this one. Sorry about that, should be good with https://github.com/nextcloud/maps/pull/678

**Comment by szaimen** [comment]
@RobinFrcd all fine :)
