### ISSUE TITLE
Contacts not shown on maps

### ISSUE THREAD

**Issue by MikeKnife** [nextcloud/maps#669]
Contacts are not shown, if the Country Field (German: Land) is populated. 
Sometimes, if there are only a few letters filled in it still shows the loacation; as soon as there is a longer country-name filled in, the position is not shown anymore.

Maps V. 0.1.9
Nextcloud V. 22.x & 23.x

Mike Knife

**Comment by marvinjuette** [comment]
I can confirm that contacts are not shown on the map. I looked in the console and found the following error:

![grafik](https://user-images.githubusercontent.com/46931628/152692883-47595ea9-0e40-4ee1-93a1-2e775895b9cc.png)

It seems to me that the adresstype is not handled correctly.

**Comment by tacruc** [comment]
We have a reimplemented the entire front-end in v0.2.0.
If the Issue still exits in the new implementation, feel free to reopen this this.
