### ISSUE TITLE
How to regenerate oc_maps table 

### ISSUE THREAD

**Issue by buoncri** [nextcloud/maps#67]
Hi 
After a first installation of nextcloud/maps i made a - maps:scan-photos - with a big network folder shared to all users. The result was a very big confusion :-D 

Then i thought to try to uninstall and reinstall to have a 'vanilla' maps environment that not have the big data generated by scanning a big network folder for all users, but it seems the db structure was the same before the reinstallation.

So i decide to try to delete all oc_maps* postgres tables (and oc_appdata mas records), thinking that the reinstall process will recreate, but now the installation process don't recreate missing tables.

So i am asking here how to regenerate oc_maps table or what i have to delete for forcing recreation of the db app environment ?

Thanks

**Comment by buoncri** [comment]
Now i have fixed db problems and while i am reindexing the photo with  sudo -u www-data ./occ maps:scan-photos , i noticed that the process is indexing external file mounted with 
Prewiew false property (in external_file).

I suggest if is possible to not index photo on external folders when preview flag is false.

**Comment by eneiluj** [comment]
How did you regenerate DB schema again? By triggering all migration steps manually?

> Preview false property (in external_file)

What do you mean by that? Is it a setting?

I agree it seems wise to avoid  showing photos for which it's impossible to generate previews. Maybe we're still going to index them...

**Comment by buoncri** [comment]
How did you regenerate DB schema again? By triggering all migration steps manually?
- the only way i found is to get them from a backup. A command like occ map:reset_db can be usefoul for testing an analising

What do you mean by that? Is it a setting?
- External_folders, when configuring shares to mount has a property for disabling preview in gallery app. So gallery do not show preview for that big network shares, it can be right. 

![immagine](https://user-images.githubusercontent.com/3062441/61771967-6bded500-adf1-11e9-8979-2e6af218f4db.png)


I sow inseat, that nextcloud/maps when made a - occ maps:scan - is indexing those big shared folder. I think it can be usefoul to make the same that gallery do.

Thanks to all

**Comment by eneiluj** [comment]
Right. Such external storages are not explored anymore. Thanks for the suggestion!

**Comment by buoncri** [comment]
Thanks to you for the code :-D

**Comment by jancborchardt** [comment]
Is there anything left do do here? :)

**Comment by eneiluj** [comment]
I don't think so.

**Comment by buoncri** [comment]
hi
today i was doing a ./occ maps:scan-photos and i notice that maps is indexing network connected folder too, while network folders have no preview like ... So, no preview, but gps index ?

**Comment by buoncri** [comment]
are
