### ISSUE TITLE
A different kind of map

### ISSUE THREAD

**Issue by dirkca** [nextcloud/maps#670]
Hi. I am scoping the possibility to replace the map and modify the app. Where/who could I contact?

The idea: Visualize a prescribed curriculum for grades Kindergarten to Grade 12. Break down map into grades and/or subject areas. Teachers 'travel' the map looking for resources. Display folders and subfolders.

**Comment by dirkca** [comment]
The ability to add folders, files, URL's etc. to the map would be super helpful.

**Comment by elearningdienst** [comment]
Great Idea, it could be very helpful to share map areas to the public. With that people could explore the areas e.g. mock-up from a festival ground, a company area or a school ground. 

So users can share additional information about areas. That's a really great adittion!

**Comment by elearningdienst** [comment]
May maybe integrated with that idea: https://github.com/nextcloud/maps/issues/667

**Comment by GAS85** [comment]
You can do this already today with [GPXPod](https://apps.nextcloud.com/apps/gpxpod), simply create a share to the folder and share your view under the app:
![grafik](https://user-images.githubusercontent.com/6813635/147911373-c8e3dab6-9cc8-4284-a2d6-71af4722df16.png)
You will get something like this with even control of all parameters via query:
```
https://FQDN/index.php/apps/gpxpod/publicFolder?token=XXXXXXXXXX&autopopup=y&autozoom=n&showchart=y&tableutd=y&layer=OpenStreetMap&displaymarkers=y&showpics=y&transp=n&lineborders=y&simplehover=n&rteaswpt=n&arrow=n&sidebar=1&lineweight=5&color=elevation&colorext=&tooltipstyle=h&draw=trw&waystyle=Pin%2C%20Blue&unit=metric
```
![grafik](https://user-images.githubusercontent.com/6813635/147911630-d4f2775d-6046-4d0f-a010-57478aff238c.png)

**Comment by tacruc** [comment]
I think this is implemented with the collaborative maps feature. You can try it with the v0.2.5 nightly builds.
