### ISSUE TITLE
Photo Scan stops when $pelIfdGPS->getEntry(PelTag::GPS_LATITUDE_REF) is null.

### ISSUE THREAD

**Issue by zhangguojvn** [nextcloud/maps#671]
Error: Call to a member function getValue() on null in /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php:479

Stack trace:

#0 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(384): OCA\Maps\Service\PhotofilesService->getExifPelBackup(Object(OC\Files\Node\File))

#1 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))

#2 /var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow(Object(OC\Files\Node\File), 'user')

#3 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run(Array)

#4 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))

#5 /var/www/html/cron.php(128): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))

#6 {main}

**Comment by zhangguojvn** [comment]
I found that this keyword is optional. How should we deal with the situation that the keyword is empty?

https://dicom.innolitics.com/ciods/vl-photographic-image/vl-photographic-geolocation/00160071

**Comment by kovge** [comment]
Hi @zhangguojvn ,

i have made a pull request regarding exif data issues: https://github.com/nextcloud/maps/pull/586
There is a refactor with robost error handling.
Do you have a chance to test if this pull request resolves your problem?

Thank you

**Comment by tacruc** [comment]
Could you check if v0.2.0-1-nightly solves the Issue.
It can be installed by
occ app:install maps --allow-unstable
or updated
occ app:update maps --allow-unstable

**Comment by elearningdienst** [comment]
Try to do that. System installed not the nightly build.

sudo -u www-data php /var/www/nextcloud/occ app:install maps --allow-unstable
maps 0.1.10 installed
maps enabled

What can I do to let nextcloud recognise the nightly build?

**Comment by tacruc** [comment]
Can you try
`sudo -u www-data php /var/www/nextcloud/occ app:install --allow-unstable maps`

**Comment by elearningdienst** [comment]
That has the same issue.

sudo -u www-data php /var/www/nextcloud/occ app:install --allow-unstable maps
maps 0.1.10 installed
maps enabled

**Comment by elearningdienst** [comment]
Installed manually. But can't test. I'm on PHP8.1, so the app could not be activated. Didn't realized the PHP Version requirement before.

**Comment by adripo** [comment]
I am not having this same error, but I have some photos on map at 0N,0W. I checked with ExifTool and found out that the GPS fields are present but have null values. I think this issue might be related. Can those be excluded from the map?

![image](https://user-images.githubusercontent.com/26493496/182005621-66fe6506-3115-4f90-b2d4-c14c8379a723.png)
![image](https://user-images.githubusercontent.com/26493496/182005636-e272991d-8e81-458f-8647-b0e3be5805ec.png)

**Comment by kovge** [comment]
Hi @adripo 

i added in my old commit a parameter to the validate function in `ExifGeoData`  class.
Here: public function validate( $invalidate_zero_iland = false )
If this parameter is true, than the photo won't go through the validation in case if it has invalid or NULL geoocoordinates.

This parameter is not configurable in settings at the moment.

If it is true, than you have the issue, that the photo is not shown on map at all.

If it is shown (like now) you have a chance to add a location for it.

I guess it could be also a nice change , that the Zero Island checking is confifurable via the app's settings.

**Comment by tacruc** [comment]
@kovge 
The zero island should be invalid by default in version v0.2.0? See
https://github.com/nextcloud/maps/blob/f682b72f9d8c6220347d8ab26a06d2a9f35e6a38/lib/Service/PhotofilesService.php#L401 

So there are two reasons for the images to still show up.

1.  The scan was done before v0.2.0.

Then it should be resolved by 
`occ maps:scan-photos`
(optionally with --now)

2. I am missing something.

**Comment by adripo** [comment]
> 
> 1. The scan was done before v0.2.0.
> 
> Then it should be resolved by `occ maps:scan-photos` (optionally with --now)
> 


I did the manual scan once I installed the app 2 days ago, already with 0.2.0.
Anyway I lunched the scan again but nothing changed. If can be helpful I can share an image with this issue with you.

**Comment by adripo** [comment]
@tacruc I sent you an email with one file having this issue.

**Comment by tacruc** [comment]
@adripo would it be OK for you, if I include a downscaled Version of the image as a testcase?
You can check https://github.com/nextcloud/maps/tree/master/tests/test_files/Photos/WithDateAndLocation how far I scale them down sofar. I probably go down to 1x1 pixel, but I would like to keep the metadata.

**Comment by adripo** [comment]
@tacruc Sure, no problem. I'm ok with scaling it down.

**Comment by adripo** [comment]
@tacruc  I just checked and it solves the issue.
I tested it by uploading a photo with the 2.0.0 version and then the same photo with the version from your pr. As you can see in the db, with the new version the `lat` and `long` are correctly set to `null` for the same photo.
![image](https://user-images.githubusercontent.com/26493496/183215350-de8c8365-3dcd-4b97-90ff-06d525ef94d5.png)
I will do a full rescan as soon as the new version will be released because it takes several hours.

**Comment by tacruc** [comment]
OK I will try to publish a New release soon, but I don't make it this week.
