### ISSUE TITLE
Federated maps/lists?

### ISSUE THREAD

**Issue by eyduh** [nextcloud/maps#673]
Hi,
I've got a shared project with someone else with their own nextcloud server.
We use a shared folder in Files and would like to collaboratively make a favourites and a contacts map based on a spread sheet in out folder.
Automating the process would be great but would merely like to edit a list collectively, is this possible? I can only find the sharing option to make a public read only view.

**Comment by tacruc** [comment]
If I understood you correctly this is currently under development You can try the 0.2.5 nightly builds.
