### ISSUE TITLE
Maps can not be installed.

### ISSUE THREAD

**Issue by dschinni** [nextcloud/maps#68]
#### Nextcloud

Version: 16.0.3.0

#### PHP

Version: 7.2.12

#### Database

Type: mysql

Version: 10.3.9

#### Description

We tried to install the Maps app on our NextCloud. We have loaded the current version from the master branch and assembled it according to instructions. That went well too. Unfortunately, the installation aborts with the following error message:

An exception occurred while executing 'CREATE TABLE oc_maps_address_geo (id BIGINT AUTO_INCREMENT NOT NULL, adr VARCHAR(255) NOT NULL, adr_norm VARCHAR(255) NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, looked_up TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_4C2424AB9CEC6B64C4BE9D6 (adr, adr_norm)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key

Can someone help us?

**Comment by eneiluj** [comment]
From which git branch are you trying to install the app? What DB system are you using? (MariaDB, MySQL, Postgre etc...)

**Comment by mikweb2017** [comment]
I have same Problem
Nextcloud

Version: 16.0.3.0
PHP

Version: 7.3.7
Database

Type: mysql

 Server: Localhost via UNIX socket
Server-Typ: MySQL
Server-Verbindung: SSL wird nicht verwendet Dokumentation
Server-Version: 5.7.27-0ubuntu0.16.04.1 - (Ubuntu)
Protokoll-Version: 10 


[settings] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_maps_address_geo (id BIGINT AUTO_INCREMENT NOT NULL, adr VARCHAR(255) NOT NULL, adr_norm VARCHAR(255) NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, looked_up TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_4C2424AB9CEC6B64C4BE9D6 (adr, adr_norm)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':

SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key at <<closure>>

 0. /var/www/vhosts/cloud.mikweb.eu/httpdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 184
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... y", Doctrine\DBAL\Dr ... "})
 1. /var/www/vhosts/cloud.mikweb.eu/httpdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 158
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... "}, "An exception oc ... y")
 2. /var/www/vhosts/cloud.mikweb.eu/httpdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1037
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... "}, "CREATE TABLE oc ... d")
 3. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/DB/Migrator.php line 260
    Doctrine\DBAL\Connection->query("CREATE TABLE oc ... d")
 4. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/DB/Migrator.php line 83
    OC\DB\Migrator->applySchema(Doctrine\DBAL\Schema\Schema {})
 5. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/DB/Connection.php line 453
    OC\DB\Migrator->migrate(Doctrine\DBAL\Schema\Schema {})
 6. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/DB/MigrationService.php line 483
    OC\DB\Connection->migrateToSchema(Doctrine\DBAL\Schema\Schema {})
 7. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/DB/MigrationService.php line 411
    OC\DB\MigrationService->executeStep("000009Date20190516000800", false)
 8. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/Installer.php line 141
    OC\DB\MigrationService->migrate()
 9. /var/www/vhosts/cloud.mikweb.eu/httpdocs/settings/Controller/AppSettingsController.php line 447
    OC\Installer->installApp("maps")
10. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 166
    OC\Settings\Controller\AppSettingsController->enableApps(["maps"], [])
11. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "enableApps")
12. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "enableApps")
13. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Settings\\C ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
14. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
15. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
16. /var/www/vhosts/cloud.mikweb.eu/httpdocs/lib/base.php line 975
    OC\Route\Router->match("/settings/apps/enable")
17. /var/www/vhosts/cloud.mikweb.eu/httpdocs/index.php line 42
    OC::handleRequest()

POST /index.php/settings/apps/enable
from 192.166.200.216 by mikweb2014 at 2019-08-08T12:22:34+00:00

**Comment by eneiluj** [comment]
I guess you're installing from master branch.

The problem you're facing was solved in @rework-eneiluj.

**Comment by mikweb2017** [comment]
work  for me tanks.
last question there is a command to scan all the photos I have not found a way to do it

**Comment by eneiluj** [comment]
Assuming you're authorized to become the webserver user and this user is www-data:

```
cd /var/www/.../nextcloud
sudo -u www-data php ./occ maps:scan-photos
```

Add a username after the command to restrict the scan to this user.

**Comment by mikweb2017** [comment]
Thanks  Great Job i love this App

**Comment by dschinni** [comment]
Seems to work. Thank you

**Comment by eneiluj** [comment]
You're welcome. Thanks for your enthusiasm. Don't hesitate to throw your remarks and criticisms.
