### ISSUE TITLE
Photos are not displayed on the map

### ISSUE THREAD

**Issue by Andy-1970** [nextcloud/maps#684]
Hello
I know this problem is boomerang through various forums. The problem is probably the differences in the PHP version. There is really no solution to this?
I have 57K photos. The Maps application also sees that much, but does not display any.
I have the following error in my logs. Sometimes a STR To INT conversion error occurred.
Required parameter $end follows optional parameter $categoryList at /var/www/html/custom_apps/maps/lib/Controller/FavoritesController.php#216

Nextcloud HUB II 23.0.0
PHP 8.0.13

**Comment by umgfoin** [comment]
Hi @Andy-1970,
maps is not PHP 8 ready, yet.
Unfortunately, dependency requirements are not set correctly in the app-manifest, thus it doesn't deactivate, if PHP8 is found during an upgrade/ install.
++umgfoin.

**Comment by hajo62** [comment]
I'm using NC v22.2.5 docker version and also do not see photos displayed in the map.
And I would expect the images is build with the correct php version.

**Comment by tacruc** [comment]
Could you check if v0.2.0-1-nightly solves the Issue.
It can be installed by
occ app:install maps --allow-unstable
or updated
occ app:update maps --allow-unstable

**Comment by artemanufrij** [comment]
Same here. Photos are not visible on Nextcloud running on docker (official docker-compose.yml). Same photos are visible on native installed Nextcloud-instance.

**Comment by artemanufrij** [comment]
I guess something like `exiftool` is not available on the docker image.

**Comment by hajo62** [comment]
Hhm, maybe number of photos? 
- I serve around 35 k images
System used to serve the container?
- I run on a Pi4 with 8GB and a 1TB ssd

Checked PHP Version in the container: PHP 8.0.23

**Comment by nousernameavailableanymore** [comment]
I have a similar issue here.
Hower, I use PHP8.1 on Ubuntu 20.04 LTS.

For me, I do not even get a number count on "my photos" in the maps app.
However, my contacts are correctly shown on the map.

Is there any eta when this will be fixed for the versions of PHP 8.0 and 8.1 which are officially supported by Nextcloud?

**Comment by bilibilistack** [comment]
Same thing here. After I convert my db from mariadb to postgresql14, no photos show up (Before it works but took 30s to load 60k+ photos on map). I use apache:stable docker image.
I tried to reinstall the maps, drop all the oc_maps_* tables in db and also cleaned oc_migration table. After I reinstalled the maps and run the scan command, I could find all 60k+ photos in the oc_maps_photos db.
But no photo is displayed on the map, neither count of photos. I could see db and apache used a lot of CPU for around 20s but nothing was out in the end. No error in the log file.
What can I do next?   

nextcloud:24.0.5  (apache:stable)
maps:0.2.1
php: 8.0.23
pgsql: PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by bilibilistack** [comment]
Update: I converted db back to mariadb using db:convert-type mysql and the photos appear on the map successfully!
I think there should be some bug with pgsql.

**Comment by hajo62** [comment]
I run 
 **mariadb**  Ver 15.1 Distrib 10.7.3-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2
and don't see images on the map.

@bilibilistack: Which version of mariadb are you running? I assume on docker?

**Comment by bilibilistack** [comment]
> 

Yes. docker pull mariadb.  I am on 10.9.2 (latest should be 10.9.3)
I saw a post suggesting migrating to psgsql with faster speed, that's why I want to move to psgsql.
I tried psgsql, it's generally faster than mariadb, especially on the gallery page and search tool bar. Also it feels like the settings page loading speed is faster. It could be anecdotal but u can have a try.

**Comment by Praetorian1410** [comment]
I also have this issue with media stored on an external hdd and mounted via a docker volume:
- Raspberry Pi 4 8gb
- NC 25.0.1
- MariaDB: 10.9.4 (I have never used psgsql before)
- PHP: 8.1.12

**Comment by Andy-1970** [comment]
It installs subsequent versions, but since I reported it never worked. I don't want to believe that anyone's photos are displayed on maps.

Docker latest image.
NX Hub 3 25.0.0.2
PHP 8.1.13
Linux 5.10.0-0.bpo.9-amd64 x86_64
Intel(R) Core(TM) i5-7400 CPU

**Comment by artemanufrij** [comment]
@Andy-1970 can you double check, if your cron job is running, please.

**Comment by artemanufrij** [comment]
@Andy-1970 
here is my line `crontab` on my host machine.
```bash
*/5 *  *  *  * root docker exec -u www-data -t nextcloud-app-1 php -f /var/www/html/cron.php
```

**Comment by Andy-1970** [comment]
I checked this at the beginning. Cron is running.

**Comment by tacruc** [comment]
@Andy-1970 could you provide some photos which you expect to be shown? You can also just email them of you don't want to share them publicly.

**Comment by Andy-1970** [comment]
Of course, I can send you some examples. In the library I have photos from various cameras, where there was no GeoTag, I added them manually in geosetter.
Currently testing the memories app. Everything displays correctly there.

**Comment by tacruc** [comment]
@Andy-1970 can you mail me or send me a message somewhere, then I will send you a link, where you can upload photos.

And would it be fine for you, if I publish a (1x1 pixel) downscaled version of the provided Photos in this repository? (The 1 pixel would still include all metadata.)

**Comment by tacruc** [comment]
@QazCetelic  @arkhi   Thanks for the Feedback
