### ISSUE TITLE
cluster photo

### ISSUE THREAD

**Issue by mikweb2017** [nextcloud/maps#69]
interesting would be the possibility the photos that form a cluster example a radius of 20 km would open on a list at the moment need to click each of the photos to watch them

**Comment by jancborchardt** [comment]
@mikweb2017 could you describe what you mean in further detail, ideally with screenshots or examples of how others do it? Currently when you click on a cluster, the cluster will "open up" and show the individual elements.

**Comment by mikweb2017** [comment]
depending on the factor 
![Bildschirmfoto 2019-08-28 um 06 23 45](https://user-images.githubusercontent.com/30271757/63826033-5f541c00-c95d-11e9-9080-bd88fb874749.png)
Zoom by clicking on the cluster you could open a new window with the lists of the photos in question larger and the zoom is larger and the more the cluster is more selective

**Comment by jancborchardt** [comment]
> the same principle as Photos for Mac OS and iOS also Android offers a similar feature

Could you show a screenshot of that? Like they do offer this from a maps view?

**Comment by mikweb2017** [comment]
MacOS
![Bildschirmfoto 2019-08-28 um 17 29 09](https://user-images.githubusercontent.com/30271757/63870936-42e6cc80-c9bb-11e9-8d1e-e05606c95445.png)

Android
![Bildschirmfoto 2019-08-28 um 17 39 50](https://user-images.githubusercontent.com/30271757/63870952-4a0dda80-c9bb-11e9-96a9-3a6eb1720366.png)

**Comment by jancborchardt** [comment]
Ah ok, so when you click on a cluster it basically opens the photo grid view.

So the difference here is that in the macOS and Android case, the map is a view of the photo app. In our case it’s mainly a Maps app. So I would say the preferred method is actually on click to show a Viewer, just like if you open a photo in Files. And the way the cluster is expanded right now is also kinda ok, and when you zoom in they show at the specific places.

The solution you propose

> by clicking on the cluster you could open a new window with the lists of the photos in question

definitely sounds good, but it seems like a step for the future and not the default behavior. :)

**Comment by tacruc** [comment]
I will close this, as you can now use the viewer to scroll though the pictures. 
Reopen if you think the grid view is still missing.
