### ISSUE TITLE
Share Map with external users, selecting specific folder/files to share only

### ISSUE THREAD

**Issue by CrypticMetaphor** [nextcloud/maps#695]
[Feature Request]

The ability to have 'other' maps that can be shared with other Nextcloud users OR users with access to an external link (+optional password protected link).

These **other** maps should have the option to pick what folders are scanned/displayed as the source files, the user should then have the ability to tick/untick the folders if they want to see specific photos (year/month for example). 

An example use case is photos uploaded by multiple users using a [Nextcloud file-drop](https://nextcloud.com/file-drop/) who can then see the photos displayed on the map (i.e. group holiday users).

**Comment by tacruc** [comment]
There is something in this direction in development in the nextgovhackathon-master branch. Testers and feedback is welcome.

**Comment by CrypticMetaphor** [comment]
I'd be happy to help test. I have very limited programming knowledge but
will be willing to test as an end user.

**Comment by tacruc** [comment]
There are now nightly builds. You can install the  v0.2.5 nightly builds directly via OCC.
