### ISSUE TITLE
[I18N] Clarity suggestion for text and hotkey

### ISSUE THREAD

**Issue by meskobalazs** [nextcloud/maps#717]
I have a suggestion for these two strings:

https://github.com/nextcloud/maps/blob/8458244fb1ff890fc0121d29bfc67ba8023be51b/src/components/map/HistoryControl.vue#L7
and
https://github.com/nextcloud/maps/blob/8458244fb1ff890fc0121d29bfc67ba8023be51b/src/components/map/HistoryControl.vue#L13

This seems an unusual syntax for `Ctrl+Z` and `Ctrl+Shift+Z`, usually we don't distinguish between small and large caps in hotkeys/shortcuts. Also I suggest renaming `Cancel` to `Undo`, as that is the usual label.

**Comment by tacruc** [comment]
@meskobalazs could you review #718?
