### ISSUE TITLE
Image viewer freezes / endless loading

### ISSUE THREAD

**Issue by eibex** [nextcloud/maps#728]
When selecting a group of pictures on the map, the image viewer opens and loads the first image.
Then two things can happen if you switch to the next image in the group:
- Nextcloud loads endlessly and all buttons become unresponsive
- You need to press the right arrow key **twice** to actually go forward, if you only press it once the loading circle will appear and stay forever

In the first example this is the error in the browser console (no Nextcloud log error):
![image](https://user-images.githubusercontent.com/40539455/165286650-0e131676-1f9b-44a4-8a35-970ebfcdb263.png)

The second example, no error is produced in the console and/or Nextcloud logs.

Versions:
- Chrome v100.0.4896.127
- Nextcloud 23.0.4
- PHP 7.4
- Apache/2.4.53
- Ubuntu 20.04

**Comment by tacruc** [comment]
We have a reimplemented the entire front-end in v0.2.0.
If the Issue still exits in the new implementation, feel free to reopen this this.

**Comment by eibex** [comment]
I cannot reproduce the error anymore, but I can always reproduce the error-less necessity of having to click/arrow key twice to actually go forward (first key press is endless loading, the next actually brings up the next image).
