### ISSUE TITLE
Release 24

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#732]
Lets Collect here, whats needs to be done for a NC24 release.

PR's, which need reviews:
Just bug fix:
- [x] #727 
- [x] #705 
- [x] #709
- [x] #718 
- [x] #737 
- [x] #740 
- [ ] #767

Minor but significant improvements, as they reduce impact of bugs:
- [x] #704 
- [ ] #724 
- [x] #725
- [x] #726
- [x] #703 

Issues:
- [x] #738 
- [ ] #735 

ToDo:
- [x] Bump version number in package.json and app.xml
- [x] Write Changelog
- [x] Set final date in changelog
- [x] Call for testers before final release

**Comment by tacruc** [comment]
@szaimen We have already the second nightly version. There is only one CSS issue reported, so maybe it is time to call for some testers, via social media. What do you think?

**Comment by szaimen** [comment]
> @szaimen We have already the second nightly version. There is only one CSS issue reported, so maybe it is time to call for some testers, via social media. What do you think?

very cool! yes that sounds like a good idea! :)
cc @jospoortvliet
