### ISSUE TITLE
Photos show up at wrong locations after update

### ISSUE THREAD

**Issue by nougatbyte** [nextcloud/maps#736]
Hi, 

I installed the current master branch in my nextcloud instance and started a metadata scan after. Everything seemed to work fine.

Now I noticed that all photos end up at the wrong coordinates on the map. I am sure they were in the correct place before the update. Single photos that were in clusters before are now all over the place, placement seems totally random to me.
GPX Files on the other hand seem to still be placed correctly.

Nextcloud Version is 23.0.5

**Comment by aPollO2k** [comment]
Same for me. But i happens only for some photos. The most photos will shown with correct coordinates.

**Comment by tacruc** [comment]
Hi,
@nougatbyte thanks for reporting this issue and @aPollO2k for confirming this. To fix this Issue sample images would be extremely helpful. 
You can post them here, or mail them to me directly. 
I wanted to create an automatised for this in the near future, therefore it would be appreciated if you would allow me to include the sample within this repository.
Best

**Comment by nougatbyte** [comment]
Hi @tacruc,

here is an example image you can also use in the repo:
![PXL_20220526_113755755](https://user-images.githubusercontent.com/10289439/170993013-e1214a01-2350-4a4f-8929-180379e5b3b3.jpg)

The (correct) metadata says its located here: https://www.google.de/maps/place/48%C2%B042'15.5%22N+8%C2%B025'06.5%22E/@48.7043,8.4162813,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x19559e2ee980fe02!8m2!3d48.7043!4d8.41847

On the nextcloud map its more like 49.13310537905709, 8.597468062328321 (not 100% accurate)

kind regards

**Comment by tacruc** [comment]
#737 should solve your issue. Can you confirm?
