### ISSUE TITLE
Some GPX Tracks not visible

### ISSUE THREAD

**Issue by nougatbyte** [nextcloud/maps#738]
Some GPX tracks dont get rendered on the map even when enabled.

Example GPX File that doesnt work: https://github.com/gps-touring/sample-gpx/blob/master/RoscoffCoastal/1_Roscoff_Morlaix_A_parcours.gpx

Example GPX File that works:
[working.zip](https://github.com/nextcloud/maps/files/8818358/working.zip)

like in my last issue, I‘m pretty sure this worked on an older version.

**Comment by tacruc** [comment]
Could you confirm that the track is shown, if the time slider is disabled?

**Comment by nougatbyte** [comment]
@tacruc can you please tell me where to find the timeslider? The nearest thing I could find was the elevation display.

**Comment by tacruc** [comment]
In the navigation sidebar at the buttom under settings. (Lower left corner)

**Comment by nougatbyte** [comment]
If the time slider is disabled I can only see the start point of the gpx track.
If the slider is enabled the point disappears.

Expected behaviour would be the rendering of the track like in gpsvisualizer.com:
![image](https://user-images.githubusercontent.com/10289439/171608378-5c956640-8b5f-4b4e-8e53-901d25aef06f.png)

**Comment by tacruc** [comment]
I'm confused.
Are you still talking about the master branch or about the changes in #739?
I would suggest that we discuss the original issue here and the changes in the pull request.

**Comment by nougatbyte** [comment]
Sorry, I had no time checking out this pull request - everything I described until now was on the master branch from a few days ago.

I will try to write a more detailed answer this evening.

**Comment by nougatbyte** [comment]
I was now able to test the branch.
Sadly it doesnt seem to fix the issue. 
Screenshots of how it looks for me:
![1](https://user-images.githubusercontent.com/10289439/171828172-70801e20-bd6c-4d4a-b763-9b293df1f497.jpg)
![2](https://user-images.githubusercontent.com/10289439/171828167-32a911d7-3f01-407a-9737-65cdf687d021.jpg)

In the first image the starting point of the track is visible but not its trackpoints like in the example in https://github.com/nextcloud/maps/issues/738#issuecomment-1144689817

**Comment by tacruc** [comment]
After changing the branch did you rebuild the js code by running:
`npm ci`?

**Comment by tacruc** [comment]
Hm interesting, I have serious problems to reproduce this with the AllwaysShowTracksWithoutTimestamps branch:
![image](https://user-images.githubusercontent.com/402891/172382807-8a85ce86-cb72-4d6d-b13e-b80738c1c4d8.png)
![image](https://user-images.githubusercontent.com/402891/172382903-da4f96f8-c886-4894-acd9-5a2dba7fcbac.png)
While I have the behavior from https://github.com/nextcloud/maps/issues/738#issuecomment-1145778849 with master.
Could you try `npm run watch` additionally?

**Comment by nougatbyte** [comment]
Nice! It works with npm run watch. As I understand it run watch should do the same just with hot reloading right?
Is there any way I could have cleared any caches to instantly see changes?
