### ISSUE TITLE
Color of contact groups is non-standard, not reflected anywhere on map

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#74]
Just saw this coloring of the Contact groups in the navigation:
![contact group coloring is not reflected and maybe not useful](https://user-images.githubusercontent.com/925062/63699153-9375f280-c820-11e9-815e-cd9f48b13b0f.png)

Some issues here:
- This is not used anywhere else, like in the Contacts app
- It’s not reflected anywhere on the map, at least as far as I can see
- We already use color for favorites, and that is already enough

I would say we remove the individual coloring of groups? What do you think @nextcloud/maps

**Comment by eneiluj** [comment]
Yep right. I just added it while thinking it might be useful later and didn't find any use for it...

What do you think of using NC instance main theming color for those group icons? I pushed it to `rework-eneiluj` branch if you want to try it.

**Comment by jancborchardt** [comment]
> What do you think of using NC instance main theming color for those group icons? I pushed it to rework-eneiluj branch if you want to try it.

Color should always have a meaning and be used sparingly – mostly for primary actions. For favorites it’s nice, and kind of a standard. But for the contacts we don’t need it. :)

**Comment by jancborchardt** [comment]
Fixed in https://github.com/nextcloud/maps/pull/75
