### ISSUE TITLE
Small Bug  app.php deprecated error message

### ISSUE THREAD

**Issue by yupthatguy** [nextcloud/maps#765]
Hey there...

cool app... just doing some maintenance and I get the error message below about app.php being deprecated:
{"reqId":"Yp5jTCiyfiKpNVlxG1xtzwAAFR4","level":0,"time":"June 06, 2022 20:27:56","remoteAddr":"192.168.61.1","user":"fathertimetest","app":"maps","method":"GET","url":"/ocs/v2.php/core/navigation/apps?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":"24.0.1.1"}

Other than this.. things seem to be working fine,

I am on NC 24, Ubuntu 20.04 and php7.4-fpm

**Comment by tacruc** [comment]
Thanks for reporting, there is already a patch #703.
