### ISSUE TITLE
Change the favicon to the app icon

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [nextcloud/maps#769]
The Maps favicon is the default Nextcloud favicon, where it could or should display as the app icon. I attached an image of another app, Contacts, which uses the app icon as the favicon. Thank you.
![Screenshot from 2022-06-17 04-19-36](https://user-images.githubusercontent.com/76442625/174218267-6b6cb193-3a98-4230-9676-4db005eb4c34.png)

**Comment by tacruc** [comment]
For Firefox it's working, which browser and maps version are you using?

**Comment by Thovi98** [comment]
I’ve a similar issue reported in https://github.com/nextcloud/maps/issues/533.

- My current browser is Firefox 101.0.1 (64 bit)
- Maps 0.1.10
- Nextcloud 23.0.4

**Comment by tacruc** [comment]
@julien-nc do you know how to fix this?

**Comment by martenwa** [comment]
@tacruc For clarification: Are you talking about a backport? Because as far as I can tell, the reporters are using Bronze Age versions of both Nextcloud and Maps.

**Comment by tacruc** [comment]
@martenwa  your right its working. 
![image](https://user-images.githubusercontent.com/402891/226143993-14705f03-8e7d-406d-b236-8b06d434785c.png)
