### ISSUE TITLE
GPX file import is broken

### ISSUE THREAD

**Issue by anaqreon** [nextcloud/maps#77]
When I try to import GPX files (from the Files app), I receive a `Track /path/to/track.gpx was not found` notification. There are no errors in the `data/nextcloud.log` file. 

When I revert to commit 3e3d461ccf59ca15853193eca05afa9af93b66ac I can import GPX files, but when I checkout 3e3d461ccf59ca15853193eca05afa9af93b66ac it is broken. Somewhere between 08/09 and 08/16 it looks like the GPX file import broke.

_Originally posted by @anaqreon in https://github.com/nextcloud/maps/pull/76#issuecomment-525547870_

**Comment by eneiluj** [comment]
Could you try it again after pulling master branch?

It might be related with "endswith" declaration problem which was solved at 7a78eaa7b4d2a29a78824f86c0ff3a831257c7a0 (after 3e3d461).

**Comment by eneiluj** [comment]
I just merged rework-eneiluj (with the fix) a few minutes ago. I should have been more explicit :wink:. Could you try with latest master commit?

**Comment by eneiluj** [comment]
Btw, thanks a looooot for your reactivity :rocket:

**Comment by eneiluj** [comment]
Oh crap, it seems the file hooks are not triggered anymore. I'm on it.

Could you describe more precisely what does not work? Do you mean when you add a gpx file in your Nextcloud files you can't find it in the track list in Maps?

**Comment by eneiluj** [comment]
My fault, I removed something I thought useless in info.xml and it broke the hooks...

It's now back and it works.

Could you try `fix-hooks` branch? You might need to disable and re-enable the app.

**Comment by jancborchardt** [comment]
This was fixed by https://github.com/nextcloud/maps/pull/78 as far as I could test – @anaqreon can you confirm?

**Comment by anaqreon** [comment]
GPX file import works now, as of commit 66cbc6e3cdb1c59740b693609e19b160f35d0412. 

By the way, [I tweaked my Docker-based dev/testing environment to allow specifying a specific Maps app commit hash](https://github.com/anaqreon/nextcloud-maps-dev/commit/a48df0dd44b0e531e18b3c6f0ae9bf62b3152384), making tests of things like this straightforward and reproducible.
