### ISSUE TITLE
l10n: Remove forward slash in directory name

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/maps#772]
I suggest changing the directory name in the "/ Maps" messages to "Maps" because the forward slash sign tells the user to put the directory in "Maps".

```
/Maps is not a directory
/Maps is not writeable
Impossible to create /Maps
```

These text strings are also found in the files `DevicesController.php`, `FavoritesController.php` and `RoutingController.php`.

**Comment by tacruc** [comment]
Wouldn't that be the case is / in the end of the sting.
Like this it is just giving the full path, or?

**Comment by Valdnet** [comment]
Yes. You're right 👍.

I think I can close the issue 😉.
