### ISSUE TITLE
Please help making the map offline

### ISSUE THREAD

**Issue by SinaBina** [nextcloud/maps#774]
Hi
I am currently hosting my own tile server using openstreetmap in an offline environment inside Linux server which also host nextcloud 24.
I plan to use the tile server inside "Map" add-on, instead of online server.
Any comments on how to do that? is there any specific URL inside the code which should be replaced? for example:

http:/arcgis.com/tile/4/3/2/3.png to http:/127.0.0.1/tile/4/3/2/3.png

Thanks

**Comment by maximilianovermeyer** [comment]
This feature is already requested here: #83
