### ISSUE TITLE
CSS errors

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/maps#775]
@tacruc While testing 0.2.0-2-nightly, I noticed the following errors:

1. The side menu icon moves to the search window.

![obraz](https://user-images.githubusercontent.com/47037905/176680708-6fa86f42-d276-499b-8e9f-ff03e50b8d1c.png)

2. The frame of the map menu should contain an automatic serance for displaying text strings. With longer text displayed, it is broken, which doesn't look very much.

![obraz](https://user-images.githubusercontent.com/47037905/176680823-366729d3-2d0e-435f-80ab-1d93c3f0655b.png)

3. There are four black points in the app settings.

![obraz](https://user-images.githubusercontent.com/47037905/176679000-28fa7f58-16d0-4864-a1fd-426c83f06219.png)

Apps:
Nextcloud 24.0.2
Maps 0.2.0-2-nightly
Firefox 102.0

**Comment by tacruc** [comment]
#1005
