### ISSUE TITLE
Mapbox tiles are not moved

### ISSUE THREAD

**Issue by Doppellhelix** [nextcloud/maps#786]
Hello all.

I just updated the map to version 0.2.0 on my Nextcloud 24.0.2 (php 8.0.21).

Now when I move the map (street map) with the mouse, the map stops and I only move the pictures, contacts or routes.
It looks like I move all layers above the map.

Can anyone confirm this?

Greeting Helix

**Comment by BWibo** [comment]
Yes, I can confirm this:

False postion after dragging the map:
![grafik](https://user-images.githubusercontent.com/7643434/179703048-d0206698-8743-48e3-8bf7-ac2585bd2b26.png)

Correct position after zoom change and no drag afterwards:
![grafik](https://user-images.githubusercontent.com/7643434/179703175-6674329d-3bf9-4e82-8a5a-8b607a36b895.png)

I'm running Nextcloud 24.0.2 and Maps 0.2.0.

**Comment by tacruc** [comment]
It looks, like both of you are using the mapbox tiles. Does the issue occur, tiles, too?

**Comment by BWibo** [comment]
@tacruc I just removed the Mapbox API key from settings and tested again. I can confirm that the error is gone and enverything works much more fluently too.

**Comment by Doppellhelix** [comment]
> @tacruc I just removed the Mapbox API key from settings and tested again. I can confirm that the error is gone and everything works much more fluently too. When I tested the thumbs for images were not showing, bit this is probably not related to the dragging issue.

yes, I can confirm that.
Mapbox API removed and all is well.

**Comment by tacruc** [comment]
@eneiluj Could you have a look? I can reproduce this error. For me the layer moves a little and then jumps back.

**Comment by tacruc** [comment]
#798 solves the Issue for me, can you confirm this?
