### ISSUE TITLE
405 Method Not Allowed error on getOptionsValues call after upgrade to 0.2.0, app fails to load

### ISSUE THREAD

**Issue by aaronsegura** [nextcloud/maps#787]
I just upgraded maps to 0.2.0 and now the interface won't load.  I get the Nextcloud app icon bar across the top of the page, but the main portion of the page where the map should load is now empty.

In the browser console, I see a 405 Method Not Allowed error when attempting `GET /apps/maps/getOptionsValues`

I see nothing relevant in the nextcloud.log.

I am running Nextcloud v23.0.6.

Please advise if I can provide more information to help resolve this.  

Thanks in advance for your time.

![image](https://user-images.githubusercontent.com/1391955/179884026-f637d386-e7d0-430d-9c0a-60789b7efa9b.png)

**Comment by aaronsegura** [comment]
Does anyone have any suggestions on this one?  I use the maps app pretty often, and would like to get it working again.

**Comment by tacruc** [comment]
Sorry, never have seen this error. What does the nc codesign say? Did you try removing and reenabling the app?

**Comment by aaronsegura** [comment]
@tacruc Thanks for your reply!  I hadn't tried removing and reinstalling the app, but now that I did, that seems to have done the trick.

Thanks again for your help :)
