### ISSUE TITLE
Opening Maps app Results in Blank Window

### ISSUE THREAD

**Issue by whiskeytangofoxy** [nextcloud/maps#790]
NC version: 23.0.1
Maps version: 0.2.0 (installed via apps page)

Maps was previously working fine for me. Not sure what has broken its functionality. Now, anytime I go to Maps, it opens a blank page. The NC titlebar is at the top still but the frame under it appears to not load at all, resulting in a big blank/gray area.

Browser console output (this repeats every few seconds)
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 3 background.js:1
    send moz-extension://c9155310-3890-4a47-8b41-5813f46bf3b2/background.js:1
```

Also tried viewing in Edge but had the same issue.

**Comment by tacruc** [comment]
Can you check the nextcloud signing status? 
Did you try removing and reinstalling the app`?
