### ISSUE TITLE
Time stamp is wrong when hovering over images

### ISSUE THREAD

**Issue by swarmalator** [nextcloud/maps#791]
![image](https://user-images.githubusercontent.com/37983210/180299899-5484f764-40ae-466a-9bbc-98a72d6dfd4f.png)
Order of magnitude fat-finger? all the dates are close to the the unix epoch after updating to 0.2.0

Time filter slider still works as expected.

**Comment by tacruc** [comment]
Probably missing a factor of 1000, when creating the label.

**Comment by HighWay777** [comment]
I have the same issue. Is there a way to fix it , or it will be fixed during the next update ?

**Comment by tacruc** [comment]
See PR.: #808
