### ISSUE TITLE
No photos on map

### ISSUE THREAD

**Issue by ad-tomsk** [nextcloud/maps#799]
Hi.
Help me please.
i send command
sudo -u www-data php /var/www/html/nextcloud/occ maps:scan-photos
![Screenshot_nasm1](https://user-images.githubusercontent.com/87646847/180921093-cf05d424-04b6-47e3-a7df-e89cc7773ce4.png)
Command completed successfully, 50k photos.
Photos do not appear on the map
![Screenshot_nasm2](https://user-images.githubusercontent.com/87646847/180921453-c8bc68e3-20b8-4eb1-b1e0-06eb397cddf0.png)
if I send a request to mariadb
![Screenshot_nm1](https://user-images.githubusercontent.com/87646847/180924499-80cff38d-b3e2-4c38-a06e-960757d5f067.png)

return nothing
if i download a photo from next cloud i see gps coordinates in properties
![Screenshot_nasm3](https://user-images.githubusercontent.com/87646847/180921896-eab6a9dd-659a-4a4b-9e9f-1814d432d52c.png)
what could be the problem?

System report:
Link: https://nas.3dkv.ru/s/mQXa8Ge5YWRfBtN
Password: HH3QpHatww

Thank you! Good luck!

**Comment by tacruc** [comment]
Is your cronjob running?
Then just wait.
maps:scan-photos only schedules the extraction process. The actual extraction is done later in a background job.

**Comment by ad-tomsk** [comment]
cron work.
I wait few month... No result

**Comment by ad-tomsk** [comment]
what should i include in cron?

**Comment by tacruc** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron

Which Verison of maps and nextcloud are you using?

**Comment by ad-tomsk** [comment]
Start with maps 0.2.0 Nextcloud 20.
Now maps 0.2.0 Nextcloud 24.0.3.
yesterday i upgrade ubuntu to 22.04, php to 8.0, nextcloud to 24.0.3 . but nothing helped.
Maybe a problem with the database? Somewhere once I met a long time ago that you need to add some kind of column.

**Comment by tacruc** [comment]
On maps v0.2.0 you can try
`sudo -u www-data php /var/www/html/nextcloud/occ maps:scan-photos --now`,
there are some memory leaks in used libraries, so this is expected to throw some out-of-memory issues after multiple thousands of photos. Anyhow it might be helpful for debugging.

**Comment by ad-tomsk** [comment]
Thank you, work.
how to enable this process to cron?

**Comment by tacruc** [comment]
Its all in
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron
