### ISSUE TITLE
Cleanup Javascript

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#8]
(Reopening your issue here @Henni cc @v1r0x  :)

[script.js](https://github.com/owncloud/maps/blob/master/js/script.js) currently has more than 1800 lines and most of the comments are code comments.

It should be cleaned up by:
- [ ] removing all code comments (we don't need them, thats what git is good for)
- [ ] adding real comments
  - [ ] every function should have its own documentation block-comment to explain what it does
  - [ ] skim the code for cryptic code segments and add line comments

**Comment by tacruc** [comment]
@jancborchardt  I guess the headline is always true :smiley:, but I guess it is referring to an old branch?

**Comment by jancborchardt** [comment]
Yep :D We can close it :tada:
