### ISSUE TITLE
GraphHopper routing option disappeared in v0.2.0

### ISSUE THREAD

**Issue by TimoWilken** [nextcloud/maps#800]
Hi, I've just upgraded to Nextcloud Maps v0.2.0 (on Nextcloud 24.0.3). I'm using Firefox 100.0.2 on Linux. The same problem occurs in Chromium 103.0.5060.134 on Linux.

I have a valid GraphHopper API key (on a free account), which I've given to NC Maps. Under the previous version of NC Maps, I could see the option to use GraphHopper when choosing a routing engine. This has now disappeared, and I see the following error in the browser console:

```
16:47:10.788 TypeError: No().Routing.graphHopper is not a function
    addRouter RoutingMachine.vue:267
    initRoutingControl RoutingMachine.vue:215
    initRouting RoutingMachine.vue:58
    created RoutingMachine.vue:52
    VueJS 40
vue.runtime.esm.js:1897:12
```

**Comment by StarSmasher44** [comment]
Same problem, looks like this will be a while ;)

**Comment by husmannm** [comment]
I really miss graphhopper. 
I'm on maps 0.2.1 now and graphhopper is not available. 
Since I'm using Maps for Hinking this is a problem, because at the moment there are only routes for cars.

**Comment by Aquariu** [comment]
The Graphhopper free plan is great for small family instance. Is there a specific technical reason the option is no longer there ?

**Comment by ant0nwax** [comment]
This project has unluckily no developer focus anymore... I think maps and routing will never work as good as a advertisement based solution, I would also like to use the Graphhopper Free Plan, and I see this:

![image](https://user-images.githubusercontent.com/33480652/222386290-2636aa52-f607-4579-879c-874c7470e7dd.png)
![image](https://user-images.githubusercontent.com/33480652/222386513-a1b4efd6-9379-4106-807c-1d87b330466d.png)
