### ISSUE TITLE
add to favorites from search does not work anymore

### ISSUE THREAD

**Issue by ebiagi** [nextcloud/maps#801]
Php 7.4
Nextcloud 24.0.3

searching an address from the search bar and trying to add the result to favorites it's not working anymore (neither the add contact address is), clicking on it doesn't trigger any action or
![Cattura](https://user-images.githubusercontent.com/58190975/181713604-5408f6e8-0898-40aa-aab0-abce1fb9c93f.PNG)

I've tried with a couple of browsers (firefox, chromium, librewolf) and disabling all privacy restrictions, I've also tried Edge with basic settings

**Comment by meierwitt** [comment]
Hi,

same here, PHP 7.4.3 and Nextcloud 24.0.4. Can't add an favorite to map, can't add new category.

Thanks, Frank

**Comment by odea** [comment]
Hi, same here, PHP 7.4.3, NC 24.0.5. Tried disable privacy addons in firefox. No javascript errors.
It's a major feature !
Thanks

**Comment by odea** [comment]
Hi, any update on this one ? It still doesn't work with maps 0.2.4, NC 25.0.2

**Comment by tacruc** [comment]
Can Anyone confirm that #933 fixes this Issue?

**Comment by odea** [comment]
Hi, Thanks ! but I edited the 3 files and still unable to add favorite from a search result.

**Comment by tacruc** [comment]
You will have to build the java script.
Something along the lines:
`npm ci`
`npm run build`
or 
`npm run watch`
to automatically rebuild the files, while developing.

**Comment by odea** [comment]
Hmm the thing is ... I'm not a good dev :) I stopped at C & PHP. I tried to install npm, tried npm ci but it can't find packages.json, I only have package-lock.json....I will fall into the rabbit hole if I go any further :)

**Comment by tacruc** [comment]
https://github.com/nextcloud/maps/releases/tag/v0.2.5-2-933-nightly

I created a nightly release with this.

**Comment by odea** [comment]
Thanks ! I tried to untar the .tar.gz in the apps folder, nextcloud updated it self automatically but I don't why but now a lot of things are missing : search bar, my favorites, etc.. did I missed something in the process ?

**Comment by odea** [comment]
I have those js errors :
`TypeError: Function.prototype.bind called on incompatible target
    easyButton easy-button.js:320
    initLayers Map.vue:774
    onMapReady Map.vue:434
    VueJS 4
    mounted LMap.js:354
    VueJS 9
    mounted LMap.js:342
    VueJS 13
    gw main.js:97
    restoreOptions optionsController.js:44
    promise callback*restoreOptions optionsController.js:41
    <anonymous> main.js:93
    EventListener.handleEvent* main.js:87
    <anonymous> main.js:94
    <anonymous> main.js:94
vue.runtime.esm.js:3049:16
    VueJS 7
    mounted LMap.js:354
    VueJS 9
    mounted LMap.js:342
    VueJS 13
    gw main.js:97
    restoreOptions optionsController.js:44
    (Asynchrone : promise callback)
    restoreOptions optionsController.js:41
    <anonyme> main.js:93
    (Asynchrone : EventListener.handleEvent)
    <anonyme> main.js:87
    <anonyme> main.js:94
    <anonyme> main.js:94
`

**Comment by tacruc** [comment]
Ok, found the Issue.
Apparently there is an incompatibility with the talk app. Both are loading different leaflet modules which seems to make problems.
You could test, when disabling the talk app. Otherwise this Issue has to be resolved first.

**Comment by odea** [comment]
Oh yeah indeed ! works like a charm now with talk disabled :) thanks !

**Comment by odea** [comment]
Maybe the initial issue was the talk app and not maps ?

**Comment by tacruc** [comment]
No it wasn't working, before the fix. And with the talk app incompatibility it's probably a shared responsibility.

**Comment by odea** [comment]
Thanks for your time !
