### ISSUE TITLE
Remove from map photos with GPS Latitude/Longitude null

### ISSUE THREAD

**Issue by adripo** [nextcloud/maps#806]
I have some photos on map at 0N,0W. I checked with ExifTool and found out that the GPS fields are present but have null values. I think this issue might be related to #671.

Can those with null values be excluded from the map?

Screenshots:

![image](https://user-images.githubusercontent.com/26493496/182005621-66fe6506-3115-4f90-b2d4-c14c8379a723.png)
![image](https://user-images.githubusercontent.com/26493496/182005636-e272991d-8e81-458f-8647-b0e3be5805ec.png)

**Comment by tacruc** [comment]
I had a brief look into the code. I think what is happing is that somewhere when saving stuff to the DB or reading form the DB null is converted to 0.

**Comment by tacruc** [comment]
Should be fixed by #811.
