### ISSUE TITLE
Wrong date on map tooltip-photo-date

### ISSUE THREAD

**Issue by adripo** [nextcloud/maps#807]
Hi, I am having an issue with the dates shown on the map tooltip. It is always somewhere close to 1970: 

<details>
<summary>image on map</summary>
<br>

![image](https://user-images.githubusercontent.com/26493496/182025140-0b28ed31-0e73-43aa-ac17-875d6dc0dcac.png)

</details>

The image date creation is correct if I search in the files details:

<details>
<summary>image details</summary>
<br>

![image](https://user-images.githubusercontent.com/26493496/182025170-942319c3-ad05-46a0-92b6-c0d7ce18fee9.png)

</details>

The time shown on the time filter slider is correct:

<details>
<summary>time slider</summary>
<br>

![image](https://user-images.githubusercontent.com/26493496/182025245-4dfa556a-9ad3-4bdd-8389-e92840751ca5.png)

</details>

**Comment by adripo** [comment]
More details:
- I am using NC23
- the date is not always the same. Sometimes is 17 January 1970, sometimes 20 January 1970, and the hours changes as well.

I see there are a few places where this is used:
https://github.com/nextcloud/maps/search?q=tooltip-photo-date

Maybe this operation is wrong:
https://github.com/nextcloud/maps/blob/master/src/nonLocalizedPhotosController.js#L183
Why the `*1000`?
Same here
https://github.com/nextcloud/maps/blob/master/src/photosController.js#L223
and here
https://github.com/nextcloud/maps/blob/master/src/photosController.js#L367

**Comment by tacruc** [comment]
The files you are looking at are out dated and going to be removed #724.

Anyhow I assume the reason for the wrong date is a factor of *1000 missing. This is due to the fact that we work with seconds since Jan 01 1970. (UTC), but the function converting the integer to a proper date string takes millisecond as input.
Therefore it needs a factor of 1000.

**Comment by tacruc** [comment]
https://github.com/nextcloud/maps/blob/f34c4bcdd3fcd821bc0d2c3ab2411d074ab01ca1/src/components/map/PhotosLayer.vue#L233

There is the factor of 1000 missing

**Comment by adripo** [comment]
Ok, I understand the issue. Thanks for solving it.
