### ISSUE TITLE
Version Number Mismatch 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/maps#810]
The version on the nc server under apps is different then the https://apps.nextcloud.com/apps/maps & https://github.com/nextcloud/maps/releases

![image](https://user-images.githubusercontent.com/59488153/182199008-15f383d8-72e7-4b99-875b-1120655851b8.png)

**Comment by tacruc** [comment]
Probably 0.1.10 is the lastes Version supported in your setup. You can check the info.XML and composer.json for dependencies oft 0.2.0 which are not fullfiled in your setup.
