### ISSUE TITLE
Unknown column 'date_created'

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#84]
After enabling the app on my bigger server (20 users) 1.5 TB of pictures I found the following error in the log:

```
[index] Error: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `id`, `name`, `date_created`, `date_modified`, `lat`, `lng`, `category`, `comment`, `extensions` FROM `oc_maps_favorites` `f` WHERE `user_id` = ?' with params ["arne"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date_created' in 'field list' at <<closure>>

 0. /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... '", Doctrine\DBAL\Dr ... ]})
 1. /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... '")
 2. /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 911
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT `id`, `n ... ?", {1: "arne"})
 3. /srv/www/nextcloud/lib/private/DB/Connection.php line 195
    Doctrine\DBAL\Connection->executeQuery("SELECT `id`, `n ... ?", ["arne"], [2], null)
 4. /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 200
    OC\DB\Connection->executeQuery("SELECT `id`, `n ... 1", {dcValue1: "arne"}, {dcValue1: 2})
 5. /srv/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 214
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /srv/www/nextcloud/apps/maps/lib/Service/FavoritesService.php line 67
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /srv/www/nextcloud/apps/maps/lib/Controller/FavoritesController.php line 88
    OCA\Maps\Service\FavoritesService->getFavoritesFromDB("arne")
 8. /srv/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Maps\Controller\FavoritesController->getFavorites()
 9. /srv/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Maps\Control ... {}, "getFavorites")
10. /srv/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Maps\Control ... {}, "getFavorites")
11. /srv/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("FavoritesController", "getFavorites", OC\AppFramework\ ... {}, {_route: "maps.favorites.getFavorites"})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "maps.favorites.getFavorites"})
13. /srv/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "maps.favorites.getFavorites"})
14. /srv/www/nextcloud/lib/base.php line 1000
    OC\Route\Router->match("/apps/maps/favorites")
15. /srv/www/nextcloud/index.php line 42
    OC::handleRequest()

GET /apps/maps/favorites
from 138.232.236.7 by arne at 2019-08-29T16:36:11+02:00
```

**Comment by eneiluj** [comment]
Well the schema of `maps_favorites` table is quite clear and was not changed a lot. I wonder what could have happened. What kind of DB are you using? (mysql, sqlite etc..) Which version of Nextcloud?

**Comment by tacruc** [comment]
The activation actually took quite long, maybe there was some timeout while activating the app.
I have to drive home to check what was actually created in the database and if I can reproduce the error.

**Comment by eneiluj** [comment]
Well it shouldn't take long to install the app... Sorry for the dumb question but: Are you sure you're using the archive from releases?

**Comment by tacruc** [comment]
I hope:

```
 1011  2019-08-29 16:30:24 wget https://github.com/nextcloud/maps/releases/download/v0.1.0/maps-0.1.0.tar.gz
 1012  2019-08-29 16:30:40 tar -x maps
 1013  2019-08-29 16:30:56 tar -xf maps-0.1.0.tar.gz maps/
 1014  2019-08-29 16:30:58 ls
 1015  2019-08-29 16:31:01 ls -la
 1016  2019-08-29 16:31:15 sudo rm maps-0.1.0.tar.gz
 1017  2019-08-29 16:31:36 chown wwwrun:wwwrun maps/
```

but it might be a problem on my setup somewhere and might have nothing to do with the app.

**Comment by jancborchardt** [comment]
Getting the same here:
```

  | Doctrine\DBAL\Exception\InvalidFieldNameException: An  exception occurred while executing 'SELECT `id`, `name`,  `date_created`, `date_modified`, `lat`, `lng`, `category`, `comment`,  `extensions` FROM `oc_maps_favorites` `f` WHERE `user_id` = ?' with  params ["jan"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date_created' in  'field list'
-- | --



```

Which led to a notification "Could not load favorites" (or something sounding like that).

**Comment by eneiluj** [comment]
I need to know which kind of DB your setup uses. Maybe the creation of a column with this name is not authorized...but it should have been detected by the tests.

**Comment by jancborchardt** [comment]
Mine is MySQL – added more details also in the post above.

**Comment by tacruc** [comment]
Mine is MySQL, too

**Comment by eneiluj** [comment]
Well, we can try to make a new migration script which changes the table name. strange though.

Is it ok with you if i do this and produce a new archive?

**Comment by jancborchardt** [comment]
@eneiluj sure, it’s also fine if the first release is 0.1.1 :)

**Comment by eneiluj** [comment]
Yes, if we want to make it possible to all testers to get the new DB scheme, we have to produce a new version to trigger the migration script.

**Comment by jancborchardt** [comment]
(I mean, is it possible that the issue is that our private instances are so old that we actually used to have the _old_ Maps app enabled and this is a remnant from that?)

**Comment by eneiluj** [comment]
Well this is possible. Only way to find out: deploy a fresh NC install with Mysql and install Maps v0.1.0

**Comment by eneiluj** [comment]
I'll do that before struggling with migrations :grin:

**Comment by eneiluj** [comment]
It works with a fresh Nextcloud instance using MySQL. The column is there and there is no bug when loading favorites. I guess this is the downside of being a developper or a bleeding edge user :wink:. This is probably my fault because I might have edited a migration script instead of adding a new one.

Bottom line is: this problem won't affect people installing the app or those who have installed it after I made the change to the migration script. My guess is you two and maybe a couple of others are impacted. Not a problem for the release.

To solve the problem on your instances, you can delete the `map_*` tables and run each migration script manually... I'm sorry I can't help more about that.

**Comment by tacruc** [comment]
DB Tables:
![image](https://user-images.githubusercontent.com/402891/63953713-26619780-ca82-11e9-88a5-0eff2f65364d.png)
I guess we can delete maps_adress_cache?
![image](https://user-images.githubusercontent.com/402891/63953838-60cb3480-ca82-11e9-9751-3d137b78a7d3.png)

Do you recognize them from an old script?

**Comment by eneiluj** [comment]
Yes you can (and should) delete all `maps_*` tables.

**Comment by tacruc** [comment]
I'm working on that, will report when I'm done

**Comment by eneiluj** [comment]
I tried to do it on my MySQL test instance and `occ` told me to enable debug to be able to run previous migration script:

`Can not go back to previous migration without debug enabled`

**Comment by tacruc** [comment]
My thought was to delete the migration from the db delete and reinstall the app

**Comment by eneiluj** [comment]
@tacruc Yes you can also do that.

Ok my method worked: just enable debug in `config/config.php`: `'debug' => true,` and then run:

```
sudo -u www-data php7.3 occ migrations:execute maps 000008Date20190428142257
sudo -u www-data php7.3 occ migrations:execute maps 000009Date20190625000800
sudo -u www-data php7.3 occ migrations:execute maps 000012Date20190703155323
sudo -u www-data php7.3 occ migrations:execute maps 000012Date20190722184716
sudo -u www-data php7.3 occ migrations:execute maps 000013Date20190723185417
sudo -u www-data php7.3 occ migrations:execute maps 000014Date20190817184844
```

**Comment by jancborchardt** [comment]
@eneiluj so the step-by-step for someone who is afraid to mess up their installation is what exactly?
1. Remove app oc_maps_* tables
2. Enable debug in the config.php
3. do the occ migrations commands you list above exactly like that via copy-paste?

**Comment by tacruc** [comment]
For me 
0. disable the maps app and wait for bg jobs to finish
1. deleting the oc_maps_tables 
2. removing the maps migrations from oc_migrations table
3. removing the maps app folder
4. downloading the maps app folder
5. reinstalling the maps app
worked fine
