### ISSUE TITLE
Undefined index: FN 

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#85]
Second error:
`
 Undefined index: FN at /srv/www/nextcloud/apps/maps/lib/Controlle/ContactsController.php#101
`

**Comment by eneiluj** [comment]
Wow, I didn't know it was possible FN is not defined. Do you have a contact without name?

**Comment by tacruc** [comment]
It might well be, as I saved sum numbers in android without specifying a name, but I have to drive home and check the db for a exact answer.

**Comment by eneiluj** [comment]
Ok anyway the fix is quite easy.
