### ISSUE TITLE
Add option to create new favorites categories

### ISSUE THREAD

**Issue by meichthys** [nextcloud/maps#850]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**
A way to create new favorite categories.

**Describe alternatives you've considered**
Currently the only way I can find to create a new favorites list is to import a list and then remove all but one favorite from the category. Then add my new favorites, then remove the remaining favorite from the imported category. 

If I try to remove all favorites form the category before adding new favorites, then the category is auto-removed.

**Comment by tacruc** [comment]
The categories are generated form the favorities.
So currently they are just properties of favorites and don't exits without them.
As a consequence you can create categories by add a Favoriten to any including a new Categories.

**Comment by meichthys** [comment]
🤦‍♂️ Wow. Not sure how I missed that. Thanks!
