### ISSUE TITLE
[Bug]: NC 25 alignment  buttons issue 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/maps#853]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/59488153/189486400-06a659e2-8205-4ce5-95dd-a534ad57630f.png)

### Steps to reproduce

please see screenshot

### Expected behavior

Should be aligned

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by tacruc** [comment]
Duplicate
