### ISSUE TITLE
Feature Request: Share of favourites at maps with other nextcloud user

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/maps#854]
It would be nice if it would be possible to create folders or such for the favourites at maps.
And then share them with other users in nextcloud.
Also to allow other users to create their own favourites in the same folder if permitted or just readonly, so that it can be collaborative.

**Comment by tacruc** [comment]
Currently under development. You can test it in the #730 branch.

**Comment by potagerGit** [comment]
hello, would it be possible to share only One favorite Point or only the whole folder ? right now, I have a "mycategory" category for 10 favourites, and I can only share the category itself, not only one point out this category.  Maybe did I miss something ? 

Thanks for your help.

**Comment by BiglifeMatt** [comment]
I saw this as well as the Collaborative Maps request.  Is this nearing the next release and how soon might that be?

**Comment by MrLoverLoverMMMM** [comment]
any news?
I am also very excited when this will be avialable :)

**Comment by tacruc** [comment]
There is a first nightly release v.0.2.5-nightly testers are welcome

**Comment by tacruc** [comment]
Now you can create maps, which can contain favorites and can be shared with other users.
