### ISSUE TITLE
[Bug]: Trimed duplicate groups name while users are in multiple groups of Contacts

### ISSUE THREAD

**Issue by LogoSapienceDEV** [nextcloud/maps#855]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

While users are in more than one groups in Contacts, there is a bug : groups name are duplicate with a trimed name in the "My Contacts" list.
Exemple : 
User 1 : John Doe in Groups 'Numérique'  and 'Tous'
User 2 : Marta Doe in Group 'Numérique' 
User 3 : Jack Doe in Group 'Tous'

In Maps, filter of Groups are showing :
Numéque (1)
Numériqu (1)
Tous (1)
Tou (1)

Nextcloud : 24.0.5
Maps : 0..2.1

### Steps to reproduce

1. Create Users and Groups in "Contacts"
2. Link one user in two groups
3. Show Maps, "My contacts" is showing duplicate groups

### Expected behavior

In Maps "My contacts" we have to show unique groups name

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install of the server?

Fresh Nextcloud Server install

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.5.1",
        "default_phone_region": "FR",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "logtimezone": "Europe\/Paris",
        "maintenance": false,
        "theme": "",
        "skeletondirectory": "",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - bbb: 2.3.1
  - calendar: 3.5.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_antivirus: 3.3.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - group_everyone: 0.1.10
  - groupfolders: 12.0.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.8
  - maps: 0.2.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - side_menu: 2.5.1
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - user_usage_report: 1.8.0
  - viewer: 1.8.0
  - welcome: 1.0.1
  - workflowengine: 2.6.0
Disabled:
  - circles: 23.1.2
  - collectives: 1.5.0
  - deck: 1.7.1
  - federation: 1.14.0
  - files_external: 1.15.0
  - firstrunwizard: 2.13.0
  - music: 1.6.0
  - nextcloud_announcements: 1.13.0
  - registration: 1.5.0
  - richdocumentscode: 22.5.502
  - spreed: 14.0.4
  - support: 1.7.0
  - talked: 0.4.0
  - user_ldap
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by LogoSapienceDEV** [comment]
Hi,

It's come from maps/src/view/App.vue, in function buildContactGroups, line 974 : 
						const cGroups = c.GROUPS.split(/[^\\],/).map((name) => {
							return name.replace('\\,', ',')
						})

Exemple, if the contact have two groups : Numerique and Tous, c.GROUPS is the string Numerique,Tous.
With the regex /[^\\],/ the mapped array is :Array [ "Numeriqu", "Tous" ]

Why there is /[^\\],/  because /,/ is working good.

Thanks for update in next update.

**Comment by tacruc** [comment]
Hey @LogoSapienceDEV thanks for reporting and spotting the right places. I improved your regex to
I needed to adapt you fix in order to properly handle commas in the group name.
I think `/(?<!\\),/` should do.

Could you test #926 ?
