### ISSUE TITLE
[Bug]: GPX files does not show any longer

### ISSUE THREAD

**Issue by srednax** [nextcloud/maps#859]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I updated the maps app to latest version, and now my gpx files (tracks mainly) does not show on the map. It correctly zooms to the area containing the track data, but there is not line or markers.

### Steps to reproduce

1. Try to display a gpx file with a track in it
2.
3.

### Expected behavior

Track show on map

### Installation method

Web installer on a VPS or web space

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
This is too difficult, it requires changing settings on the host.
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by tacruc** [comment]
Can you provide an example gpx file, which isn't working?

**Comment by srednax** [comment]
tirsdag den 27. september 2022 19.26.11 CEST skrev Arne Hamann:
> Can you provide an example gpx file, which isn't working?

Sure, this one: https://alundnc.dynv6.net/index.php/s/RY4J4AS4xjjbHcZ

--
Kindly,
Anders

**Comment by srednax** [comment]
Any news on this? I updated nextcloud to 22.10, and still no tracks can be 
visible. The maps app zooms correctly (it looks like), but tracks are not 
drawn.

**Comment by srednax** [comment]
I just downloaded the "GPX Edit" app, and that one actually does draw the 
tracks. Btw, why not just make this functionality part of the maps app?

**Comment by srednax** [comment]
After editing a file in gpx editor and then saving it (to same location), it 
suddenly became visible in maps app as well.
The GPX edit app changed the GPX version (gpx xmlns) to 1.1, and added a 
global "metadata" section, which btw looks incorrect to me, since the data 
entered was for the track contained in the file - because the edit widget in 
the gpx edit app says "track name". However, both name and description are 
valid elements insidt the trk element, according to the spec.

Given the poor formatting of the gpx element of the edited file, it is 
difficult to understand the changes.

However, I do believe you should support valid gpx 1.0 files.

**Comment by srednax** [comment]
I created a gpx 1.1 file using my GPS Logger app on the phone, and uploaded it 
to nextcloud, but that one also does NOT work with the maps app. So somewhere 
in your code, there is an error. File enclosed.

**Comment by srednax** [comment]
https://alundnc.dynv6.net/index.php/s/Li4xYjTn9AJrAd7

**Comment by srednax** [comment]
Hi,

Any news on this? My nextcloud instance is up todate, running on 32 bit linux 
on a RPI 4, and I still can't see my GPX files.

Kindly,
Anders

tirsdag den 27. september 2022 19.26.11 CET skrev Arne Hamann:
> Can you provide an example gpx file, which isn't working?

**Comment by srednax** [comment]
I installed OpenTracks on my phone, and the gpx exported from that actually 
shows. Sample enclosed. They have horrible file names, and fill the gpx file 
with crap - but it does show in nc maps app.

It does not help me a lot, because all my trackss from recent years does not. 
They used to - so you must have changed something to a wrong state somewhere 
along the road.

Kindly,
Anders

tirsdag den 27. september 2022 19.26.11 CET skrev Arne Hamann:
> Can you provide an example gpx file, which isn't working?
