### ISSUE TITLE
[Bug]: Favorite icons on map are not visible but outlines of the icon are visible 

### ISSUE THREAD

**Issue by meichthys** [nextcloud/maps#866]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The favorite star icons on the map are there, but are transparent/not rendering:
![image](https://user-images.githubusercontent.com/10717998/194590404-33667b99-ed7a-4302-9f87-f9108390a6cc.png)

### Steps to reproduce

1. Open Maps
2. Add Favorite
3. Look for favorite on map

### Expected behavior

Favorite should show a nice little star :)
![image](https://user-images.githubusercontent.com/10717998/194590525-cccf8404-4b47-4254-be6d-33ec27332506.png)

### Installation method

Official VM scripts

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.0.0-alpha.1
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.0-rc.1
  - contactsinteraction: 1.6.0
  - cookbook: 0.9.15
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0-beta.2
  - drawio: 1.0.3
  - external: 4.1.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - files_antivirus: 3.3.1
  - files_automatedtagging: 1.15.0
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.13.2
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.0-beta.2
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.0-rc.1
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - occweb: 0.1.0
  - password_policy: 1.15.0
  - pdf_downloader: 1.0.6
  - photos: 1.7.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recognize: 3.0.0-beta.3
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 2.5.1
  - socialsharing_email: 2.5.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.4
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bookmarks_fulltextsearch: 1.2.0
  - bruteforcesettings: 2.4.0
  - encryption: 2.13.0
  - federation: 1.13.0
  - files_external: 1.15.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - user_ldap
```

### Additional info

Maps Version: 0.2.1
Nextcloud Version: 25rc3

**Comment by goldanorak** [comment]
Hello : same bug for me, since yesterday ! I'd like to point out that everything worked normally before. 
Nextcloud version 25.0.1
Maps version 0.2.1.
Firefox version 107.0
Linux Mint version 20.3
thanks !

**Comment by BernardS** [comment]
hi, same bug since NC fresh install 
NC version 25.0.1
Maps version 0.2.1
server OS Linux 5.4.0-125-generic x86_64 (VM)
merci
