### ISSUE TITLE
Feature Request Photos from external storage

### ISSUE THREAD

**Issue by derritter88** [nextcloud/maps#873]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Also read EXIF GPS data from external storages which are mounted within Nextcloud

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Cebrain** [comment]
Is this an active problem?
I dont know why, but for me some pictures appeared the first time after setting up, but many pictures was missing.
After running "./occ maps:scan-photos" all photos disappeared.

**Comment by derritter88** [comment]
Not sure if this is a problem.
I just recognized that Maps shows only photos from within Nextcloud local storage but not from any external mounts.

I will check your command and give a feedback.

**Comment by derritter88** [comment]
@Cebrain Your command seems to work as it scans also my external mounts but now I do not see any photos after all on my map - maybe too many photos?!

**Comment by Cebrain** [comment]
It is working again for me. One thing was i waited now 12 hours and the icons appears on the map.
Also my photo previews was broken and i fixed them, maybe this fixed the problem in general.

**Comment by dirk80** [comment]
It would be great to be able to upload pictures into maps from my computer which maps than stores somewhere within Nextcloud and showing the picture at the GPS data location.

**Comment by derritter88** [comment]
> It is working again for me. One thing was i waited now 12 hours and the icons appears on the map. Also my photo previews was broken and i fixed them, maybe this fixed the problem in general.

It also worked after your guide.

In general it would be cool if this job could be included in general cron.php and show the photos directly at maps without any delay

**Comment by Cebrain** [comment]
> In general it would be cool if this job could be included in general cron.php and show the photos directly at maps without any delay

Great that it is working again!
I think this would be a new feature request

**Comment by mkrohn** [comment]
It doesn't show the photos located on mounted external storage
