### ISSUE TITLE
[Bug]: Large error messages appear from time to time.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/maps#879]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

From time to time, i see this error message having a white background and being larger than screen:

> Failed to save option values:

Nextcloud

<div id="nojavascript">
<div>
See rakendus vajab toimimiseks JavaScripti. Palun <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">luba JavaScript</a> ning laadi see leht uuesti. </div>
</div>

Nextcloud

Serveri sisemine viga
Server ei suutnud sinu päringut lõpetada.
Kui see veel kord juhtub, saada tehnilised detailid allpool serveri administraatorile.
Lisainfot võib leida serveri logist.

Tehnilised andmed

Kaugaadress: 127.0.0.1
Päringu ID: 0mIxqv1F2PrJbRTNEoXA

Nextcloud – turvaline koht sinu andmetele

✖
[Skip to main content](https://nextcloud.tennis24.ee/index.php/apps/maps/#app-content) [Skip to navigation of app](https://nextcloud.tennis24.ee/index.php/apps/maps/#app-navigation)
Aadam ja Eeva, Bastioni käigud, Vanalinn, Kesklinna linnaosa, Tallinn, Harju maakond, 10130, Eesti

10 m

[+](https://nextcloud.tennis24.ee/index.php/apps/maps/#)
[-](https://nextcloud.tennis24.ee/index.php/apps/maps/#)
[Leaflet](https://leafletjs.com/) | © [OpenStreetMap](http://openstreetmap.org/) contributors, [CC-BY-SA](http://creativecommons.org/licenses/by-sa/2.0/)the 

### Steps to reproduce

As the error message will be displayed from time to time i cannot write down an algorithm for that.

### Expected behavior

No error message appears if there is no error.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Is this bug present after an update or on a fresh install of the app?

Updated from a minor version

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
kalmer@test:/projektid/nextcloud$ sudo -u www-data php occ config:list system
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ php occ config:list system
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ ./occ config:list system
-bash: ./occ: Permission denied
```

### List of activated Apps

```shell
kalmer@test:/projektid/nextcloud$ sudo -u www-data php occ app:list
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ php occ app:list
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
kalmer@test:/projektid/nextcloud$ ./occ app:list
-bash: ./occ: Permission denied
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by tacruc** [comment]
Which version of maps are you using?

**Comment by piiskop** [comment]
It seems to be corrected meanwhile. i reported it in November. That issue was still present a while ago, maybe a week ago or so. Now, i have the version [Nextcloud Hub 3](https://nextcloud.com/) (25.0.4).
