### ISSUE TITLE
[Bug]: No dark mode?

### ISSUE THREAD

**Issue by illnesse** [nextcloud/maps#881]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

can't seem to find any option regarding dark mode, which would be really nice to have!

![image](https://user-images.githubusercontent.com/40355982/200304719-3fdad2f4-8a01-47d2-bf77-42fd95893a30.png)

![image](https://user-images.githubusercontent.com/40355982/200304640-9aebcdb1-da1a-4839-92b5-9018b55c6ed3.png)

### Steps to reproduce

1.
2.
3.

### Expected behavior

go dark

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
maps
```

**Comment by jospoortvliet** [comment]
Please have a closer look - there is a reason this is mentioned as a feature, as, well it works just fine...

![Screenshot_20230224_184040](https://user-images.githubusercontent.com/551757/221250305-4a1be737-54bd-4b5c-bc38-edb0c6d82410.png)
