### ISSUE TITLE
Submitting OSM map (error) notes

### ISSUE THREAD

**Issue by bkil** [nextcloud/maps#884]
There exist similar third party mapping projects that also support [adding POI](https://wiki.openstreetmap.org/wiki/Onosm.org) or reporting errors via forms over map notes. Consider whether such a simple workflow of contribution could be integrated to the map widget.

https://wiki.openstreetmap.org/wiki/Notes

See also #883

**Comment by tacruc** [comment]
Hi I would actually prefer to advertise [StreetComplete](https://streetcomplete.app/)? I think this has the lowest entry burden and could actually get people to contribute.

**Comment by bkil** [comment]
@tacruc This issue is about extending the NextCloud Maps widget with controls that will communicate through the OSM API. I think you wanted to comment this on #883 instead?

**Comment by tacruc** [comment]
No I wanted to comment here. I would rather like to point to tools which are good for editing stuff, than including a new feature which needs to be maintained. As currently maps main issue is not too little features but stability.

**Comment by bkil** [comment]
If you prefer to not implement this in the near future, feel free to close _this_ one. I only opened it because @jancborchardt suggested it on our meeting.

**Comment by tacruc** [comment]
What do you think of a right click action pointing to
https://www.openstreetmap.org/note/new?lat={lat}&lon={lon}#map={zoom}/{center-lat}/{center-lon}

**Comment by bkil** [comment]
Sure, that would be helpful.
