### ISSUE TITLE
show pictures in maps uploaded from my computer

### ISSUE THREAD

**Issue by dirk80** [nextcloud/maps#886]
Hi,
It would be great to be able to upload pictures into the maps app from my computer which maps than stores somewhere within Nextcloud and is showing the picture at the GPS data location.
This would make it dead simple to add pictures to a map for me and others which servers are not supporting cron jobs.
Is it possible to be implemented?
Thanks.
Dirk

**Comment by tacruc** [comment]
I see two requests:

- Show picture uploaded via webdav clients
Implemented and working upto other Issues reported
- Something about servers not supporting cron jobs.
In principle this works, the background jobs just needs to be executed. I don't see how a server can not support cron jobs? Webcron should be possible to configure on any server.
With AJAX background jobs one backgroundjob is executed per pageload. So after many page reloads the photos show up on the map.

**Comment by dirk80** [comment]
My request was not to upload via webday client but through the browser. This feature has not been added. Please open the request again.

**Comment by tacruc** [comment]
Works the same, it doesn't matter from where you upload the images to nextcloud

**Comment by dirk80** [comment]
ok. I can see the pictures in the picture app of Nexcloud but not in the maps app.
