### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SKB-CGN** [nextcloud/maps#889]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Maps is trying to load filetypes.js but this file returns a 404. Looking into the folder, it is not inside this one.

### Steps to reproduce

Not applicable

### Expected behavior

Load the page without errors

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

Fresh Nextcloud Server install

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
sudo -u www-data php occ app:list
php occ app:list
./occ app:list
```

**Comment by tacruc** [comment]
Closed by #731

**Comment by SKB-CGN** [comment]
Hi,
updated to the last Maps Version and still 
`/apps/maps/js/filetypes.js?v=3cbe1edc-18` is casusing errors. Now its blocked due to a MIME Type and further more producing an 404 error.

**Comment by tacruc** [comment]
It's not released in stable.

**Comment by SKB-CGN** [comment]
Ah, ok. May i ask, how to install it?

**Comment by tacruc** [comment]
occ app:install --allow-unstable maps

But notice that v0.2.5-1-nightly is a nightly and not a stable release. I expect more issues, but spotting those would be a great help.

**Comment by SKB-CGN** [comment]
NC says, maps is already installed

**Comment by tacruc** [comment]
Then I guess you have to update
occ app:update --allow-unstable maps
