### ISSUE TITLE
l18n: Need context for translation

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/maps#927]
Hello,

https://github.com/nextcloud/maps/blob/3538507488ce5c9dc60d8cac2bf1227370349338/src/views/App.vue#L824

Would be `Photo {photoName} added to map {mapName}` be correct?

https://github.com/nextcloud/maps/blob/3538507488ce5c9dc60d8cac2bf1227370349338/src/views/App.vue#L830

Would be `Failed to save photo {photoName} to map {mapName}` be correct?

@tacruc 

Issue has been reported at Transifex.

**Comment by tacruc** [comment]
Probably photo would be bedder here.

**Comment by tacruc** [comment]
I don't have my laptop around now, might be able to do it tomorrow.
