### ISSUE TITLE
Map Sharing  / GPX KML association and or sharing

### ISSUE THREAD

**Issue by xes** [nextcloud/maps#928]
Currently there is no way to protect a link share with a password or apply any kind of restrictions on it.
If you take care of your contents i would say it is like say do-not-use-this.

Would it be possible to apply the same share possibilities of other Nextcloud modules?

As alternative would it be possible to associate gpx/kml files with the map application?
After that, sharing map export files could be used to send maps to other internal users without the need to save and then re-import these maps.

**Comment by tacruc** [comment]
Have you tested v0.2.5-1-nightly?

**Comment by xes** [comment]
Is the nightly version compatible with NC 24 ?

**Comment by tacruc** [comment]
No, unfortunately due to the design update I had to drop NC24 compatiblity.

**Comment by tacruc** [comment]
> Currently there is no way to protect a link share with a password or apply any kind of restrictions on it.
If you take care of your contents i would say it is like say do-not-use-this.

I'm not sure if I agree with that statement. The way most users communicate the password (In a message or though the same channel as the link), there is no significant security win by the password.  
Let me explain: The link includes a token, which is sufficiently random to be not guessable. Therefore there is already  a password encoded in the link. So people without the link wont be able to see the content, as guessing the link is as complicated as guessing the password.

Anyhow if you would like to generate a link with password, include the favorites on a new map and share the map.
