### ISSUE TITLE
Open Viewer when clicking on photo

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/maps#93]
When clicking on a photo, right now it opens a new tab with the files view, which breaks the flow.

Much better would be to simply open the [Viewer](https://github.com/nextcloud/viewer/) with the photo. Navigation left-right in the viewer should probably work just like in the folder, to go to the next newer or previous older picture. (In the case of a track this will also correspond to where you were first etc.)

**Comment by eneiluj** [comment]
It's in progress in Viewer app development. We'll be informed in https://github.com/nextcloud/viewer/issues/157 when it's available.
