### ISSUE TITLE
[Bug]: Map not visible and impossible to delete

### ISSUE THREAD

**Issue by xes** [nextcloud/maps#942]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After applied the upgrade to v0.2.5-2-933-nightly, saved maps are not visible and there is no way to delete them.

### Steps to reproduce

Import a map, try to delete

### Expected behavior

Should be possible to delete maps

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
maps
```

**Comment by tacruc** [comment]
They are stored in your files within the Maps folder. In general folders are shown on the maps app, iff they contain a ".index.maps" file.
Each map correspond to a folder. Just delete the folder form the files app and any trace of the map is deleted.

If you cannot find the folder the issue is that the map is never created and hence cannot be deleted. You should find a corresponding error in the logs. This would be helpful for further debug.

**Comment by tacruc** [comment]
Sorry one more question.
What do you mean by:

> Import a map, try to delete

**Comment by xes** [comment]
I mean, once you manage to import a map, it cannot be deleted. 
I was expecting to have a "delete" option on the 3 dot menu.
Then, i have a map loaded years ago with hundreds of pushpins. Now pushpins are not visible and map cannot be deleted. 

Now i have deleted the "Maps" folder and my map is still listed but no pin is visible on the map.

**Comment by tacruc** [comment]
What don't understand what you mean by "import a map"

**Comment by xes** [comment]
Thank you for your patience..
Since years, I'm importing set of favorites loading Google Maps kml/kmz files of hundred or thousand of points/coordinates. 
(My favorites -> Import" -> kml)

Now these "Maps" or set of favorites are still there but all the points/pushpins are vanished and I can't find a way to delete those sets.

Also importing them again fails with no output with no error message.

**Comment by tacruc** [comment]
Sorry, then we talked about different features. 
Is this related to #845?

**Comment by idoodler** [comment]
I am new to nextcloud and this app. I am organizing all my travels in iCloud (migrated to Nextcloud now). So i tried to create a file `.index.maps` in one of the travel folders, tho I can't find it in the map app. I think it is related to this issue.

**Comment by tacruc** [comment]
@idoodler This feature is currently under development and only available  in the nightly builds after of v0.2.5

**Comment by tacruc** [comment]
Duplicate #845
