### ISSUE TITLE
[Bug]: Maps and Talk not compatible

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#947]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the talk app is enabled, the maps app won't show content.
Probably leaflet e.g. window.L is overwritten by a talk script and then missing some modules.

This could happen here: https://github.com/nextcloud/spreed/blob/c4c87ba5480cc28efcf793580f2bb6754aa1fa4c/src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue#L54-L60 

### Steps to reproduce

1. Enable maps in v0.2.5-x-nightly
2. See that the maps works
3. Enable Talk app
4. Map won't show content
6. Disable Talk maps working again.

### Expected behavior

Show content of the maps app.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- maps
- talk
```

### Browser Console

```shell
> TypeError: Function.prototype.bind called on incompatible target
>     easyButton easy-button.js:320
>     initLayers Map.vue:589
>     onMapReady Map.vue:258
>     VueJS 4
>     mounted LMap.js:354
>     VueJS 9
>     mounted LMap.js:342
>     VueJS 13
>     main main.js:99
>     restoreOptions optionsController.js:39
>     promise callback*restoreOptions optionsController.js:36
>     <anonymous> main.js:95
>     EventListener.handleEvent* main.js:87
>     <anonymous> maps-main.js:196345
>     <anonymous> maps-main.js:196347
> vue.runtime.esm.js:3049
```

**Comment by nickvergessen** [comment]
The problem is the talk-files-sidebar.js
https://github.com/nextcloud/spreed/blob/4e857ae62632bd2d8b467c503ac6a149c365f00c/lib/Files/TemplateLoader.php#L98
It is meant to only register on the Files app in it's sidebar.

But the Maps app is triggering the event of the files app, instead of it's own?
https://github.com/nextcloud/maps/blob/666284415e6fe417ededb667bfe7576b46596516/lib/Controller/PageController.php#L72
Or what is the goal with dispatching an event of the files app?

**Comment by nickvergessen** [comment]
Temporary patch to disable the files sidebar integration of talk when the URL is the maps app:

```diff
diff --git a/lib/Files/TemplateLoader.php b/lib/Files/TemplateLoader.php
index c129c1854..297a214ae 100644
--- a/lib/Files/TemplateLoader.php
+++ b/lib/Files/TemplateLoader.php
@@ -95,7 +95,9 @@ class TemplateLoader implements IEventListener {
 
 		Util::addStyle(Application::APP_ID, 'At');
 		Util::addStyle(Application::APP_ID, 'icons');
-		Util::addScript(Application::APP_ID, 'talk-files-sidebar');
+		if (strpos(\OC::$server->getRequest()->getPathInfo(), '/apps/maps') !== 0)
+			Util::addScript(Application::APP_ID, 'talk-files-sidebar');
+		}
 
 		if ($user instanceof IUser) {
 			$this->publishInitialStateForUser($user, $this->rootFolder, $this->appManager);
```
