### ISSUE TITLE
Offset -1 not within [0, 731422]

### ISSUE THREAD

**Issue by FrouxBY** [nextcloud/maps#96]
Hi,
I'm testing this first release, and it seems awesome for now ! Good job to you !

Of course there are still some bugs, and this one that occurs on some of my files 

` [lsolesen\pel\PelDataWindowOffsetException]`
` Offset -1 not within [0, 731422]`

The higher value change depending on the file, it seems to append on some old files (all jpg), but I have no error on them in the Viewer, so they don't seem corrupt either.

Furthermore, the scan crash on those error, and maybe having a warning + skip the file might be a better behaviour, since this interrupt the scan for all user, despite a lot of valid file which could be displayed.

Thanks again,
cheers

**Comment by eneiluj** [comment]
Hey, thanks for the feedback. It has already been solved in #91 and will be included in v0.1.2 soon.

**Comment by FrouxBY** [comment]
Perfect, I did'nt see the PR !
