### ISSUE TITLE
PHP8.2 support

### ISSUE THREAD

**Issue by derritter88** [nextcloud/maps#983]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I am running the current NC 26 beta 5 to test/use PHP8.2 FPM.
I just recognised that Maps is not supporting it so I edited the info.xml the bypass the restriction.

So far the Maps app works but if I move the map it hangs sometimes.
Zooming in & out again usually solves the problem.
I think this is a similar problem to https://github.com/nextcloud/maps/issues/786

**Describe the solution you'd like**
Make Maps compatible to PHP 8.2

**Describe alternatives you've considered**
-
**Additional context**
I am currently using [v0.2.5-9-nightly](https://github.com/nextcloud/maps/releases/tag/v0.2.5-9-nightly)

**Comment by tacruc** [comment]
#984

**Comment by derritter88** [comment]
> #984

Thanks!

**Comment by tacruc** [comment]
Can you test #985 ?

**Comment by derritter88** [comment]
Simply by downloading the new package-lock.json and putting it into the maps directory?

**Comment by tacruc** [comment]
I think you will need the package.json, too
Then you would need to rebuild it with
`Npm ci`
And 
`npm run build`

**Comment by derritter88** [comment]
As you have already merged your change to master I just cloned the repo and compiled it.
#985 fixed the problem with the tiles - thanks!

**Comment by derritter88** [comment]
I get several error messages at my NC log:

```
{"reqId":"ZAESEX0DXXLRfNeASNG5aQAAAgc","level":4,"time":"2023-03-02T22:16:01+01:00","remoteAddr":"192.168.10.2","user":"3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3","app":"no app in context","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=00111","message":"Could not boot maps: Failed opening required '/var/www/cloud/apps/maps/lib/Service/../../vendor/autoload.php' (include_path='/var/www/cloud/apps/news/vendor/pear/net_url2:/var/www/cloud/3rdparty/pear/archive_tar:/var/www/cloud/3rdparty/pear/console_getopt:/var/www/cloud/3rdparty/pear/pear-core-minimal/src:/var/www/cloud/3rdparty/pear/pear_exception:/var/www/cloud/apps')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.8","exception":{"Exception":"Error","Message":"Failed opening required '/var/www/cloud/apps/maps/lib/Service/../../vendor/autoload.php' (include_path='/var/www/cloud/apps/news/vendor/pear/net_url2:/var/www/cloud/3rdparty/pear/archive_tar:/var/www/cloud/3rdparty/pear/console_getopt:/var/www/cloud/3rdparty/pear/pear-core-minimal/src:/var/www/cloud/3rdparty/pear/pear_exception:/var/www/cloud/apps')","Code":0,"Trace":[{"file":"/var/www/cloud/lib/composer/composer/ClassLoader.php","line":578,"function":"include"},{"file":"/var/www/cloud/lib/composer/composer/ClassLoader.php","line":432,"function":"Composer\\Autoload\\{closure}","class":"Composer\\Autoload\\ClassLoader","type":"::","args":["*** sensitive parameters replaced ***"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"__construct","class":"ReflectionClass","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/ServerContainer.php","line":155,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/apps/maps/lib/AppInfo/Application.php","line":78,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":171,"function":"OCA\\Maps\\AppInfo\\{closure}","class":"OCA\\Maps\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":487,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/apps/maps/lib/AppInfo/Application.php","line":86,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\Maps\\AppInfo\\Application","type":"->"},{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":213,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":141,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/cloud/lib/base.php","line":1030,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/cloud/apps/maps/lib/Service/PhotofilesService.php","Line":37,"message":"Could not boot maps: Failed opening required '/var/www/cloud/apps/maps/lib/Service/../../vendor/autoload.php' (include_path='/var/www/cloud/apps/news/vendor/pear/net_url2:/var/www/cloud/3rdparty/pear/archive_tar:/var/www/cloud/3rdparty/pear/console_getopt:/var/www/cloud/3rdparty/pear/pear-core-minimal/src:/var/www/cloud/3rdparty/pear/pear_exception:/var/www/cloud/apps')","exception":[],"CustomMessage":"Could not boot maps: Failed opening required '/var/www/cloud/apps/maps/lib/Service/../../vendor/autoload.php' (include_path='/var/www/cloud/apps/news/vendor/pear/net_url2:/var/www/cloud/3rdparty/pear/archive_tar:/var/www/cloud/3rdparty/pear/console_getopt:/var/www/cloud/3rdparty/pear/pear-core-minimal/src:/var/www/cloud/3rdparty/pear/pear_exception:/var/www/cloud/apps')"},"id":"64011211ce444"}

{"reqId":"ZAESEX0DXXLRfNeASNG5aQAAAgc","level":3,"time":"2023-03-02T22:16:01+01:00","remoteAddr":"192.168.10.2","user":"3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3","app":"PHP","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=00111","message":"require_once(/var/www/cloud/apps/maps/lib/Service/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/cloud/apps/maps/lib/Service/PhotofilesService.php#37","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.8","data":{"app":"PHP"},"id":"64011211ce452"}

{"reqId":"ZAESEX0DXXLRfNeASNG5aQAAAgc","level":3,"time":"2023-03-02T22:16:01+01:00","remoteAddr":"192.168.10.2","user":"--","app":"PHP","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=00111","message":"include_once(/var/www/cloud/apps/maps/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/cloud/apps/maps/lib/AppInfo/Application.php#48","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.8","data":{"app":"PHP"},"id":"64011211ce581"}
´´´

**Comment by derritter88** [comment]
I just tried the regular app from the NC app store. There are also some log entries:

´´´
{"reqId":"ZAGZzzQmL7bnpPZPhb0nmgAAVgU","level":3,"time":"2023-03-03T07:55:16+01:00","remoteAddr":"192.168.10.2","user":"3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"include(/var/www/cloud/apps/maps/lib//AppInfo/Application.php): Failed to open stream: No such file or directory at /var/www/cloud/lib/composer/composer/ClassLoader.php#578","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.8","data":{"app":"PHP"},"id":"64019a09905ea"}

{"reqId":"ZAGZzzQmL7bnpPZPhb0nmgAAVgU","level":3,"time":"2023-03-03T07:55:16+01:00","remoteAddr":"192.168.10.2","user":"3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3","app":"no app in context","method":"POST","url":"/settings/apps/enable","message":"App maps threw an error during app.php load and will be disabled: Class \"OCP\\AppFramework\\Db\\Mapper\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.8","exception":{"Exception":"Error","Message":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found","Code":0,"Trace":[{"file":"/var/www/cloud/lib/composer/composer/ClassLoader.php","line":578,"function":"include"},{"file":"/var/www/cloud/lib/composer/composer/ClassLoader.php","line":432,"function":"Composer\\Autoload\\{closure}","class":"Composer\\Autoload\\ClassLoader","type":"::","args":["*** sensitive parameters replaced ***"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"__construct","class":"ReflectionClass","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":84,"function":"array_map"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/ServerContainer.php","line":155,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/apps/maps/appinfo/application.php","line":33,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":171,"function":"OCA\\Maps\\AppInfo\\{closure}","class":"OCA\\Maps\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":487,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/apps/maps/appinfo/application.php","line":41,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/cloud/lib/private/ServerContainer.php","line":107,"function":"__construct","class":"OCA\\Maps\\AppInfo\\Application","type":"->"},{"file":"/var/www/cloud/lib/private/ServerContainer.php","line":186,"function":"getAppContainer","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/cloud/lib/private/ServerContainer.php","line":153,"function":"getAppContainerForService","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/cloud/apps/maps/appinfo/app.php","line":20,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":316,"args":["/var/www/cloud/apps/maps/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":192,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":1062,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/cloud/lib/private/Installer.php","line":164,"function":"executeRepairSteps","class":"OC_App","type":"::"},{"file":"/var/www/cloud/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/cloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/cloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/cloud/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/cloud/apps/maps/lib/DB/GeophotoMapper.php","Line":18,"message":"App maps threw an error during app.php load and will be disabled: Class \"OCP\\AppFramework\\Db\\Mapper\" not found","CustomMessage":"App maps threw an error during app.php load and will be disabled: Class \"OCP\\AppFramework\\Db\\Mapper\" not found"},"id":"64019a09905cf"}

{"reqId":"ZAGZzzQmL7bnpPZPhb0nmgAAVgU","level":3,"time":"2023-03-03T07:55:16+01:00","remoteAddr":"192.168.10.2","user":"3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"include(/var/www/cloud/apps/maps/lib//AppInfo/Application.php): Failed to open stream: No such file or directory at /var/www/cloud/lib/composer/composer/ClassLoader.php#578","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.8","data":{"app":"PHP"},"id":"64019a09905ea"}
´´´

**Comment by derritter88** [comment]
> The second one is a duplicate of #948 The others I looks like files are missing. What does the signing status say?

How do I verify the signing status?

**Comment by tacruc** [comment]
In the admin settings somewhere.
Anyhow on maps v0.2.4 you will run into the issue #948 such that it won't work on NC26.

**Comment by derritter88** [comment]
Ah okay the regular Nextcloud signing status. 
It says that everything is fine and nothing found.

Also the integrity check didn't show any errors.

I just pulled the current master repo and modified it for PHP8.2 and compiled it with the above mentioned npm commands.

**Comment by derritter88** [comment]
Where are the dependencies listed? `package.json`?

**Comment by tacruc** [comment]
composer.json
its the php dependencies.

**Comment by derritter88** [comment]
Thanks.

I just crosschecked my NC folders now + the error message.
According to the the error message your app tries to register to some kind of service

```
[PHP] Fehler: include_once(): Failed opening '/var/www/cloud/apps/maps/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/cloud/3rdparty/pear/archive_tar:/var/www/cloud/3rdparty/pear/console_getopt:/var/www/cloud/3rdparty/pear/pear-core-minimal/src:/var/www/cloud/3rdparty/pear/pear_exception:/var/www/cloud/apps') at /var/www/cloud/apps/maps/lib/AppInfo/Application.php#48

PROPFIND /remote.php/dav/files/3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3/KSV
from 192.168.10.2 at 2023-03-03T09:14:47+01:00
```

```
        public function register(IRegistrationContext $context): void {
                // ... registration logic goes here ...

                // Register the composer autoloader for packages shipped by this app, if applicable
                include_once __DIR__ . '/../../vendor/autoload.php';
                $context->registerEventListener(
                        LoadAdditionalScriptsEvent::class,
                        LoadAdditionalScriptsListener::class
```


But I wasn't able to find this file.
May I ask what exactly does this autoload.php?

**Comment by tacruc** [comment]
Sorry maybe I forgot, you should probably also run
`make`
to install the php dependencies. But this is what is failing in the test https://github.com/nextcloud/maps/actions/runs/4315929083/jobs/7531002675#step:8:25

**Comment by derritter88** [comment]
Thanks - the `make` command removed the error messages.
As you have mentioned it also showed the dependency error.

With my little dev knowledge I have just done what the shell recommended and ran `composer update` which downloaded new versions of the dependencies.

After that the whole make process was running without any error message regarding maps.
Only some I guess general PHP warning messages appeared:
```
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:48
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:56
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:884
```

I then moved the compiled maps app to Nextcloud and enabled it.
It runs, there are no errors and also the tiles are moving as expected.

**Comment by tacruc** [comment]
Yes the problem is that after composer update
make fails on php8.0 and php7.4
Dropping php7.4 is fine for me, but I would like to provide one release with php8.0 before dropping the support.

**Comment by tacruc** [comment]
Also NC25 supports php8.0 and php8.1, but not php8.2

**Comment by derritter88** [comment]
Ah okay so the issue comes from older PHP versions..

Would it work to ship dependencies for more PHP versions within the same app and the client uses the right one depending on the local version?

**Comment by tacruc** [comment]
I don't know how.
It might even be that some release I between supports both.

**Comment by tacruc** [comment]
Could you test v1.1.0-nightly?

**Comment by nodiscc** [comment]
Sorry for the late feedback, it appears to work perfectly, thanks!
